### ISSUE TITLE
Bugfix compatibility

### ISSUE THREAD

**Issue by MartijnDwars** [mollie/mollie-api-php#10]
Wouldn't it be a good idea to make a new release with [this](https://github.com/mollie/mollie-api-php/commit/854a3714e00e0ca10803da137fa4a3077edf0625) fix? I'm currently on PHP 5.4.36 and Composer automatically loads 1.2.0 (since that's the latest release), which fails..

**Comment by Daanvm** [comment]
Hi Martijn,
I just created a new release. I hope this fixes your issues.

**Comment by MartijnDwars** [comment]
It does, thanks! :+1:
