### ISSUE TITLE
Geen payment ID in POST naar webhook

### ISSUE THREAD

**Issue by robinklaassen** [mollie/mollie-api-php#11]
Ik ben in een lokale omgeving jullie PHP API aan het uitproberen (dus ook met een testkey). Ik volg daarbij de voorbeelden op Github. Echter geeft mijn webhook een melding dat er geen parameter 'id' in $_POST zit (en daarna gaat dus ook het ophalen van de status van de betaling fout).

Ik vroeg me af of dit intended behaviour is en zo niet, wat ik er dan aan kan doen. Wil op verzoek zeker  mijn code posten maar ze verschillen eigenlijk niet wezenlijk van jullie voorbeelden.

Alvast bedankt!

**Comment by RickWong** [comment]
Hi Robin. Voor onze webservers is het belangrijk dat zij je webhookUrl kunnen bereiken. Als die webhookUrl op een lokale omgeving draait, is de kans groot dat die alleen bereikbaar is op jouw computer. Controleer dit even voordat je verder gaat. Ook is het belangrijk dat er geen redirects plaatsvinden op de webhookUrl. Door redirects kun je namelijk ook POST-data verliezen.

Verder geven wij by-design geen betaalgegevens mee aan de redirectUrl. De redirectUrl is hoort geen acties te doen of Mollie API requests uit te voeren. Er moet puur gekeken worden naar de orderstatus in je database. (Die orderstatus wordt al geupdate door de webhook.)

Laat 't me weten als je verder nog vragen hebt.

**Comment by robinklaassen** [comment]
Oh, wat dom. Daar had ik best zelf even aan kunnen denken :') ik zal het verdere testen in een online omgeving gaan doen. Voor de rest heb ik op dit moment geen vragen, dank je wel voor je snelle antwoord!

**Comment by MartijnDwars** [comment]
Mocht je lokaal willen ontwikkelen maar toch Mollie webhooks ontvangen kun je ngrok.com eens proberen. Daarmee zet je zonder veel poespas een tunnel open naar je eigen machine.

**Comment by lvgunst** [comment]
Ja ngrok is een hele fijne tool om lokaal webhooks te testen. Bedankt voor het vermelden. Ik zal hier binnenkort nog een artikel over schrijven voor op onze [support pagina](https://www.mollie.com/nl/support/)

**Comment by robinklaassen** [comment]
Bedankt voor de tip! Inmiddels heb ik al wel een online testversie aan de praat gekregen gelukkig. Na een heleboel gehannes met de automatische CSRF-beveiliging van het PHP framework waar ik in werk. De Mollie API zelf werkt erg prettig, goed werk mannen :)
