### ISSUE TITLE
The webhook location is invalid.

### ISSUE THREAD

**Issue by kamov** [mollie/mollie-api-php#111]
I tested your example by adding my test API key, but checking examples/01-new-payment.php
I have error:

API call failed: Error executing API call (request): The webhook location is invalid.

I found similar issue here https://github.com/mollie/mollie-api-php/issues/70
but not sure how he fixed it.

I am testing from localhost. 
When I try to add localhost in web profile, it's not allowed me.
So I guess where to change webhook location.

Thanks

**Comment by TheJenne18** [comment]
Mollie can't reach you localhost webhook.

The webhook needs to be accessible from any location on the web.

**Comment by kamov** [comment]
Yes, I got the point. I see here https://help.mollie.com/hc/en-us/articles/213470409-My-webhook-URL-is-invalid-or-not-working-What-is-the-problem-

**Comment by jimkaler** [comment]
do we have to update order in database from that webhook url?

**Comment by TheJenne18** [comment]
what do you mean?

**Comment by jimkaler** [comment]
@TheJenne18  I 've got it . but I am getting error Trying to get property of non-object while using 
$payment = $mollie->payments->get($payment->id); 
I dont know why i am getting this error in webhook url.

**Comment by abbatis** [comment]
How would you test it on your local machine then?

**Comment by robindirksen1** [comment]
@abbatis use a tool like this one; https://localtunnel.github.io/www/

**Comment by abbatis** [comment]
@robindirksen1 Yeah I thought so, I have ngrok so I'll use that. Thanks.

Makes me wonder though, how come it always worked correctly without tunneling before v2?

**Comment by sandervanhooft** [comment]
For manual inspection I sometimes use this one: https://webhook.site

**Comment by awaisZtabs** [comment]
> How would you test it on your local machine then?

ngrok
