### ISSUE TITLE
Language of mollie is wrong in the example

### ISSUE THREAD

**Issue by kamov** [mollie/mollie-api-php#112]
When I test example, the language of mollie page is always wrong.
I don't mean first screen where you select payment method, but second screen.

![screen shot 2017-09-26 at 08 58 06](https://user-images.githubusercontent.com/2345000/30846683-f054c36e-a298-11e7-8c6d-746abc5ee69f.png)

My browser is in english, so I am not sure why it's loaded in Dutch.

**Comment by willemstuursma** [comment]
Thanks for bringing this up. At the moment, we only offer Dutch test screens.
We're working on bringing localized test mode payment, it won't take too long!
