### ISSUE TITLE
Create mandate not work

### ISSUE THREAD

**Issue by kamov** [mollie/mollie-api-php#113]
In the example 22-create-mandate-subscription.php

I can see only that customer is created, and then I don't see

    echo "<p>Mandate created with id ". $mandate->id."</p>";

nor

    echo "<p>Subscription created with id ". $subscription->id."</p>";

There is not any errors

**Comment by danger89** [comment]
Any update from the developers?

**Comment by Smitsel** [comment]
Hello! thanks for spotting this.

Tried running the example right of the bat with the same result.
In my error log i found out that the IBAN in this example does not meet our IBAN check requirements. So i replaced it with a randomly generated one that does.

With PR https://github.com/mollie/mollie-api-php/pull/133 the script runs straight away.
