### ISSUE TITLE
Idea: Bump php version in the composer.json

### ISSUE THREAD

**Issue by Tjoosten** [mollie/mollie-api-php#115]
https://github.com/mollie/mollie-api-php/blob/6c0b4ba383a3b88aaba8b5051d9024235de46951/composer.json#L19

Hi, 

My idea was to bump the php version. Because php 5.2 is not supported anymore.

**Comment by willemstuursma** [comment]
We're no longer able to automatically build using Travis on 5.2, so I agree that we should bump it to 5.3 min.

**Comment by Tjoosten** [comment]
Hi @willemstuursma @Smitsel 

If you want i like to try to bump this one?

**Comment by willemstuursma** [comment]
Sure, pull requests are welcome.
