### ISSUE TITLE
Add HTTP code to Location headers

### ISSUE THREAD

**Issue by willemstuursma** [mollie/mollie-api-php#119]
Prevent clients from accidentally using 307 redirects which will break some (but not all) payment methods / issuers. Correct code is 303. https://stackoverflow.com/a/4764473/6632554

**Comment by Smitsel** [comment]
I've made a PR: https://github.com/mollie/mollie-api-php/pull/132

Please note there is also an explanation in the description of the PR explaining why we want this.
