### ISSUE TITLE
Amount valuta

### ISSUE THREAD

**Issue by wmdiensten** [mollie/mollie-api-php#12]
Hello,

It would be great to add the ability to set the not only the amount but including the valuta.
Our system uses EUR and USD but the amount is diffrent, now we only support EUR.

Kind Regards
Erik

**Comment by Daanvm** [comment]
Hi,

Currently our system only works for euro payments. However, some payment methods like PayPal and Creditcard can be paid by consumers in dollars or other currencies. The conversion is done by PayPal or their Creditcard supplier. It is not possible to specify the amount in dollars.

I hope this works for you.

**Comment by mufi-zwt** [comment]
Hi There,
Does it now supports USD or still works for only EUR?
