### ISSUE TITLE
Using multiple payment methods.

### ISSUE THREAD

**Issue by sjorsvanheuveln** [mollie/mollie-api-php#122]
I want to use a selection of payment methods. Currently I only have ideal. How can I expand this?
Say I only want to use PayPal, iDeal and Bancontact. How do I do this?

$payment = $mollie->payments->create(array(
		"amount"       => $amount,
		"description"  => $_GET['upgrade']." Maand(en) Premium Upgrade",
		"redirectUrl"  => "http://mysite.nl/return_page.php?months={$months}",
		"webhookUrl"   => "http://mysite.nl/betaaltest/02-webhook-verification.php",
		"method"       => 'ideal',
		"metadata"     => array(
		"order_id" => $order_id,
		"uid" => $_SESSION['uid'],
		"months" => $months,
		),
	));

**Comment by willemstuursma** [comment]
You should enable the correct payment methods in your Dashboard and then leave the `method` parameter blank.
