### ISSUE TITLE
Outdated links in PHPDoc

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#124]
Some links used in the PHPDoc seem to be outdated. 

For example https://github.com/mollie/mollie-api-php/blob/ad566702895b41ca62c5d74583c582b08b19173b/src/Mollie/API/Object/Settlement.php#L63 points to https://www.mollie.com/en/docs/overview#settlements-object, which seems not the proper page. It should probably link the "the 'period object' section" on https://www.mollie.com/en/docs/reference/settlements/get, but this section can not be linked properly. 😢 . 

When [searching the repository](https://github.com/mollie/mollie-api-php/search?utf8=%E2%9C%93&q=https%3A%2F%2Fwww.mollie.com%2Fen%2Fdocs%2F&type=), more candidates can be found.

Since the response of an API call like `$apiClient->settlements->all()` returns a data structure which only uses objects of type `stdClass`, navigating the results becomes a bit "annoying". Outdated links do not contribute to that experience 😉 .

**Comment by willemstuursma** [comment]
Thanks, I'll see if we can improve this. Sorry for the disappointing developer experience.

**Comment by holtkamp** [comment]
Thanks for the swift response! Don't worry, "Disappointing" is not the word. I like the puzzle, but it should read as clear and possible => other people might stop trying quicker...

**Comment by Smitsel** [comment]
Created a PR:
https://github.com/mollie/mollie-api-php/pull/131

Thanks for letting us know @holtkamp
