### ISSUE TITLE
Observation: Settlement.settledDatetime can change?

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#127]
When working with the Settlements API, I noticed that the Settlement.settledDatetime might change. To me this sounds like an immutable property: the Settlement gets settled at timestamp X, which will/can/should never change.

Observations:
- at 2017-11-13 10:39:56 a certain Settlement X has the following properties:
  - Settlement.status: paidout
  - Settlement.createdDatetime: 2017-11-13T05:00:02.0Z
  - Settlement.settledDatetime: 2017-11-13T08:36:02.0Z
- at 2017-11-13 **12:51:29** the same Settlement X has the following properties:
  - Settlement.status: paidout
  - Settlement.createdDatetime: 2017-11-13T05:00:02.0Z
  - Settlement.settledDatetime: **2017-11-13T09:43:48.0Z**

My question: why is this? Is this on purpose? 

The reason why I ask: we import the Settlements at time X, and process the related Payments at time Y. I would expect that at both time X and Y the Settlement.settledDatetime is the same, so we can use this information when processing Settlements and the Payments and still end up with the same information.

In the current situation this information differs. Our "internal" Settlement objects have a different "settledDatetime" than our internal Payment objects. Which is rather strange 😉

**Comment by willemstuursma** [comment]
Thanks for bringing this up.

The settlementDatetime should only change if the settlement get transferred multiple times (for example, if the bank account is closed and the settlement is returned to us).

I'll have a look why this is being changed.

Can you send me an email with the settlement ID? My email address is in my profile.

**Comment by willemstuursma** [comment]
The issue has been resolved.
