### ISSUE TITLE
Request for redirectUrl's

### ISSUE THREAD

**Issue by leolems** [mollie/mollie-api-php#128]
In the payments->create  object there is a redirectUrl when the payment process is over...

BUT i would like to have 2 url's to return to:

1) If the order is paid (or in the process of being payed)
   This is the Thank you for ordering 'kinda' page.. with a summary
2) If the payment is canceled or failed in some way..
    I would like to show them a different page if something went wrong

It would be a great addition for the shop owners to be able to redirect them to a proper response page

**Comment by willemstuursma** [comment]
We won't be providing this. See #18 for earlier discussions.

**Comment by leolems** [comment]
I think it would be an addition... its not much code
