### ISSUE TITLE
Incorrect Retry on connection error check

### ISSUE THREAD

**Issue by NiekvandenBogaard** [mollie/mollie-api-php#136]
https://github.com/mollie/mollie-api-php/blob/5e81dac60352723ec512edd0ce2b9edfb859b888/src/Mollie/API/Client.php#L406

$connectionErrors stores all connection error numbers as KEYS not as VALUES
so 'in_array' function should be replaced by 'array_key_exists' function on the mentioned line.

**Comment by Smitsel** [comment]
Hi Niek,

Nice find! I provided a PR fixing this.
Feel free to create a PR next time :)
