### ISSUE TITLE
Order Status niet altijd geupdate

### ISSUE THREAD

**Issue by PaulKruijt** [mollie/mollie-api-php#14]
Hoi Mollie,

Ik heb een raar probleem dat de status van een bestelling (in onze database) niet geupdate wordt.
Dit gebeurt af en toe en dus niet altijd.
In Mollie staat de status wel op "Betaald", maar in onze DB dus nog op "Niet betaald"

Ik heb de error logs bekeken, maar daar staan geen gekke dingen.
Hebben jullie dit probleem wel eens eerder van andere klanten gehoord?

Misschien een tip hoe ik dit het beste aan kan pakken?
Dank je.

**Comment by Daanvm** [comment]
Hoi Paul,

Ik denk dat je het beste even een email kunt sturen naar info@mollie.com met daarin een voorbeeld van een betaling waar het fout is gegaan. Dan kunnen wij kijken of we kunnen zien waardoor dat komt.

Het klinkt alsof we je webhook niet goed hebben kunnen aanroepen, maar zonder meer informatie wordt het lastig om dat met zekerheid te zeggen.
