### ISSUE TITLE
Included issuers are not wrapped in Mollie_API_Object_Issuer object

### ISSUE THREAD

**Issue by willemstuursma** [mollie/mollie-api-php#141]
```
$all_methods = $api_client->methods->all(0, 0, ["include" => "issuers"]);
```

The issuers are not converted to a `Mollie_API_Object_Issuer` object but instead `stdClass` is used.

Also, there is no `issuers` property on `Mollie_API_Object_Method`.
The `image` property is missing on `Mollie_API_Object_Issuer`.

**Comment by Smitsel** [comment]
This is fixed as of 2.0
