### ISSUE TITLE
Display discount in checkout dialog

### ISSUE THREAD

**Issue by egonolieux** [mollie/mollie-api-php#142]
I have multiple subscription tiers with each their own price. If a user wants to upgrade to a higher tier subscription, I want to subtract the remaining period of the subscription as a discount.

For example: a user paid €20 for subscription X for a year, but wants to upgrade to subscription Y costing €40 3 months later.  The user would receive a (3/12) * €20 = €5 discount making a total of €35.

Is it possible to show this discount in the checkout dialog or is it only possible to show the end result of €35?

**Comment by willemstuursma** [comment]
Sorry, this is not possible using the payments API. 

We'll take this into consideration for any future API's.
