### ISSUE TITLE
308 permanent redirect

### ISSUE THREAD

**Issue by rienheuver** [mollie/mollie-api-php#144]
I'm testing a mollie-setup locally on a project and I've a subdomain of a domainname I own to go to my local pc. On my pc I then setup a virtual host to redirect all incoming requests to my local project. The virtual host is setup to redirect with a 308 instead of a 302, because a 308 can preserve POST parameters. However, this does not seem to be working, probably because mollie simply doesn't act on the 308 http status. Any explanation for this or help on how to tackle this?

I don't want to set my local project straight to that subdomain because then I'll have to change a few other configurations. And this is likely to occur more often in the future, so changing the redirect every time I'm testing is hardly any effort, but changing the other configurations wouldn't be worthwhile.

**Comment by willemstuursma** [comment]
@rienheuver Just to get this clear, the webhook doesn't follow the 308 redirect? Or the method is changed? Could you elaborate a bit?

**Comment by rienheuver** [comment]
By now I've realized that it wouldn't work either way. I was assuming that the webhook doesn't follow the 308, but even if it would, it wouldn't be able to find my local project. So I'll have to mess around with my virtual hosts anway

**Comment by willemstuursma** [comment]
We recommend using ngrok for testing integrations locally.
