### ISSUE TITLE
paidDatetime not ISO8601 compliant

### ISSUE THREAD

**Issue by rienheuver** [mollie/mollie-api-php#146]
I'm trying to implement mollie subscriptions in a laravel project and I want to save the paidDatetime to a mysql-database (also datetime). Since I use Laravel, the date is converted to a Carbon object when I assign it to a model property. However, I can't get this to work so far because the paidDatetime is not ISO8601 compliant. The datetime I'm receiving is: 2018-02-12T12:23:15.0Z
I can't find anything on the ISO8601 wikipedia page about the trailing ".0Z". The Z is known, and parseable by php date functions, but the dot and the zero seem to be unknown. How should I reliably parse this paidDatetime to a php date?

**Comment by rienheuver** [comment]
Oh, this is rather odd... I found a few sources saying that
`DateTime::createFromFormat(DateTime::ISO8601, $timeString);`
should work, but it didn't for me. However, just using
`new DateTime($timeString);`
does work, and the same with Carbon
`new Carbon\Carbon($timeString);`
where $timeString = '2018-02-12T12:23:15.0Z'

**Comment by willemstuursma** [comment]
Thanks for reporting regardless, we'll have a close look.

**Comment by arendvw** [comment]
The dot and the zero are fractional seconds, it's actually 12h 23m 15.0s, in timezone zulu (alias for UTC).

See [this article](https://nbsoftsolutions.com/blog/iso-8601-and-nanosecond-precision-across-languages) about fractional seconds in ISO8601.

**Comment by holtkamp** [comment]
Ok, so `2018-02-12T12:23:15.0Z` is not a valid ISO8601 format?

**Comment by rienheuver** [comment]
the very last line in the [Times](https://en.wikipedia.org/wiki/ISO_8601#Times) section of Wikipedia on ISO8601 very briefly mensions something of the sort. However, running the following:
`DateTime::createFromFormat(DateTime::ATOM, '2018-02-12T12:23:15.0Z')`
returns false, so something seems off about it.
