### ISSUE TITLE
Error executing API call (request): Unauthorized application request.

### ISSUE THREAD

**Issue by kerim55** [mollie/mollie-api-php#148]
Get this error when using applicationFee. No problem without applicationFee.

```       
$connect = Mollie::api()->payments()->create([
    "amount" => str_replace(',', '.', $request->get('params')[ 'amount' ]),
    "description" => $request->get('params')[ 'description' ],
    "redirectUrl" => config('app.url') . '/order/' . $payment->id,
    "webhookUrl" => config('app.url') . '/payments/webhook/',
    "profileId" => collect(session()->get('profiles'))->first()->id,
    "testmode" => 'test',
    "applicationFee"    => array(
        "amount" => '0.25',
        "description" => 'Application Fee',
    ),
]);
```
![naamloos](https://user-images.githubusercontent.com/7556615/36537457-79c8a2ee-17d0-11e8-8c23-0326ead4701e.png)

**Comment by JorikMollie** [comment]
We return this error in two cases:
- Application Fee is not enabled in your account;
- The source and destination account for the application fee are the same;

**Comment by turk55** [comment]
Sounds oke =)

How can I enable Application Fee for my account?

**Comment by JorikMollie** [comment]
I've sent an email with more information.

**Comment by petericebear** [comment]
Can the information be shared somewhere for more people to see it?

**Comment by JorikMollie** [comment]
No problem. I've moved it off GitHub because it required exchanging personal info.

If you send us an email at info@mollie.com with the ID of your account we can activate Application Fees for your account.

**Comment by turk55** [comment]
Mijn ID is 3621224. Alvast bedankt voor uw moeite.
________________________________
