### ISSUE TITLE
Exception on existing subscription

### ISSUE THREAD

**Issue by toonvandeputte** [mollie/mollie-api-php#149]
The PHP library probably just passes on exceptions from the API, but FWIW, here is a possible improvement:

*Existing situation:*

When creation of a subscription is attempted, the API throws an exception if there is an existing subscription with an identical description: `Error executing API call (request): A subscription with the same description already exists for this customer.`
It is unclear whether this exception is only thrown for *active* subscriptions (I suspect it is thrown for both active and canceled subscriptions) and no information is given about the conflicting subscription

*Desired situation:*

The exception thrown contains information about the status of the conflicting subscription, and its id.

**Comment by willemstuursma** [comment]
Thanks for bringing this up, we'll get to this shortly and I'll report back here once we do.

**Comment by willemstuursma** [comment]
This issue will be resolved later today.
