### ISSUE TITLE
Looping through the payment objects

### ISSUE THREAD

**Issue by MurtazaAydogdu** [mollie/mollie-api-php#150]
Hi, I have an methods thats get all the payments. But is it possible to loop through these objects

**Comment by Smitsel** [comment]
Hello, when using the payments->all() you receive an ArrayObject. 
This can be looped through.

See this example: https://github.com/mollie/mollie-api-php/blob/master/examples/05-payments-history.php

**Comment by MurtazaAydogdu** [comment]
Thanks didn't see that exmple
