### ISSUE TITLE
Error 500 when i Upload files on server, running fine in local server

### ISSUE THREAD

**Issue by jimkaler** [mollie/mollie-api-php#158]
Hey guys I am using larevel 5.5 and  I have successfully tested Mollie on local server, but when I upload package from vendor/mollie and vebndor/composer/ to live server it is giving me error "_This page isn’t working_"
If i do not upload vendor/composer folder then its giving error "_Class 'Mollie_API_Client' not found_".
Can anyone please tell me what I am doing wrong here?
Thanks.

Error when vendor/composer is not uploaded

![screenshot from 2018-04-09 12-50-00](https://user-images.githubusercontent.com/36437555/38484542-92aac376-3bf4-11e8-83dd-00c4e22b103b.png)

Error when vendor/composer uploaded

![screenshot from 2018-04-09 12-51-15](https://user-images.githubusercontent.com/36437555/38484586-b5a1f796-3bf4-11e8-8ac6-508de099fd12.png)

**Comment by jimkaler** [comment]
I got sollution for it.

**Comment by Smitsel** [comment]
Hi @jimkaler,

Awesome. Was just typing a reply!

**Comment by jimkaler** [comment]
Hey @Smitsel .

**Comment by lode** [comment]
@jimkaler your test api key is visible in the screenshot, you might want to reset the key in your settings.

**Comment by jimkaler** [comment]
@lode  oops. Thanks buddy.
