### ISSUE TITLE
notifyUrl

### ISSUE THREAD

**Issue by casdr** [mollie/mollie-api-php#16]
Hello,

I'm not sure if it is available in the Mollie API, but I would like to be able to set a notify/IPN url. This will be used so Mollie will send a request with the payment details to the server. I haven't been able to find this option myself yet, but AFAIK the Omnipay module supports it.

**Comment by casdr** [comment]
Ah, I see there is an option in the Website profiles to set the Webhook now.

**Comment by lvgunst** [comment]
You can also set a custom `webhookUrl` when you create a new payment https://www.mollie.com/en/docs/payments#payment-create-optional. Also checkout the examples https://github.com/mollie/mollie-api-php/blob/master/examples/1-new-payment.php#L40

**Comment by casdr** [comment]
Thanks for that tip, @lvgunst
