### ISSUE TITLE
Get all payments between specific dates / months?

### ISSUE THREAD

**Issue by Fossil01** [mollie/mollie-api-php#160]
Is it possible to get all payments in a certain quarter or between two specific dates from the API? If so, how?

**Comment by MurtazaAydogdu** [comment]
You can't https://www.mollie.com/nl/docs/reference/payments/get

**Comment by willemstuursma** [comment]
No sorry, we don't offer this yet.

**Comment by DigitalLeaves** [comment]
+1 for this functionality. It is just so basic stuff that I am amazed there is no way of doing that with the Mollie API.

**Comment by Fossil01** [comment]
Completely agree.

**Comment by tabsl** [comment]
+1 for this functionality
