### ISSUE TITLE
Error: Trying to get property of non-object in webhook

### ISSUE THREAD

**Issue by jimkaler** [mollie/mollie-api-php#161]
Hello guys I am using mollie in laravel
everything is ok but when i am going to update status in database using webhook, its giving me error..
_Trying to get property of non-object_. what do i need to do to solve this issue by using code:

$payment = $mollie->payments->get($payment->id);
_$payment->id_ is giving me error.

Thanks.

**Comment by willemstuursma** [comment]
You should take the ID from the `$_POST` superglobal instead of the non-existing `$payment` object.

**Comment by MurtazaAydogdu** [comment]
How is your route and your function / controller look like.

**Comment by jimkaler** [comment]
@MurtazaAydogdu  
Route::get('/webhook', 'UserReportsController@Webhook');
and controller is defined below in screenshots.
This is UserReportsController

![creating payment](https://user-images.githubusercontent.com/36437555/38617876-bdec6810-3db5-11e8-986d-ce2b568d9a02.png)


![webhookfunction](https://user-images.githubusercontent.com/36437555/38617896-c7efab74-3db5-11e8-8265-d88e02452894.png)

**Comment by MurtazaAydogdu** [comment]
No wonder that you get an empty result. The webhookUrl tries to make a POST request to your api (read the docs https://www.mollie.com/nl/docs/webhook). So change this 

> Route::get('/webhook', 'UserReportsController@Webhook');

to Route::post('/webhook', 'UserReportsController@Webhook');

**Comment by jimkaler** [comment]
Its already Post @MurtazaAydogdu.

![screenshot from 2018-04-12 09-37-22](https://user-images.githubusercontent.com/36437555/38655978-2365ea5c-3e35-11e8-8284-c9a1c665d5a1.png)
