### ISSUE TITLE
How to create a recurring subscription linked to specific mandate for user with multiple mandates.

### ISSUE THREAD

**Issue by tafelnl** [mollie/mollie-api-php#168]
A customer of mine has set up multiple IBAN card mandates by making a one time payment of 0.01 euros through iDeal from different bank accounts, for each of the mandates. Now when I create a recurring subscription, it is always linked to the last created IBAN card mandate. But I want to be able to link one subscription to mandate 1 and another subscription to mandate 2. I cannot find any information on how to do this anywhere in the documentation. Is this a limitation from Mollie or...?

**Comment by Smitsel** [comment]
I'm afraid this is not supported by us. Subscriptions will always use the last mandate.

What you could do is create multiple Customer objects for your customer and give each of these another mandate/subscription. 

Or if you need more flexibility you could always schedule a cronjob to create the payments as subscription yourself.

**Comment by tafelnl** [comment]
Okay, that is unfortunate. Are there any plans supporting such a feature in the future? Because there already is a Mandate List Get feature in the API: https://www.mollie.com/nl/docs/reference/mandates/list

And how exactly would the cronjob you mentioned solve my problem? I still wouldn't be able to link the payment to a specific mandate of my choice right?

**Comment by sandervanhooft** [comment]
This would also be beneficial to Cashier's `switchPaymentMethod`.

**Comment by MollieRick** [comment]
Hi @tafelnl and @sandervanhooft,

It is now possible to set a ``mandateId`` with a subscription. When set, just that mandate will be used for creating payments. 

Small note: When the mandate will be revoked, also the connected subscription(s) will be canceled.

**Comment by sandervanhooft** [comment]
@MollieRick Thanks!

> Small note: When the mandate will be revoked, also the connected subscription(s) will be canceled.

Just curious: Is this also the case if a customer has some existing valid mandates and a mandate is not set upon subscription creation? Does it then fall back to another mandate?

**Comment by MollieRick** [comment]
@sandervanhooft 
>Just curious: Is this also the case if a customer has some existing valid mandates and a mandate is not set upon subscription creation? Does it then fall back to another mandate?

No, the subscription will be canceled at this time because you setting it explicitly. :)
