### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by eaglejohn** [mollie/mollie-api-php#17]
When I include the Mollie API (PHP) in my WordPress code, I get the "headers already sent" error:
```
Warning: Cannot modify header information - headers already sent by (output started at /home/xxx/public_html/wp/wp-content/themes/xxx/header.php:7) in /home/xxx/public_html/wp/wp-content/themes/xxx/Mollie/examples/04-ideal-payment.php on line 67
```

When I call the API directly (http://www.xxx.nl/wp/wp-content/themes/xxx/Mollie/examples/04-ideal-payment.php) everything works fine and I get redirect to the payment page.

Any suggestions?

**Comment by darma-avalos** [comment]
According to the error message the culprit is on the file
 /home/xxx/public_html/wp/wp-content/themes/xxx/header.php
on line 7

**Comment by eaglejohn** [comment]
That's something WordPress does by default on the proper location I guess. The Mollie API is sending headers after a lot of content has already been displayed.

**Comment by darma-avalos** [comment]
The theme should be able to output content without echoing on the header, you can have breadcrumbs and all possible things on header.php, but the output should not display before all headers are sent. 
If you would like me to take a look at your source code, send me a PM..

**Comment by eaglejohn** [comment]
Ehm, how do I send you a PM on GitHub...? :-)

**Comment by darma-avalos** [comment]
Oh yes, I forgot that feature was removed here. If you join this group and post the question there, I’ll do my best to help you out.

https://www.facebook.com/groups/1399467530361551/

**Comment by RicardoJ** [comment]
Hello John,

This issue is because how Wordpress handles and uses all functions regarding to modules and themes. If you want to integrate Mollie within Wordpress, maybe our [Wordpress (WooCommerce) module](https://github.com/mollie/WooCommerce) is something you want.

Ricardo,
Mollie

**Comment by eaglejohn** [comment]
Thanks, but the website is not using WooCommerce. It's just a minimal form (Mollie PHP API) with one field that redirects to iDeal.

**Comment by JohannesSanders** [comment]
This does not seem to be relevant any more. If it is please reopen the ticked and tell us how your payment is created in detail. Based on this I can't make out where your problem lies. You can also email us at info[at]mollie.com.
