### ISSUE TITLE
Integrating old reseller methods into Mollie Connect

### ISSUE THREAD

**Issue by oekeur** [mollie/mollie-api-php#170]
Are there any plans on migrating some more features of the (seemingly) old reseller API?
Specifically the account-create and bankaccount-edit are useful for integrating Mollie into ones own application

**Comment by willemstuursma** [comment]
Hi @oekeur. We have some (not well developed) plans for merging the Reseller and OAuth APIs but unfortunately, they are not very high on our priority list right now.

Rest assured that the Reseller API is fully supported by Mollie. 

If there is anything specific you need, you can drop it here. I'll leave this issue open.

**Comment by willemstuursma** [comment]
Hi @oekeur. We're looking to integrate a Create organization API call in the v2 API. See https://github.com/mollie/api-documentation/pull/211 for what it would look like.

Let us know what you think!

**Comment by oekeur** [comment]
Hi @willemstuursma,

Things seem to be moving seeing the new[ onboarding api](https://github.com/mollie/api-documentation/commit/b32683836f1cc43afea6d18e67c9d47c56412a96).
Since there is an get already available, am I right to assume creating entities will also be part of this API?

**Comment by MollieRick** [comment]
Hi @oekeur, 

We released a _Submit onboarding data_ endpoint, this week. You can check the documentation here: https://docs.mollie.com/reference/v2/onboarding-api/submit-onboarding-data

I expect that the onboarding APIs will be part of the client soon.
