### ISSUE TITLE
Api v1 end of life?

### ISSUE THREAD

**Issue by arendvw** [mollie/mollie-api-php#178]
[After reading the docs for v1 to v2](https://docs.mollie.com/migrating-v1-to-v2), I've not found any information that could lead to a deadline or loss of support for the API v1 (both on the PHP end, and on the server side)

I'm looking for information on documentation of the possible depreciation of API v1
- if it will remain to be maintained / developed for PHP?
- if it will remain operational for the api endpoint?

At this moment the documentation for migration is very nice, but it does not confirm or deny the depreciation of APIv1.

**Comment by willemstuursma** [comment]
The v1 API will be supported for the foreseeable future, at least until July 2023. 

New features will go into the v2 API.  We're recommending all new implementations to be built on top of the v2 API.
