### ISSUE TITLE
Payment amount.value must be set as a string

### ISSUE THREAD

**Issue by pedro-walter** [mollie/mollie-api-php#179]
Hello,

The following codes illustrate the issue:

```php
//This works
$orderAmount = "100.00";
$payment = $this->mollie->payments->create([
  "amount"      => [
    "currency" => "EUR",
    "value" => $orderAmount,
  ],
  "description" => "Order ".$order['id'],
  "redirectUrl" => $callbackUrl,  
]);
```

```php
//This does not work
$orderAmount = 100.00;
$payment = $this->mollie->payments->create([
  "amount"      => [
    "currency" => "EUR",
    "value" => $orderAmount,
  ],
  "description" => "Order ".$order['id'],
  "redirectUrl" => $callbackUrl,  
]);
```

To make it work properly, I must force a string conversion:

```php
//This does work
$orderAmount = 100.00;
$payment = $this->mollie->payments->create([
  "amount"      => [
    "currency" => "EUR",
    "value" => sprintf("%.2f", $orderAmount),
  ],
  "description" => "Order ".$order['id'],
  "redirectUrl" => $callbackUrl,  
]);
```

Thanks for your attention!

**Comment by toonvandeputte** [comment]
Is there any particular reason why you're not using `strval($orderAmount)`?

**Comment by Smitsel** [comment]
Hi Pedro,

We enforce the usage of strings in ``amount.value`` because the number of decimals must be correct. So forcing string conversion is required in your case. 

I've added some comments to the examples explaining it.

**Comment by willemstuursma** [comment]
@toonvandeputte note that `strval` isn't guaranteed to return a string with the correct number of decimals.

You should use `sprintf("%.2F", $amount_as_float)` if you use floats to represent your order amounts.

**Comment by toonvandeputte** [comment]
I'm currently using `number_format( $amount, 2, '.', '' );` in the code I'm migrating over to v2 of the API. Any reason why `sprintf` would be better?

**Comment by pedro-walter** [comment]
Following up on this, I wanna stress out that you should always use sprinf(".2F") (note, uppercase "F"), instead of sprintf(".2f") (lowercase "f"), since that forces the output to use the "." (dot) as a decimal separator. Had an issue since my locale defaults to "," (comma) as a separator.
