### ISSUE TITLE
Webhook POST id always the same for every order

### ISSUE THREAD

**Issue by Thorazine** [mollie/mollie-api-php#184]
I've implemented the PHP api in test mode on my localhost and my webhook is working. I also get payment updates there and am very happy with it, so no problems.

However, the POST id I get from mollie is always the same for every order (tr_EuhW9Wfg4F). I would've guessed that every order would have it's own unique id. I use that id to get the order from my database (in conjunction with an id in the redirectUrl, so the redirectUrl is always unique). 

How can I get a unique (mollie) id for every order?

**Comment by Smitsel** [comment]
The Mollie payment token ``tr_EuhW9Wfg4F`` is unique per payment.
The order is just meta data for yourself.

Could you send us an email at support@mollie.com with your code?
Then its easier for us to assist :)

**Comment by Thorazine** [comment]
Nope, nevermind. Whoopsie, i'm retarded. Thanks!
