### ISSUE TITLE
Issue in make payments api https://api.mollie.com/v2/payments

### ISSUE THREAD

**Issue by saurabhcoder** [mollie/mollie-api-php#185]
I am using below json data for post request for the api -->https://api.mollie.com/v2/payments
Request body->

```json
{
	"amount ": {
		"currency":"EUR",
		"value": "10.00"
	},
	"description ": "My first payment ",
	"redirectUrl ": "https://webshop.example.org/order/112/ ",
	"webhookUrl ": "https://webshop.example.org/payments/webhook/ ",
	"metadata ": {
		"order_id ": "112"
	}
}
```

The response I am getting is 

```json
{
    "status": 422,
    "title": "Unprocessable Entity",
    "detail": "The amount does not contain a currency",
    "field": "amount.currency",
    "_links": {
        "documentation": {
            "href": "https://docs.mollie.com/guides/handling-errors",
            "type": "text/html"
        }
    }
}
```
Is there any mistake done by me in request body data?

**Comment by Smitsel** [comment]
Hi there,

Yes, i can see that you're request body has spaces after the keyword.
So ``"amount "`` should be ``"amount"``.

Notice the space before the last ``"``.

**Comment by shirshir** [comment]
I added some code block markup so that the JSON is easier read.

**Comment by Daanvm** [comment]
I've updated our API to return a clearer error message. It would now return `"The amount is required for payments"`.

**Comment by rakeshislive** [comment]
`mollieClient.payments.create({
                        amount: {
                          value:    result[0].price,
                          currency: 'EUR'
                        },
                        description: 'Booking Charge for the service',
                        redirectUrl: 'http://' + req.hostname +':' + process.env.PORT + '/index/profile',
                        webhookUrl:  'http://www.blacklyst.app/webhook'
                      }, (err, payment) => {`

I am getting an error. 
UnhandledPromiseRejectionWarning: Error: ApiError: The amount contains an invalid value

Can anyone help me?

**Comment by robindirksen1** [comment]
@rakeshislive `result[0].price` needs to be a string like this: `100.09`.

> A string containing the exact amount you want to charge in the given currency. Make sure to send the right amount of decimals and omit the thousands separator. Non-string values are not accepted.

See: https://docs.mollie.com/reference/v2/payments-api/create-payment#parameters
