### ISSUE TITLE
Payment method mistercash should be bancontact

### ISSUE THREAD

**Issue by mathijsvdb** [mollie/mollie-api-php#187]
In the PaymentMethod class, `mistercash` should be updated to `bancontact`.

```
    /**
     * Bancontact, formerly known as Mister Cash.
     *
     * @link https://www.mollie.com/mistercash
     */
    const MISTERCASH = "mistercash";
```

My payment call always returned an error, so i went exploring the API. Seems the `mistercash` id has been updated to `bancontact`

**Comment by ndijkstra** [comment]
Hi! In the latest version we've updated it to bancontact: https://github.com/mollie/mollie-api-php/blob/master/src/Types/PaymentMethod.php

**Comment by holtkamp** [comment]
Can this also be backported for the `v1` branch?

https://github.com/mollie/mollie-api-php/blob/ed1683b244676360d951c7c5beefe02782cc20eb/src/Mollie/API/Object/Method.php#L94

Since *changing* it is probably a breaking change, it might be better to simply add the `BANCONTACT` constant?

**Comment by holtkamp** [comment]
@ndijkstra and @willemstuursma did https://github.com/mollie/mollie-api-php/issues/187#issuecomment-428347741 reach your "radar" ? 😃

**Comment by willemstuursma** [comment]
@holtkamp In v1, you have to use the `mistercash` value to create Bancontact payments. 

You can also retrieve this value from the v1 methods API. 

I don't understand why you want to use `bancontact` for this?

**Comment by holtkamp** [comment]
mmm, well, the company / payment method "Mistercash" has been "Bancontact" for some time now.

Internally we use identifiers for the PaymentMethods as provided by the various PaymentServiceProviders (like Mollie) to populate the requests that are dispatched to their APIs. 

I thought it was kind of awkward to present a PaymentMethod as "Bancontact" to our customers, while using `mistercash` as identifier... But apparently it is not as trivial as I thought? 😄

**Comment by willemstuursma** [comment]
@holtkamp if you have some internal identifiers, you would have mapping from your internal identifier to the PSP's identifier regardless right?

In v2 this has been resolved so you could also upgrade your connection to that.

**Comment by holtkamp** [comment]
Indeed, and I would like these identifiers to make sense...

I expected this would have been simple to backport Bancontact "support" for the `v1` folks out here by simply adding a constant to https://github.com/mollie/mollie-api-php/blob/ed1683b244676360d951c7c5beefe02782cc20eb/src/Mollie/API/Object/Method.php

```php
const BANCONTACT = self::MISTERCASH;
```

nice-to-have, not a biggy though 👍
