### ISSUE TITLE
settlements->chargebacks() doesn't work - it uses refunds instead of chargebacks

### ISSUE THREAD

**Issue by synio-wesley** [mollie/mollie-api-php#194]
Similar to #192 

`foreach ($result->_embedded->refunds as $dataResult)`
should be
`foreach ($result->_embedded->chargebacks as $dataResult)`

in `src/Resources/Settlement.php`

**Comment by Smitsel** [comment]
Thanks Wesley, 

Fixed them in https://github.com/mollie/mollie-api-php/commit/95add45d42423162f82ee6eb62f0004c2c184f37
