### ISSUE TITLE
Settlement::payments() retrieve only 50 payments

### ISSUE THREAD

**Issue by synio-wesley** [mollie/mollie-api-php#195]
According to docs, Settlement::payments() should retrieve all payments, but it only retrieves max. 50 - How can I retrieve all of them using this function?

**Comment by synio-wesley** [comment]
If #196 is fixed I will be able to retrieve all the next batches

**Comment by Smitsel** [comment]
Fixed it in https://github.com/mollie/mollie-api-php/commit/95add45d42423162f82ee6eb62f0004c2c184f37

Thanks!
