### ISSUE TITLE
CursorCollection::next() and prev() only work once because count/links are not reset

### ISSUE THREAD

**Issue by synio-wesley** [mollie/mollie-api-php#196]
Related to #195 

In `CursorCollection::next()` and `CursorCollection::prev()` these lines:
`$collection = new static($this->client, $this->count, $this->_links);`
should be:
`$collection = new static($this->client, $result->count, $result->_links);`
so that the count and links are reset for the next batch.

Otherwise, there will be an endless loop when you want to keep calling next() on the result set to fetch all results.

**Comment by Smitsel** [comment]
Thanks for finding the bugs @synio-wesley 

Fixed them:
https://github.com/mollie/mollie-api-php/commit/95add45d42423162f82ee6eb62f0004c2c184f37
