### ISSUE TITLE
composer.json version number

### ISSUE THREAD

**Issue by mathiasselleslach** [mollie/mollie-api-php#20]
Dear @RickWong ,

As discussed earlier, I would like to request the revert of this commit on composer.json 
https://github.com/mollie/mollie-api-php/commit/bb72cc856e3546c864c7db1355f27d141d989990#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
That removes the version number.

The Drupal Libraries API depends on it to detect the version of the Mollie API.

I have also created an issue on drupal.org for reference that can be found here:
https://www.drupal.org/node/2684741

Thanks in advance

Mathias

**Comment by RicardoJ** [comment]
Hello @mathiasselleslach,

I've added this in release v1.4.1 both in the release tag as in the master branch (of course). You can find the new release [here](https://github.com/mollie/mollie-api-php/releases/tag/v1.4.1) on GitHub or on [Packagist](https://packagist.org/packages/mollie/mollie-api-php#1.4.1). 

Thank you for your suggestion and have a nice day.

Ricardo,
Mollie.
