### ISSUE TITLE
ErrorException: Undefined index: id in mollie webhook

### ISSUE THREAD

**Issue by jimkaler** [mollie/mollie-api-php#202]
Hi, I am using laravel framework, I am getting error ErrorException: Undefined index: id while retrieving payment. I am using testing mode. here is the code

 $mollie = new \Mollie_API_Client();
        $mollie->setApiKey("APKIKEY");

  try
        {
            $payment = $mollie->payments->get($_POST['id']);
            $order_id = $payment->metadata->order_id;
            // File::put(public_path('/aaaaaaaa.txt'),);
            //Update Database Actest_QunbwFVUMEsGsbCSUj3x5PvsRNEvRdcording Payment status
            if ($payment->isPaid())
                {       
                        $report = Report::where('order_id',$order_id)->first();
                        $report["status"] = 'Paid';
                        $report->save();
                        //Stock Getting Update after Payment has been done.
                        $CoinValue = $report->btc_value;
                        $stock = AvalableStock::where('type',$report->coins_type)->first();
                        $UpdateStock = $stock->coins-$CoinValue;
                        $stock['coins'] = $UpdateStock;
                        $stock->save();

                }
 else
                {
                    
                        $report = Report::where('order_id',$order_id)->first();
                        $report["status"] = 'Pending';
                        // $report["account_number"] = $payment->details->consumerAccount;
                        $report->save();
                }

            // File::put(public_path('/aa1.txt'),$order_id);   

        }
        catch(\Exception $e)
        {test_QunbwFVUMEsGsbCSUj3x5PvsRNEvRd
            $data = $e;
            File::put(public_path('/aaaaaaaa.txt'),$data);
        }
               
Thanks in advance.

**Comment by Smitsel** [comment]
Hi @jimkaler,

Are u running the script directly?
Because this is probably because your $_POST["id"] is undefined.

The webhook is called by our server with an ``id`` in the POST.
So to test your script you should POST an id to it.

See: https://docs.mollie.com/guides/webhooks

**Comment by jimkaler** [comment]
@Smitsel i am not running it directly, I am calling it after payment. It was running fine but suddenly it stopped working. i have changed API key, is it causing problem?

**Comment by flowroma** [comment]
Jim, I had the same issue. You need to use the live API key and for testing purposes use a hardcoded ID like this:

` $payment = $mollie->payments->get('tr_WFF8qARVHQ');`

**Comment by jimkaler** [comment]
may i use that same id? or from where will i get that id dude?

**Comment by flowroma** [comment]
The ID is given to you by Mollie once you make payment requests in live mode. Testing mode won't give you that.

**Comment by jimkaler** [comment]
Does it means we can't test it on testing mode?

**Comment by flowroma** [comment]
You can, but you need to use a hardcoded ID

**Comment by Smitsel** [comment]
Hi @jimkaler can you email us at <techsupport@mollie.com> with an example of your code?

Closing the issue for now.
