### ISSUE TITLE
[Documentation] Certain links in PHPDoc to API Documentation broke for version 1

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#203]
## Specifications

  - API Version: 1

## Describe the issue
In some cases links to the API Documentation are used as PHPDoc, for example:

https://github.com/mollie/mollie-api-php/blob/33e09a0be5edfcf5b7bf8100e253666de514b4cf/src/Mollie/API/Object/Settlement.php#L63

This points to 

https://www.mollie.com/en/docs/reference/settlements/get#period-object

which gets redirected to using a HTTP/301 "moved permanently" header to:

https://docs.mollie.com/reference/v2/settlements-api/get-settlement

While this should probably be:

https://docs.mollie.com/reference/v1/settlements-api/get-settlement#response

Note the internal link `#period-object` breaks, might be nice of such deeplinking still works.

This is not a big issue, but I think it is good to know.

It seems for 
https://github.com/mollie/mollie-api-php/blob/v1-develop/src/Mollie/API/Object/Profile.php#L71 the redirection works properly
https://www.mollie.com/en/docs/reference/profiles/get

**Comment by Smitsel** [comment]
Nice find again! I've updated all the links to go to their respective page in the new v1 docs.

About the anchor linking to period-object, i've opened an issue in our documentation for adding it to the common data types. So we can link it again.

https://github.com/mollie/api-documentation/issues/62
