### ISSUE TITLE
Missing properties in v1: Settlement.createdDatetime, Settlement.status

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#204]
## Specifications

  - API Version: 1

## Describe the issue
It seems the [`Mollie_API_Object_Settlement`](https://github.com/mollie/mollie-api-php/blob/33e09a0be5edfcf5b7bf8100e253666de514b4cf/src/Mollie/API/Object/Settlement.php) class in v1 misses the following properties:

- createdDatetime
- status

The reason why this is useful:

1. The returned objects as returned by `Mollie_API_Resource_Settlements::all()` are of class `stdClass` and **do** have these properties populated
2. This general class can be used to populate a Mollie_API_Object_Settlement for actual use in user land code (for example: to prepare for v2)
3. It would be nice if IDEs like PHPStorm would recognise all available properties in order to use autocompletion, etc

Here one can see the result in PHPStorm:

<img width="543" alt="screen shot 2018-06-18 at 17 33 17" src="https://user-images.githubusercontent.com/776405/41546383-cf83ce9a-731d-11e8-8bce-9e756e426fc0.png">

**Comment by Smitsel** [comment]
Thanks for spotting this, i've just added them to the ``v1-develop`` branch.
