### ISSUE TITLE
Invoices API missing in v1 while it is documented?

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#206]
## Specifications

  - API Version: 1

## Describe the issue
The API Documentation for `v1` describes an [Invoices API](https://docs.mollie.com/reference/v1/invoices-api/)

However when looking at the `v1` [API client, no Invoices endpoint / resource seems to be implemented](https://github.com/mollie/mollie-api-php/tree/v1-develop/src/Mollie/API/Resource)...

On the master branch this **is** available: https://github.com/mollie/mollie-api-php/blob/4cd551920a6fad339e09fdfdbbe13eff4af5f679/src/Resources/Invoice.php

 Am I missing something? The [migration guide](https://docs.mollie.com/migrating-v1-to-v2#changes-in-the-invoice-api) kind of suggests that the Invoice API was/should also be part of `v1`...

**Comment by willemstuursma** [comment]
Hi @holtkamp. You are right. It's part of the v1 API, however the objects were never implemented in the PHP API client.

You can create a PR or use the magic __call() method.

**Comment by willemstuursma** [comment]
This is related to https://github.com/mollie/laravel-mollie/pull/35.

**Comment by holtkamp** [comment]
Aah, ok, thanks for the swift response, I will have a look.
