### ISSUE TITLE
API results cannot be serialized

### ISSUE THREAD

**Issue by willemstuursma** [mollie/mollie-api-php#212]
## Specifications

  - API Version:  v2

## Describe the issue

Results retrieved from the API cannot be serialized, because the Guzzle client is one of the properties. 

Serialization could be used to enable caching of the methods, for example.

It was reported by @davdebcom.

**Comment by willemstuursma** [comment]
```php
    /**
     * Serialization can be used for caching. Of course doing so can be dangerous but some like to live dangerously.
     *
     * \serialize() should be called on the collections or object you want to cache.
     *
     * We don't need any property that can be set by the constructor, only properties that are set by setters.
     *
     * @return string[]
     */
    public function __sleep()
    {
        return ["apiEndpoint", "apiKey", "oauthAccess"];
    }

    /**
     * When unserializing a collection or a resource, this class should restore itself.
     *
     * Note that if you use a custom GuzzleClient, this client is lost. You can't re set the Client, so you should
     * probably not use this feature.  
     */
    public function __wakeup()
    {
        $this->__construct();
    }
```

**Comment by willemstuursma** [comment]
Yes, we will implement this but we need to create some documentation and tests to be sure that it works correctly.

**Comment by willemstuursma** [comment]
I'm not sure @davdebcom. 

Serializing will also cause the API key to end up in strange places. 

Does it work for you if the API key is not restored after unserializing?

**Comment by davdebcom** [comment]
@willemstuursma Removed `"apiKey", "oauthAccess", seems to work, and I don't need the API key in my case, so that's okay.

**Comment by davdebcom** [comment]
Just curious, where did you find this:
https://github.com/mollie/mollie-api-php/issues/212#issuecomment-399952300

**Comment by willemstuursma** [comment]
It's my job to know these things!

**Comment by davdebcom** [comment]
Haha, I guess so. I thought maybe there was an interesting blog post about it, but I I can live with that explanation as well.
