### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/mollie-api-php#217]
## Specifications

  - API Version: 2

## Describe the issue
While upgrading the [laravel-mollie client](https://github.com/mollie/laravel-mollie), I noticed the mollie-api-php client code examples are no longer available at the Mollie website.

Only the curl calls are now covered in the docs.

Are there any plans for launching easily digestible docs for the php client? The code examples at `/examples` help, but are not extensive.

Let me know if I can help with this.

**Comment by willemstuursma** [comment]
We could use some help adding them to our [api documentation](https://github.com/mollie/api-documentation) project. You could add some as a PR here and then we'll pass it to our design team to add the dropdowns and whatnot needed.

**Comment by sandervanhooft** [comment]
Ok. Let me focus on finalizing laravel-mollie v2 first. I'll also send a note to Tomas.
