### ISSUE TITLE
Feature request: hasActiveMandate helper method

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/mollie-api-php#218]
## Specifications

  - API Version: 1 and/or 2

## Describe the issue
Manually implementing the check whether a customer has an active mandate is a bit cumbersome. As far as I know there is no helper method for this.

How about an `$customer->hasActiveMandate()` helper?

**Comment by willemstuursma** [comment]
@Smitsel can you weight this?

**Comment by sandervanhooft** [comment]
Love it! 🥇
