### ISSUE TITLE
$mollie object voided after $mollie->payments->get

### ISSUE THREAD

**Issue by JannesKlaas** [mollie/mollie-api-php#22]
Hi,
I use this code while verifying my payments, (API key an payment id Xed out):

`require_once 'Mollie/API/Autoloader.php';

$mollie = new Mollie_API_Client;
$mollie->setApiKey('test_XXXXXXXXXXXXXX');
$payment_id = 'some payment id';
$payment    = $mollie->payments->get($payment_id);
$order_id = $payment->metadata->order_id;`

I noticed that the payment object returned is empty. So the payment can not be verified.
Furthermore, the mollie object is also voided after `$payment    = $mollie->payments->get($payment_id);` is called.

If I try: 

`require_once 'Mollie/API/Autoloader.php';

$mollie = new Mollie_API_Client;
$mollie->setApiKey('test_XXXXXXXXXXXXXX');
print_r($mollie);
$payment_id = 'some payment id';
$payment    = $mollie->payments->get($payment_id);
print_r($mollie);
$order_id = $payment->metadata->order_id;`

the first time the object is printed, the second time nothing is given out.

I re installed the module already with no success.
Thanks in advance for your help,
Jannes

**Comment by RickWong** [comment]
Hi Jannes. Are you sure the script even reaches the code after `->get(...)`? Because if that call fails, an exception is thrown. Try catching that exception to see what's wrong.

**Comment by JannesKlaas** [comment]
Hi Rick,
catching the exception revealed that the payment id i had used to test the verification had become invalid. A new id worked perfectly.
Thank you very much for your help,
Jannes

**Comment by RicardoJ** [comment]
Glad to hear it is solved. Have a nice evening.
