### ISSUE TITLE
No permissions() shorthand method

### ISSUE THREAD

**Issue by willemstuursma** [mollie/mollie-api-php#220]
## Specifications

  - API Version:  v2

## Describe the issue

We've seem to misplaced the `permissions()` shorthand method for getting the permissions in v2.

**Comment by sandervanhooft** [comment]
@willemstuursma It seems like the permission endpoint has not been implemented yet in this client.

**Comment by sandervanhooft** [comment]
```
Searching 64 files in "src/" for "permission"

0 matches
```

**Comment by willemstuursma** [comment]
@sandervanhooft feel free to add it to this client.

**Comment by sandervanhooft** [comment]
@willemstuursma I'll discuss priorities with Mike and Nick :).

**Comment by sandervanhooft** [comment]
The same for Organizations: not implemented yet.

**Comment by sandervanhooft** [comment]
#273

**Comment by sandervanhooft** [comment]
#274

**Comment by sandervanhooft** [comment]
@willemstuursma I think this issue is now solved and can be closed.
