### ISSUE TITLE
Ship CA files with v2 module

### ISSUE THREAD

**Issue by willemstuursma** [mollie/mollie-api-php#224]
## Specifications

  - API Version: v2

## Describe the issue

Various reports have come in centering around cURL error 60, the certificates cannot be verified. 

Given the wide landscape of servers our client runs on, we might need to ship a `cacert.pem` file just like in v1.

**Comment by it-can** [comment]
Maybe this is an option?

https://github.com/composer/ca-bundle

```
$client = new \GuzzleHttp\Client([
    \GuzzleHttp\RequestOptions::VERIFY => \Composer\CaBundle\CaBundle::getSystemCaRootBundlePath()
]);
```
