### ISSUE TITLE
Can I update subscription amount?

### ISSUE THREAD

**Issue by thobroni** [mollie/mollie-api-php#226]
## Specifications

  - API Version: 2

## Describe the issue
I am trying to create subscription proccess, and I want to give a discount for first month, how to do that ?, can I update subscription amount?. Thanks

**Comment by willemstuursma** [comment]
We'll be releasing an Update Subscription endpoint soon which will allow you to change the subscription amount. Expect it within 14 days.

**Comment by willemstuursma** [comment]
Hi @thobroni We've added an Update Subscription endpoint.

**Comment by thobroni** [comment]
Great. thanks
