### ISSUE TITLE
Geen payment-id in the $_POST naar de webhook

### ISSUE THREAD

**Issue by jpdamen** [mollie/mollie-api-php#23]
Onze webhook is publiek toegankelijk en gevalideerd in de Mollie-beheertool.
In de accesslog zie ik dat er een POST wordt gemaakt naar de webhook.

```
77.245.85.230 - - [19/Apr/2016:21:44:07 +0200] "POST /shop/payment/status/ HTTP/1.1" 200 3676 "-" "Mollie.nl HTTP client/1.0"
```

De $_POST-array is echter leeg. Ik ben inmiddels aan het testen geslagen met de live-key omdat de test-api alleen een dummy get-parameter meestuurt. 
Maar in het geval van de live_api (met echte betalingen) zou er zeker een payment-id meegestuurd moeten worden toch?

Enig idee wat hier aan de hand zou kunnen zijn?

**Comment by RickWong** [comment]
Het kan zijn dat op de Webhook URL een redirect wordt gedaan: de URL verandert en de POST-data verdwijnt.

Het gaat meestal om een van de volgende situaties:

* een HTTPS- naar HTTP-redirect web-adres, of vice versa;
* een domein- of subdomein-redirect;
* een website-taal-redirect.

Controleer of dit bij jouw Webhook URL gebeurt simpelweg door hem in de webbrowser te bezoeken. Let daarbij goed op hoe de URL/het web-adres verandert.
