### ISSUE TITLE
Customer payments not working in testmode oAuth

### ISSUE THREAD

**Issue by ndijkstra** [mollie/mollie-api-php#232]
## Specifications

  - API Version: v2
  - Client version: 2.0.7

## Describe the issue

Retrieving a customer in testmode is working fine:
`$mollie->customers->get('cst_xxxxx', ['testmode' => 'true']);`

Only listing the payments, mandates or subscriptions of the customer isn't working in testmode. I'm getting the error: "Error executing API call (404: Not Found): Customer cst_xxxxx exists, but the wrong mode is used. Try switching live / test API keys."

I'm using this code:

```
$customer = $mollie->customers->get('cst_xxxxx', ['testmode' => 'true']);

$payments = $customer->payments();
$subscriptions = $customer->subscriptions();
$mandates = $customer->mandates();
```

**Comment by Smitsel** [comment]
Thanks @ndijkstra,

I've created a PR with the fix.

**Comment by RyonMB** [comment]
Hello, I am still have the same issue, do I need to change something myself?

`$customer = $mollie->customers->get($customerid->customer_id, ['testmode' => 'true']);
        $betalingen = $customer->payments();`

This is the code I am using

**Comment by sandervanhooft** [comment]
Hi @RyonMB ,

Can you open a new ticket for this?

**Comment by RyonMB** [comment]
Yes, sure
