### ISSUE TITLE
$payment->getRefund(...) missing

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/mollie-api-php#235]
## Specifications

  - API Version: v2.0
  - Mollie client: v2.0.8

## Describe the issue
Working on the API docs, discovered there's no `$client->refunds->get('refund_id_here')` method. Makes it hard to retrieve or cancel a single refund.

Not worked on this package yet, let me know if you'd like me to create a PR.

**Comment by willemstuursma** [comment]
If I am not mistaken, the refund has to be "get" from the Payment. It cannot be retrieved from `v2/refunds/re_xxxxx`. See the `self` URL in the `_links` property. 

I guess for canceling a refund, you would usually have the paymentId on hand right?

Do you have a use case?

**Comment by sandervanhooft** [comment]
Agreed. Retrieving the refund via the payment is fine. I was a bit confused because `$client->refunds` exists (`RefundEndpoint`).

There's however no way (afaik) to retrieve a single refund (by refund-id). Right now you need to manually filter the results from `$payment->refunds()`.

Perhaps add a `$payment->getRefund(...)` helper?

**Comment by sandervanhooft** [comment]
(There's a similar `getMandate('some_id')` helper method on the `Customer` resource.)

**Comment by Smitsel** [comment]
Its allright if you make a PR for it :)

**Comment by sandervanhooft** [comment]
Ok, to be sure, that would require the following to be implemented:

```
RefundEndpoint:
tests/Mollie/API/Endpoints/RefundEndpointTest : testGetForWorks
src/Endpoints/RefundEndpoint : getFor(Payment $payment, $refundId, array $parameters = [])

PaymentResource:
tests/Mollie/API/Resources/Payment : testGetRefundWorks
src/Resources/Payment : getRefund($refundId, array $parameters = [])
```

**Comment by sandervanhooft** [comment]
Will work on this later this week.

Also noted that there's a minor docbloc issue [in the Payment resource](https://github.com/mollie/mollie-api-php/blob/8acb00b90a5a7a2ecfcd11d4608444150d89a220/src/Endpoints/PaymentEndpoint.php#L125), referencing `$filters`, which should be `$data`.

Will take care of this as well.

**Comment by sandervanhooft** [comment]
Hi @Smitsel ,

Working on it...

Shouldn't RefundEndpoint have `payments_refunds` as the resource path?

```
class RefundEndpoint extends EndpointAbstract
{
    protected $resourcePath = "refunds"; // should be "payments_refunds"?
```

```
class MandateEndpoint extends EndpointAbstract
{
    protected $resourcePath = "customers_mandates"; // seems right
```

**Comment by sandervanhooft** [comment]
While implementing `$client->refunds->getFor($payment, $refundId, $params)` I now get these test results:

```php
1) Tests\Mollie\Api\Endpoints\RefundEndpointTest::testGetRefundOnPaymentResource
URI path must be identical
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/v2/payments/tr_44aKxzEbr8/refunds/re_PsAvxvLsnm'
+'/v2/refunds/re_PsAvxvLsnm'
```

RefundEndpoint method
```php
    /**
     * @param Payment $payment
     * @param string $refundId
     * @param array $parameters
     *
     * @return Refund
     */
    public function getFor(Payment $payment, $refundId, array $parameters = [])
    {
        $this->parentId = $payment->id;

        return parent::rest_read($refundId, $parameters);
    }
```

**Comment by sandervanhooft** [comment]
I'll prepare a PR and leave the nested resource path commented out for now.

**Comment by Smitsel** [comment]
Pull request has been merged! Thanks @sandervanhooft
