### ISSUE TITLE
Oauth / Connect token management methods and examples missing

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/mollie-api-php#238]
## Specifications

  - API Version: 2
  - Package version: 2.0.10

## Describe the issue
(I came across this issue while updating the official Mollie docs.)

Examples for Oauth / Connect token management are missing.

Only `setAccessToken(...)` is currently mentioned ([here](https://github.com/mollie/mollie-api-php/blob/6567ed19aa657c58ae50b2185918d4cff512d097/examples/initialize_with_oauth.php#L18)). 

How to perform the initial and refresh requests is not described.

It seems to me that convenience methods are missing on the client class as well, so I'm not sure how to document this / what's the best approach here.

Perhaps the Laravel-Mollie implementation can serve as inspiration ([link](https://github.com/mollie/laravel-mollie/blob/ac170096bb3784230cf44a892f94d27b0dc3b261/src/MollieConnectProvider.php)).

**Comment by willemstuursma** [comment]
OAuth should be handled using league/oauth for which we created a [provider](https://github.com/mollie/oauth2-mollie-php).

Does that help @sandervanhooft ?

**Comment by sandervanhooft** [comment]
I think that's the best way indeed.

Perhaps document this in the readme?

**Comment by willemstuursma** [comment]
Yes, that would be great. Could you open a PR?

**Comment by sandervanhooft** [comment]
Any suggestions for the official docs on this topic?

**Comment by sandervanhooft** [comment]
Closing here. Continue [here](https://github.com/mollie/api-documentation/issues/124#issuecomment-409650012).
