### ISSUE TITLE
How to get all subscriptions for a customer?

### ISSUE THREAD

**Issue by Lars-** [mollie/mollie-api-php#240]
## Specifications

  - API Version: latest

## Describe the issue

When I use $customer->subscriptions() I get a nice SubscriptionCollection and I see the storage element in it, which holds the information I'm looking for. But it's private...

How do I get all subscriptions for a customer?

**Comment by Smitsel** [comment]
Hi @Lars- 

Our collection extend from PHP's ArrayObject: http://php.net/manual/en/class.arrayobject.php
This means that you can iterate it like you can see in our example:
https://github.com/mollie/mollie-api-php/blob/master/examples/13-customer-payments-history.php

Hope that helps!
