### ISSUE TITLE
[Beta]Order and Shipment integration

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/mollie-api-php#247]
## Specifications

  - API Version: v2

## Describe the issue
I am preparing the Order and Shipment integrations [in this fork/branch](
https://github.com/sandervanhooft/mollie-api-php/tree/klarna).

Any discussion on the development can take place here in this issue.

PR is here: #252.

**Endpoints:**
- [x] `OrderEndpoint` for `/orders/*`:
  - [x] `create`
  - [x] `get`
  - [x] `list`
  - [x] `cancel`
- [x] `OrderLineEndpoint` for `/orders/*/lines/*`
  - [x] `cancelFor($orderId)`
- [x] `OrderRefundEndpoint` for `/orders/*/refunds/*`
  - [x] `create`
  - [x] `list`
- [x] `ShipmentEndpoint` for `orders/*/shipments/*`
  - [x] `createFor`
  - [x] `getFor`
  - [x] `listFor`

**Resources:**
- [x] `Order`
  - [x] `isStatusX()`
  - [x] `lines()`
  - [x] `shipments()`
  - [x] `getShipment()`
  - [x] `createShipment()`
  - [x] `ship()`
  - [x] `isCancelable()`
  - [x] `cancelLine()`
  - [x] `refunds()`
  - [x] `refund(...)`
- [x] `OrderCollection`
- [x] `OrderLine`
  - [x] `isStatusX()`
  - [x] `isTypeX()`
  - [x] `cancel()`
  - [x] `isCancelable()`
- [x] `OrderLineCollection`
- [x] `Shipment`
  - [x] `lines()`
  - [x] `order()`
- [x] `ShipmentCollection`

**Types:**
- [x] `OrderStatus`:
  - [x] `created`
  - [x] `paid`
  - [x] `authorized`
  - [x] `canceled`
  - [x] `refunded`
  - [x] `shipping`
  - [x] `completed`
  - [x] `void` (dropped)
  - [x] `expired`
- [x] `OrderLineStatus`:
  - [x] `created`
  - [x] `authorized`
  - [x] `paid`
  - [x] `canceled`
  - [x] `refunded`
  - [x] `shipped`
  - [x] `void`
- [x] `OrderLineType`:
  - [x] `physical`
  - [x] `discount`
  - [x] `digital`
  - [x] `shipping_fee`
  - [x] `store_credit`
  - [x] `gift_card`
  - [x] `surcharge`

**Documentation:**
- [x] Update examples
  - [x] `Order`
    - [x] `26-new-order`
    - [x] `27-handle-order-status-change`
    - [x] `28-cancel-order`
    - [x] `29-list-orders`
    - [x] `30-cancel-order-line`
  - [x] `Shipment`
    - [x] `31-ship-order-completely`
    - [x] `32-ship-order-partially`
    - [x] `33-get-order-shipment`
    - [x] `34-list-order-shipments`
- [x] Update official docs to include php examples (when php client released)
  - [x] `Order`
    - [x] `create`
    - [x] `get`
    - [x] `cancel`
    - [x] `list`
    - [x] `cancel line`
    - [x] `create refund`
    - [x] `list refunds`
  - [x] `Shipment`
    - [x] `create`
    - [x] `get`
    - [x] `list`

**Comment by sandervanhooft** [comment]
The response for `OrderEndpoint.get/create/list` includes order lines (`lines`).

@ndijkstra Should this be an `OrderLineCollection` resource?

It would be a first for this client to include a nested resource(collection) in a response. It would probably require overriding the `rest_create` method.

**Comment by ndijkstra** [comment]
The order lines are in the order response. The order line endpoint is only for canceling an order line

**Comment by sandervanhooft** [comment]
Ok, so no `OrderLineCollection` is necessary on the `Order` resource?

I'll update the plan above to only include the `cancel` method on `OrderLine`.

**Comment by ndijkstra** [comment]
I think that is correct. @Smitsel Can you check if this is ok?

**Comment by Smitsel** [comment]
I think it is, take for example the IssuerCollection.
These are an include on the methods api. But its rather useful to make them value objects.

This way we can iterate the OrderLineCollection and create cool helper functions like:`$orderline->cancel()`. 

So please do add them :)

**Comment by Smitsel** [comment]
I can also see value for people implementing this library and typehint them for example.

**Comment by sandervanhooft** [comment]
Thanks @Smitsel ! I overlooked the IssuerCollection on the methods api. I'll look into that one for inspiration.

**Comment by sandervanhooft** [comment]
By the way, why are all properties defined _explicitly_ on the resource classes? The tests are passing without. Is this for autocompletion?

**Comment by Smitsel** [comment]
Yes it is.

**Comment by sandervanhooft** [comment]
Are there any other relations I should be aware of, like to a `customer` entity?

I.e. the word `customer` is used a lot in the order docs, but there seems to be no relationship defined.

**Comment by sandervanhooft** [comment]
I'm assuming there's going to be a Order cancel (delete) api endpoint, right?

I.e. 
```bash
curl -X DELETE https://api.mollie.com/v2/orders/ord_kEn1PlbGa \
       -H "Authorization: Bearer test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM"
```

**Comment by ndijkstra** [comment]
Correct. Docs coming soon 😇

**Comment by sandervanhooft** [comment]
OrderEndpoint ready (see backlog). Had to use some response fixtures and assertion helpers to keep the file length in check. Reduced it from 1600+ lines to less than 600. Pfew 😓

**Comment by willemstuursma** [comment]
> Had to use some response fixtures and assertion helpers to keep the test file length in check.

Yes, it is very important to remember that tests are software too, and they can massively benefit from abstractions too.

**Comment by holtkamp** [comment]
@sandervanhooft just noted the incorrect casing of `Stdclass`, it should be `stdClass`

https://github.com/sandervanhooft/mollie-api-php/blob/02bc1988b91ef66cc28d6ada659f4fe10aa8c211/tests/Mollie/API/Endpoints/OrderEndpointTest.php#L335

**Comment by sandervanhooft** [comment]
Thanks @holtkamp!
Interestingly though, the tests pass... Nevertheless, I'll convert `StdClass` into `stdClass` as suggested.

**Comment by willemstuursma** [comment]
Class names are case-insensitive in PHP @sandervanhooft, only the Composer autoloaders (PSR-0, PSR-4) are.

**Comment by sandervanhooft** [comment]
Working on the `OrderResource` statuses and status methods now.

Can someone with Order API domain knowledge check whether this test ([link](https://github.com/sandervanhooft/mollie-api-php/blob/a191c90a8040ad182c93d44247e41a92347b3ff9/tests/Mollie/API/Resources/OrderTest.php)) is ok? If so I can continue with implementation.

(The docs are not ready for this yet, only stating "See Order status changes for details on the orders’ statuses.", but no link is provided / page is not available yet.)

**Comment by sandervanhooft** [comment]
> Class names are case-insensitive in PHP @sandervanhooft, only the Composer autoloaders (PSR-0, PSR-4) are.
Good to know 😄

**Comment by Smitsel** [comment]
Hi Sander, the status fields are as described in the docs.
So your status methods are correct.

What we ment with the "order status changes details" is the transitions between statuses.
We will add a guide for this and update accordingly.

**Comment by sandervanhooft** [comment]
Ok @Smitsel ! So I'm going to assume there's no additional logic to implement than (pseudo):

```php
public function isSomeStatus()
{
    return $this->status === ORDER_STATUS::SOME_STATUS;
}
```

**Comment by sandervanhooft** [comment]
> Take a look at the cancel order endpoint docs and you will understand why we want such a guide ;)

Indeed I do 😆 

Seems to me that there should be a `isCancelable` method on the `OrderLine` resource as well.

**Comment by sandervanhooft** [comment]
Perhaps this would require an additional `isCancelable` field in the Order API response?
I noticed it on some other resources.

**Comment by sandervanhooft** [comment]
Ok, I'm mixing things up here. I think we need this `isCancelable` method both on the Order and the OrderLine.

I can probably implement the logic client side, but I think it's better to include a `isCancelable` field on both the Order and the OrderLine responses, to keep the logic where it belongs - server side.

**Comment by sandervanhooft** [comment]
Like with the payment response, it has a `isCancelable` field.

**Comment by sandervanhooft** [comment]
@Smitsel Minor doc issue: the id is missing on the Order line details. ([Link](url
https://docs.mollie.com/reference/v2/orders-api/create-order#order-line-details))

**Comment by sandervanhooft** [comment]
As you can see [here](https://github.com/mollie/mollie-api-php/issues/247#issue-348664390): nearly done with the implementation!

I'd like to manually test this against the private beta api when it's available.

**Comment by sandervanhooft** [comment]
@ndijkstra @Smitsel @willemstuursma 

Next steps:
- review WIP PR (don't merge yet) (Mollie )
- write examples (Sander)
- try examples as soon as API is ready (Sander)
- all works? Merge PR & release (Mollie)
- (update Laravel client (Sander))

**Comment by sandervanhooft** [comment]
I just read up on the `Order` docs. It seems the `void` status is dropped, and the `expired` status is new.

Is that correct?

**Comment by willemstuursma** [comment]
@sandervanhooft yes we are indeed re-considering some of the statuses

**Comment by sandervanhooft** [comment]
@willemstuursma Thanks. So it's not final yet? In that case I'll leave it alone for now.

**Comment by sandervanhooft** [comment]
Added the examples.

**Comment by sandervanhooft** [comment]
@ndijkstra @Smitsel @willemstuursma 

Similar to the `isCancelable` field, I think there should be an `isRefundable` field on the `Order` response. What do you think?

**Comment by willemstuursma** [comment]
We'll create a field for the refundable amount probably.

**Comment by sandervanhooft** [comment]
@willemstuursma Then an `isRefundable()` helper would be nice

**Comment by sandervanhooft** [comment]
@Smitsel When you review this, be sure to keep an eye out for OAuth compatibility. I've not explicitly tested this.

**Comment by willemstuursma** [comment]
@sandervanhooft we want to merge this into a branch and create a pre-release, is that OK for you?
