### ISSUE TITLE
Feature request: Subscription metadata

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/mollie-api-php#257]
## Specifications

  - API Version: 2

## Describe the issue
For subscription handling in Laravel Cashier, I'd like to store `metadata` on the subscription. Is it possible to add this field?

**Comment by sandervanhooft** [comment]
The specific use case here is that I'd like to support Cashier's subscription quantity support.

When updating the quantity, I'd like to store the `quantity` as `metadata`, and update the amount value accordingly.

There are probably many other use cases for subscription metadata.

**Comment by ndijkstra** [comment]
Thanks @sandervanhooft, I will create an issue for that on our backlog

**Comment by sandervanhooft** [comment]
Can I work around this by switching to recurring payments?

**Comment by sandervanhooft** [comment]
Unfortunately triggering payments periodically from the application side is not a viable option using Cashier.

**Comment by MollieRick** [comment]
Hi @sandervanhooft, it is now possible to add `metadata` to subscriptions. Please see the [documentation](https://docs.mollie.com/reference/v2/subscriptions-api/get-subscription) for more info :-)
