### ISSUE TITLE
Error executing API call (rate-limit): Your request has been rate limited (please wait 55s)

### ISSUE THREAD

**Issue by eduardo71vg** [mollie/mollie-api-php#266]
## Specifications
  - API Version: v1
  - PHP CLIENT_VERSION = "1.6.0"

## Describe the issue

I am receiving the following API error while trying to execute a batch of payments for the same API KEY:

Error executing API call (rate-limit): Your request has been rate limited (please wait 55s)

I would like to know two things:

1. The rate limit for my account 
2. Does this rate limit is linked to the API key that I used to perform the payment or it is linked to the IP(or any other identifier) of the consumer/client?

Regards

...

**Comment by willemstuursma** [comment]
The rate limit is linked to your account. 

You can reach out to our support department to retrieve your current limit and request a higher limit.

Note that any paid payments will not count towards your limit.

**Comment by eduardo71vg** [comment]
Hello @willemstuursma thanks for your prompt response, what about the second question? Thanks

**Comment by eduardo71vg** [comment]
@willemstuursma thanks for your help
