### ISSUE TITLE
Support for Settlement subresources

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/mollie-api-php#276]
## Specifications

  - API Version: 2

## Describe the issue
While working on [the documentation](https://github.com/mollie/api-documentation/issues/124), I noticed this client does not support Settlement subresources yet.

<img width="249" alt="screenshot" src="https://user-images.githubusercontent.com/7265703/45696146-33cc8d00-bb63-11e8-81f2-4d1b39dada75.png">

Should these be added? Let me know if I can help.

**Comment by willemstuursma** [comment]
We can add them once we release personal access tokens, which are due soon.

**Comment by sandervanhooft** [comment]
Ok, 'personal access tokens` sounds like interesting stuff is coming! Any impact on the Laravel client as well?

**Comment by willemstuursma** [comment]
We'll create some documentation soon and then you can investigate impact on the clients. The tokens will allow you to access OAuth resources without creating an app.

**Comment by sandervanhooft** [comment]
Closing this for now.
