### ISSUE TITLE
Issues when user cancels payment

### ISSUE THREAD

**Issue by RamarioDepass** [mollie/mollie-api-php#277]
I'm using Mollie Checkout. When a user cancels a payment on the checkout page they are redirected to the success redirect url. How do I send the user to a cancel url? I'm not very familiar with webhooks and my attempts to fix this have failed. Is there a simple cancel url feature?

**Comment by zzplab** [comment]
You don't need another url. The response example is in [02-webhook-verification.php](https://github.com/mollie/mollie-api-php/blob/master/examples/02-webhook-verification.php)

**Comment by willemstuursma** [comment]
There is no cancel URL. See https://github.com/mollie/mollie-api-php/issues/18#issuecomment-255081190 where it was extensively discussed.
