### ISSUE TITLE
No timeouts set in API v2 client

### ISSUE THREAD

**Issue by willemstuursma** [mollie/mollie-api-php#278]
## Specifications

  - API Version: v2

## Describe the issue

There doesn't seem to be any default time outs set. 

A default timeout of 10s should be configured if no Client is passed.

**Comment by sandervanhooft** [comment]
@smitsel 👍 Sure I'll look into this.

**Comment by sandervanhooft** [comment]
@willemstuursma @Smitsel 

I can add it (it's simple) but I'm unable to test this in a non-integrative way (= without calling the API).

The current `$httpClient` generation is also not covered by any tests - all tests inject a mock client.

We could include a single integration test for this, but that would be a first.

Let me know whether:

1. you know another solution;
2. I should build a simple integration test (we could disable it by default in `phpunit.xml`);
3. I should just build it and test it manually.

Each of these options is fine with me. 😄

**Comment by willemstuursma** [comment]
3. Thanks.

**Comment by sandervanhooft** [comment]
There's also a connection timeout option, but I assumed you mean a "normal" response timeout.

**Comment by Smitsel** [comment]
This has been merged. Thanks again!
