### ISSUE TITLE
mollie-api-php integrate problem

### ISSUE THREAD

**Issue by chuzair53** [mollie/mollie-api-php#28]
Hi, 
I want to integrate mollie payment system in WebSite that develop in CodeIgniter FrameWork I need help some one who can help me to install mollie system in website thank's

**Comment by mollierobbert** [comment]
Sorry, we only offer a limited number of modules for popular webshop systems.

Please contact an external party for support with building CodeIgniter plugins, or try using existing Mollie plugins for CodeIgniter (for example https://github.com/kieranklaassen/codeigniter-mollie-ideal-api).
