### ISSUE TITLE
Mollie webhook can not call the specified API

### ISSUE THREAD

**Issue by tomzi** [mollie/mollie-api-php#29]
Hello,
I have a problem setting up a webhook url.
I use a staging url to do so like http://staging.mysite.be/mollie/webhook, i can call it publicly but still, i have this error message in the dashboard: 
"Mollie webhook can not call the specified API. Make sure your webhook exists and is publicly callable."
Could you please be more specific or give me a solution for this problem ?

Thanks a lot,
Thomas

**Comment by jdanthinne** [comment]
I had this problem once because I was using http instead of https. Have you tries that?

**Comment by lvgunst** [comment]
@tomzi Can you please send an email to info@mollie.com describing your problem? We can check our logs to find out why your webhook URL couldn't be called. Don't forget to include your Mollie partner ID and possibly a Payment ID (e.g. tr_xxxxxx).

**Comment by tomzi** [comment]
@lvgunst okay thank you, i do it right now!
