### ISSUE TITLE
No suitable mandates found for method

### ISSUE THREAD

**Issue by everydaypanos** [mollie/mollie-api-php#290]
## Specifications

  - API Version: 

## Describe the issue

Hello,
I am in TEST MODE and I am trying to create a new Subscription for a newly created Payment(mandate status = pending) and I always receive this error:

"No suitable mandates found for method"

Although I have just created a new Payment via the API and I can see one "pending" mandate, I cannot create the subscription.

PS The Subscription has a future start date.
PS The customer/user was not redirected to the checkout link though.

Thanks

**Comment by martinmollie** [comment]
Hi! Could you send the API call you're doing and the customer ID to info@mollie.com? That way we can provide more in-depth support to your issue.

**Comment by twf-nikhila** [comment]
@everydaypanos : Facing the same issue, did you got any solutions to it?
