### ISSUE TITLE
'next' link in '_links' contains https url to port 80

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [mollie/mollie-api-php#294]
When browsing through the payments of a settlement, the 'next' link contains a https url but also a specified port 80. This obviously breaks the next request.

For example:

```php
require_once __DIR__ . "/../../vendor/autoload.php";

$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setAccessToken("access_x");

$payments = $mollie->settlements->get('stl_x')->payments();

// Works
var_dump($payments);

// Broken
var_dump($payments->next());
```

The `_links` object on the payments contains a `next` link to `https://api.mollie.com:80/v2/settlements/stl_x/payments?limit=50` which is weird. Or am I missing something here?

**Comment by willemstuursma** [comment]
Thanks for reporting. Looking into it, will report back here.

**Comment by willemstuursma** [comment]
Thanks @SanderVanLeeuwen, this has been resolved.

**Comment by SanderVanLeeuwen** [comment]
Check, works fine now. Thanks for the quick fix :)
