### ISSUE TITLE
Feature request: payment events

### ISSUE THREAD

**Issue by robindirksen1** [mollie/mollie-api-php#295]
## Specifications

  - API Version: v1/v2

## Describe the issue

All the payments have a "history"/"events" section in the dashboard like payment started, scheduled payout etc.. Is it possible to load this via the payments api?

**Comment by willemstuursma** [comment]
What would be your use case? Just curious, to understand the feature request better.

**Comment by robindirksen1** [comment]
To show the employees the actions a enduser makes for debugging/support, like selecting a payment method during the checkout, or it's waiting for a SEPA transfer?

**Comment by willemstuursma** [comment]
Please send me an email with your Mollie partner ID and I will reach out to you tomorrow.
