### ISSUE TITLE
Example links not working

### ISSUE THREAD

**Issue by gasserol** [mollie/mollie-api-php#297]
## Specifications

  - API Version: 

## Describe the issue
The linked examples like 01-...., 02-.... are not working anymore. They did yesterday although.
...

**Comment by willemstuursma** [comment]
Thanks for reporting @gasserol.

@MollieRick can you fix this? @ndijkstra renamed the files, was merged earlier today.

**Comment by MollieRick** [comment]
Fixed! Again; thanks for reporting @gasserol. Happy coding!
