### ISSUE TITLE
Method to update order

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [mollie/mollie-api-php#299]
The current client doesn't provide a method to update address details of an order as documented at https://docs.mollie.com/reference/v2/orders-api/update-order.

**Comment by willemstuursma** [comment]
@sandervanhooft could you pick this up?

**Comment by sandervanhooft** [comment]
@willemstuursma sure!

@SanderVanLeeuwen It seems you are right, thanks for reporting this. I’ll look into this this week.

**Comment by sandervanhooft** [comment]
@SanderVanLeeuwen Update order is now available on the master branch

**Comment by SanderVanLeeuwen** [comment]
Thnx!

**Comment by Smitsel** [comment]
It has been released, thanks @sandervanhooft
