### ISSUE TITLE
Captured amounts are not reflected on payments or orders

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [mollie/mollie-api-php#301]
## Specifications

  - API Version: 2

## Describe the issue

Captured amounts for a payment are not reflected in the payment object itself. For example, capture `cpt_24ayoe` has a related payment `tr_PntgzVWkcq` but the payment itself has a `capturedAmount` of 0 instead of the captured amount.

The corresponding order `ord_3xnaz7` has no captured amount either. I'm not sure though if I'd ever expect orders to have captured amounts as those are captured on the corresponding payment(s) and not the order itself.

**Comment by Smitsel** [comment]
Hi @sandervanhooft,

Sorry for the delay on an answer to your question.
This order is an rather old one from the private beta where we still had issues with the capturing.

The issues with this are now resolved so new klarna orders should have these amounts reflected on the payment and order. 

Please let us know if you are still facing this issues with new orders.

**Comment by SanderVanLeeuwen** [comment]
Thnx. Looks like for new orders this is available as expected 👍
