### ISSUE TITLE
Best way to get the last error (if error known)

### ISSUE THREAD

**Issue by WebVooruit** [mollie/mollie-api-php#305]
## Specifications

  - API Version: 2

## Describe the issue

...
Recently I am getting empty return from $payment->getCheckoutUrl() 

What is the best way to get the error that is causing this.

**Comment by sandervanhooft** [comment]
@WebVooruit If there's an API call error you should get it directly.

But this doesn't necessarily have to be an error. There are create payment methods that do not require a checkout (i.e. recurring / mandated payments). What code are you using to create the payment / what does the payload look like?

**Comment by WebVooruit** [comment]
The code hasn't changed in months... 
$payment = $mollie->payments->create(.....);
$url = $payment->getCheckoutUrl();

It is any kinds of payment that brings this up. iDeal, creditcard, Mistercash etc.

**Comment by sandervanhooft** [comment]
@willemstuursma any ideas?

**Comment by willemstuursma** [comment]
Without any code, it will be impossible to debug @WebVooruit.

**Comment by MollieRick** [comment]
@WebVooruit Do you still have this issue?

**Comment by WebVooruit** [comment]
No, this issue has been fixed.

The issue was due to problems with iOS posts in a very early version of iOS 12. 

The postdata from some mobile users was empty making it go into a weird mode. 

Had nothing to do with Mollie, Safari iOS12 issue.

**Comment by MollieRick** [comment]
Thank you for your response. We'll close this issue then :-)
