### ISSUE TITLE
Payment for canceled order still has status 'authorized'

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [mollie/mollie-api-php#306]
## Specifications

  - API Version: 2

## Describe the issue

When canceling an order, the corresponding payment status doesn't change to 'canceled' but remains 'authorized'. In case of an Klarna payment this suggests that the corresponding Klarna payment (from a consumer perspective) isn't canceled either?

It doesn't matter if the order is canceled through the API or in the Mollie dashboard; both give the same result.

For example; orders `ord_aklvo3` and `ord_bj4851` have been canceled, but their corresponding payments `tr_9G9sHfvC92` & `tr_m9x7C6MCvx` are still authorized.

**Comment by willemstuursma** [comment]
Hi @sandervanhooft. Thanks, this is on our todo list.

**Comment by sandervanhooft** [comment]
@willemstuursma probably meant @SanderVanLeeuwen 😄

**Comment by SanderVanLeeuwen** [comment]
Great name, isn't it? ;)

But thanks for the reply. I hope it will be resolved before customers start complaining about open invoices at Klarna 🙈

**Comment by willemstuursma** [comment]
I think it is taken care of - I'll double check tomorrow.

**Comment by willemstuursma** [comment]
@SanderVanLeeuwen just confirming that the authorization is released at Klarna when the order is canceled.

We'll update this issue when we've fixed the bug regarding the payment's status.
