### ISSUE TITLE
error in autoload.php

### ISSUE THREAD

**Issue by PanderBoy18** [mollie/mollie-api-php#314]
I'm getting the error as shown below. Help/hint anyone ?!!

Parse error: syntax error, unexpected '.' in /var/www/xxxxxx.nl/folder/mollie/vendor/autoload.php on line 11

Line 11:         return \_PhpScoper5be2fdb7243e7\database_read(...func_get_args());

**Comment by Smitsel** [comment]
Hello! What version of PHP is your server running?
It is having trouble with the splat operator (...) which is added in php 5.6

This package does not work with PHP versions < 5.6

**Comment by Smitsel** [comment]
If you are running a lower version i can recommend updating it.

If this is not an option somehow you can always use our V1 API:
https://github.com/mollie/mollie-api-php/releases/tag/v1.9.11

Please report back if you are running 5.6 or higher and still facing this issue.
