### ISSUE TITLE
Add support for the list chargebacks API

### ISSUE THREAD

**Issue by JorikMollie** [mollie/mollie-api-php#315]
## Specifications

  - API Version: 2.1.5

## Describe the issue

Integrate the List Chargebacks API in the PHP-client. It seems that this API is missing.

## Relevant documentation

https://docs.mollie.com/reference/v2/chargebacks-api/list-chargebacks

**Comment by JorikMollie** [comment]
@sandervanhooft Can you take a look?

**Comment by sandervanhooft** [comment]
@JorikMollie Sure I'll take a look!

**Comment by sandervanhooft** [comment]
So the issue is that currently only the paymentChargeback endpoint is implemented. I'll add the (root) Chargeback endpoint, will create and merge a PR later this week.

**Comment by sandervanhooft** [comment]
@JorikMollie Do you have an example response for a call to `https://api.mollie.com/v2/chargebacks`?

**If** it's the same as to `https://api.mollie.com/v2/payments/*paymentId*/chargebacks`, is the response also non-paginated?

**Comment by sandervanhooft** [comment]
@JorikMollie
Just merged the PR solving this issue. 
I've assumed that the responses are about the same.

**Comment by willemstuursma** [comment]
Is this resolved now @sandervanhooft ?

**Comment by sandervanhooft** [comment]
@willemstuursma Yes it is!
