### ISSUE TITLE
isRefunded method not valid in Order Resource

### ISSUE THREAD

**Issue by ndijkstra** [mollie/mollie-api-php#321]
@sandervanhooft Can you take a look at this issue?

https://github.com/mollie/mollie-api-php/blob/master/src/Resources/Order.php#L206
This method is incorrect because an order can't have the status refunded.

Also change the example if necessary: https://github.com/mollie/mollie-api-php/blob/master/examples/orders/webhook.php

**Comment by sandervanhooft** [comment]
Hi @ndijkstra!

Just checked the docs, you're right!

In theory removing the `isRefunded()` method could cause breaking changes. Practically I'm not so sure. I can either

1. remove the method
2. mark it as deprecated, remove in next major release

Also, I noticed that the `pending` status is missing. I'll add that in a separate PR.

**Comment by sandervanhooft** [comment]
Do you want me to remove or deprecate?

**Comment by sandervanhooft** [comment]
Same goes for the OrderLine resource btw, it also should not have a `refunded` status.

**Comment by Smitsel** [comment]
I think the option you PRed is best. Deprecation. We can deal with it in a new major.

**Comment by sandervanhooft** [comment]
Thanks @Smitsel!
