### ISSUE TITLE
add support for enabling/disabling methods

### ISSUE THREAD

**Issue by sweebee** [mollie/mollie-api-php#332]
## Specifications

  - API Version: 2

## Describe the issue

its just integrated in the API, would be nice to use in this wrapper.

https://docs.mollie.com/reference/v2/profiles-api/enable-method

**Comment by willemstuursma** [comment]
@sandervanhooft could you give this a shot?

If not possible, the exception should have a method that can easily give you the URL where the merchant can enable the payment method.

**Comment by sandervanhooft** [comment]
Sure thing @willemstuursma !

**Comment by sandervanhooft** [comment]
Shouldn't the profile method response include a `_link` to the `profile` as well?

**Comment by willemstuursma** [comment]
@MollieRick could you look into this?

**Comment by MollieRick** [comment]
@sandervanhooft @willemstuursma I will add it.

**Comment by sandervanhooft** [comment]
> @sandervanhooft could you give this a shot?
> 
> If not possible, the exception should have a method that can easily give you the URL where the merchant can enable the payment method.

```
HTTP/1.1 422 Unprocessable Entity
Content-Type: application/hal+json; charset=utf-8

{
    "status": 422,
    "title": "Unprocessable Entity",
    "detail": "Can not enable Credit card via the API. Please go to the dashboard to enable this payment method.",
    "_links": {
         "dashboard": {
                "href": "https://www.mollie.com/dashboard/settings/profiles/pfl_v9hTwCvYqw/payment-methods",
                "type": "text/html"
         },
         "documentation": {
                "href": ":doc:`https://docs.mollie.com/guides/handling-errors </guides/handling-errors>`",
                "type": "text/html"
         }
    }
}
```

The API exception message is passed through by default. You want me to catch this and amend the message to include the link?

I think a better solution may be to amend the message at the API. You'll probably need it in all integrations.

Instead of:
```
Can not enable Credit card via the API. Please go to the dashboard to enable this payment method.
```

Do something like:
```
Can not enable Credit card via the API. Please enable it here: https://www.mollie.com/dashboard/settings/profiles/pfl_v9hTwCvYqw/payment-methods
```

**Comment by willemstuursma** [comment]
I would like it to be possible for integrators to easily create a clickable link if enabling automatically fails.

So the exception should have some `getDashboardLink()` method.

**Comment by sandervanhooft** [comment]
Interesting idea @willemstuursma , I'm on it!

**Comment by sandervanhooft** [comment]
@willemstuursma Currently the ApiException does not include this. Is there another way of accessing the response object / `_links` that I'm overlooking?

**Comment by sandervanhooft** [comment]
@MollieRick ?

**Comment by willemstuursma** [comment]
Better to create an `ApiException::fromParsedResponse(stdClass $response): self` method that constructs the exception.

**Comment by MollieRick** [comment]
> Shouldn't the profile method response include a `_link` to the `profile` as well?

@sandervanhooft We decided to closed this PR and not implement this. We using resources and these must be the same on every point in the API. Adding a profile link to every method resource makes no sense.

**Comment by sandervanhooft** [comment]
@MollieRick noted!

@willemstuursma That makes more sense, thanks!

**Comment by sandervanhooft** [comment]
@willemstuursma Just looked into refactoring the `ApiException`, I will open a separate issue + PR for this.

(This also means that the `getDashboardLink()` feature moves to that issue/PR.)

**Comment by MollieRick** [comment]
Support has been added for the API call.
