### ISSUE TITLE
Order payments

### ISSUE THREAD

**Issue by ndijkstra** [mollie/mollie-api-php#352]
`$order->payments()` is not yet implemented in the PHP Client.
https://docs.mollie.com/reference/v2/orders-api/get-order#embedding-of-related-resources

**Comment by sandervanhooft** [comment]
I'll whip something up! 😄

**Comment by sandervanhooft** [comment]
#353

**Comment by sandervanhooft** [comment]
I've prepared a new release for next Monday to introduce the `$order->payments()` helper.

**Comment by Smitsel** [comment]
This has been done and released. Thanks @sandervanhooft
