### ISSUE TITLE
Feature request: List only valid mandates

### ISSUE THREAD

**Issue by Cannonb4ll** [mollie/mollie-api-php#367]
Currently building subscriptions in my SaaS application where I only want to display 'valid' mandates to my users/customers.

Seeing the API documentation I see there is no such option currently. For now, I am filtering in my own collection method;

```php
    public function getMandates()
    {
        return $this->getOrCreateMollieUser()->mandates();
    }

    public function getValidMandates()
    {
        return collect($this->getMandates())->filter(function (Mandate $mandate) {
            return $mandate->status == 'valid';
        });
    }
```

This seems cumbersome, some sort of filter to return only valid mandates would be way more optimized.

Please let me know if this was detailed enough and if it needs further explanation.

**Comment by sandervanhooft** [comment]
Thanks @Cannonb4ll for submitting this issue.

Based on this, I'm preparing a PR for client-side filtering a MandateCollection by Mandate status.

There are no plans for adding filtering to the API.

**Comment by sandervanhooft** [comment]
See PR #368

**Comment by Cannonb4ll** [comment]
Thanks @sandervanhooft for your quick work. 🚀

If an actual filter in the API itself would be available I would recommend changing that, as I am not sure what pagination would do in this case if records are above 250> I believe. (Not that I get users that create that much subscriptions so i'm good for now).

Thanks!

**Comment by MollieRick** [comment]
It don't think this is worth the effort. Like you said; I don't think an API Customer will get that many mandates. Besides that; filtering by the developer is not that much effort. Close this issue for now.

Thanks for the request!
