### ISSUE TITLE
Strange release number:  v1.9.12 => v1.19.123

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#369]
## Specifications

  - API Version: 1

## Describe the issue
Is it correct that the 1.x version changed from `1.9.12` to `1.19.123` while the "name" of the release is `1.19.13`...

https://github.com/mollie/mollie-api-php/releases/tag/v1.19.123

😕 

Seems like a typo to me ? Or was it a VriMiBo release :shipit: 😄

**Comment by willemstuursma** [comment]
Sorry, it was a Friday release! 

Moved the tags around, should be good now. Got less than 5 installs of the wrong version, according to Packagist.
