### ISSUE TITLE
PaymentLink API not included / mentioned?

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#37]
**Context**
Periodically, we are sending out invoices by e-mail, which include a PDF attachment (with the same invoice data). We would like to include a (never-expiring) [PaymentLink](https://www.mollie.com/en/docs/paylinks) in both e-mail and PDF. 

**Observation**
I noticed the PaymentLink API differs a bit from how this Mollie-API-PHP client works. For example, the endpoints are:

- PaymentLink API: https://www.mollie.com/xml
- Mollie-API-PHP: https://api.mollie.nl

**Questions**
So before  I start creating something on our own, some questions:

- is the PaymentLink API scheduled to included in the Mollie-API-PHP client (this library)?
- is the PaymentLink API scheduled to be deprecated / cancelled somewhere in the near future, or is it safe to start using it (with the long-term in mind 😄 ).

**[And then?](https://www.youtube.com/watch?v=GKNX6dieVcc)**
Maybe I am missing something, but it might be an idea to include a bit on this topic in the Mollie-API-PHP documentation? On why there is a difference (historic reasons?), how the future will look like, etc.

**Comment by mollierobbert** [comment]
Thanks for your input, Menno. Our payment links API is a legacy API that we no longer actively develop or support. We will not be including the API in our official API clients.

We're working on an OAuth based alternative for generating payment links that will supersede the payment links API. We'll announce it in a few months.

The API endpoint itself will not be removed any time soon, so feel free to build something yourself on top of it.

**Comment by holtkamp** [comment]
ok thanks for the clarification!

**Comment by holtkamp** [comment]
@mollierobbert is there a place where feature requests can be done concerning the new Payment Links API? It would be nice to be able to provide some metadata when generating the Payment Link. In our case, an invoice UUID. Currently we need to 'abuse' the description for this, not optimal 😄

**Comment by mollierobbert** [comment]
Feature requests can be sent to info@mollie.com. However, since the payment links API is deprecated, we're unlikely to implement that feature. I would advise to await our OAuth alternative then.

If you're in a hurry, please note a payment link is nothing but a page that generates an API payment when you open it. It should be fairly easy to create your own payment links that are tailored to your needs.

**Comment by holtkamp** [comment]
> I would advise to await our OAuth alternative then.
Yeah, that was idea

> please note a payment link is nothing but a page that generates an API payment when you open it. It should be fairly easy to create your own payment links that are tailored to your needs.

Aah, good to know, guess this is the way to go then, thanks!

**Comment by hansrossel** [comment]
Any updates on the status of the OAuth alternative?
