### ISSUE TITLE
How to check the webhook url page output after payment done.

### ISSUE THREAD

**Issue by ramkumawathis** [mollie/mollie-api-php#371]
## Specifications

  - API Version: 

## Describe the issue

...

**Comment by robindirksen1** [comment]
Hi @ramkumawathis, can you please describe your issue with some more details about what you want to achieve?

For example:
- Do you want to see what Mollie see's when they call the webhook? You can see the response code in the Dashboard
- Do you want to debug you development environment with a fake webhook so you can see what Mollie see's when they call your webhook?

**Comment by ramkumawathis** [comment]
@robindirksen1 
Am using this mollie  payment method.
-> i have successfully done the payment through mollie with paypal.  after payment,  i want to  update the database payment status for webhookUrl. How i will check the webhookUrl response.

**Comment by robindirksen1** [comment]
You can check the webhookURL response by making a post request to your webhook-url with an ID of the transaction (tr_******). This is the same way as mollie sends a webhook, more information at the bottom of this comment.

In this repo there are some example, here you can find it for the payments webhook: https://github.com/mollie/mollie-api-php/blob/master/examples/payments/webhook.php. With this example you can implement it in your own system. 

To test the webhook you can deploy the files to a public server that can be access by mollie's servers. If you're developing it locally, you can use ngrok (https://ngrok.com/).

For more information, take a look at: 
- https://docs.mollie.com/guides/webhooks
- https://help.mollie.com/hc/en-us/articles/213470409-My-webhook-URL-is-invalid-or-not-working-What-is-the-problem-

**Comment by willemstuursma** [comment]
Thanks @robindirksen1.

@ramkumawathis you can also call / email Mollie (they speak multiple languages).
