### ISSUE TITLE
Getting customer in Webhook

### ISSUE THREAD

**Issue by pjeutr** [mollie/mollie-api-php#372]
## Specifications

  - API Version: 2.8.1

## Describe the issue

During the payment we get the customer id, like this
```
$payment = Mollie::api()->payments()->get($transaction_id);
$payment->customer_id
```

When we use the following code in the webhook, we get `Undefined property: Mollie\Api\Resources\Payment::$customer_id`
```
$payment = Mollie::api()->payments()->get($request->id);
Log::info(json_encode($payment));
$payment->customer_id
```

The log show that customerId is present in the response
```
 {"resource":"payment","id":"tr_xxx","mode":"test",
-- knip --
"customerId":"cst_xxx"} 
```

Seems logical this would work, Is this a bug? Or am I missing something.

**Comment by pjeutr** [comment]
Sorry, I was mixing things up. The first one is also not working.
Would be cool thought to get the customerId this easily. I will look now for another way to get it.

**Comment by sandervanhooft** [comment]
Hi @pjeutr,

Try `$payment->customerId` instead of `$payment->customer_id`.

**Comment by pjeutr** [comment]
Duhh.. Need lunch not thinking clearly, thanks for the headsup!

**Comment by pjeutr** [comment]
Duhh.. Need lunch not thinking clearly, thanks for the headsup!

**Comment by sandervanhooft** [comment]
No problem, enjoy (your lunch 😉)!
