### ISSUE TITLE
Webhook does not work

### ISSUE THREAD

**Issue by danman1234** [mollie/mollie-api-php#378]
Webhook file is reachable, by the browser
But it does not send any post value to this url whatsoever.

I think mollie has a bug.

`	$payment = $mollie->payments->create([
		  "amount" => [
				"currency" => "EUR",
				"value" => "".$_GET['amount']."" // You must send the correct number of decimals, thus we enforce the use of strings
		  ],
		  "description" => "Premium rapport",
		  "redirectUrl" => "".HTML_ROOT."betaald",
		  "webhookUrl" => "".HTML_ROOT."inc/webhook.php",
		  "metadata" => [
				"order_id" => "12345",
		  ],
	]);	
	?><script>window.location = '<?=$payment->getCheckoutUrl();?>';</script>
    <?php`

For dutch speakers is here another link: https://www.phphulp.nl/php/forum/topic/mollie-webhook-werkt-niet/102869/1/#0

**Comment by sandervanhooft** [comment]
This is not a bug in this package.

Most likely, your webhookUrl is still unreachable.

Checking whether  your webhookUrl is reachable via your _local_ browser is not a good way to test this if the url is hosted from the same machine/on your local network. 

More info here: https://help.mollie.com/hc/en-us/articles/213470409.

Please contact [Mollie support](https://www.mollie.com/support) if you need further assistance.

**Comment by danman1234** [comment]
No my webhook Url is very very reachable. ow it worked b4, and now not, I think this mollie is really bugged.

I not check it on localhost but on my webserver

**Comment by sandervanhooft** [comment]
Ok, thanks for clearing that up. Please contact support.
