### ISSUE TITLE
How to install this in  my project 

### ISSUE THREAD

**Issue by maitrixtca** [mollie/mollie-api-php#379]
## Specifications
when i open example folder then its show blank screen
  - API Version: 

## Describe the issue

...

**Comment by sandervanhooft** [comment]
The example folder is not meant to be executed, but read instead by a human developer for inspiration.

Please follow along the installation instructions in the readme, and check out the documentation at [docs.mollie.com](https://docs.mollie.com).

An overview of ready-to-use, platform-specific packages can be found [here](https://www.mollie.com/en/developers/packages).
