### ISSUE TITLE
Retrieving payments when in testing mode

### ISSUE THREAD

**Issue by Ken-vdE** [mollie/mollie-api-php#385]
## Specifications

  - API Version: 2.1.6

## Describe the issue

 I'm having a hard time figuring out how to correctly process my webhook calls by Mollie when in test mode. I don't get a payment Id from mollie when in test mode and when I try to retrieve a payment using a fake id I get `No payment exists with token tr_7UhSN1zuXS` (where `tr_7UhSN1zuXS` is a fake id)

**Comment by sandervanhooft** [comment]
Hi @Ken-vdE ,

Thanks for opening this ticket.

**1.**
Would it be possible for you to upgrade to the latest version? (It's currently at 2.9.1)
AFAK there have been no breaking changes, so you should be good.

**2.**
Can you share how you configure the mollie client? Are you authenticating using an api key or OAuth (access token)?

**3.**
Can you share the calls you're making and/or failing tests you're running?

**Comment by Ken-vdE** [comment]
1. I will make sure to check if that's possible.
2. I'm using an API key
3. The `$mollie->payments->create()` works fine, it's just the webhook call made by Mollie afterwards. Here the call doesn't contain a payment id because I'm using testing mode. Within the call i run `$mollie->payments->get()` with a random id and this returns the error above.

**Comment by sandervanhooft** [comment]
So what you're trying to test is handling webhook calls for subsequent subscription payments' updates?

Or for the first payment in order to obtain a mandate?

**Comment by Ken-vdE** [comment]
I'm just making a simple mock payment which calls the webhook when I say the payment was 'paid'.
![image](https://user-images.githubusercontent.com/15888558/57015223-db3e9180-6c13-11e9-8a13-fbc94e885f2b.png)

**Comment by sandervanhooft** [comment]
What I usually do is split the test in two:

1. Assert that my app can create the payment
2. For a given payment (you can prepare one manually), assert that if I call my webhook using a POST request using the payment id (like Mollie would do), it is handled correctly in my app.

**Comment by sandervanhooft** [comment]
So essentially I prepare one payment for that test case and use the same id every time I test the webhook.

**Comment by sandervanhooft** [comment]
(The test data is stored indefinitely, so no issues there.)

**Comment by Ken-vdE** [comment]
@sandervanhooft Good idea, I'm going to give that a try!

**Comment by sandervanhooft** [comment]
Great, I'll close this for now, let me know how it went! :)
