### ISSUE TITLE
phpstan (with level >= 6) warns about undefined properties on amount objects

### ISSUE THREAD

**Issue by nederdirk** [mollie/mollie-api-php#389]
## Specifications

  - API Version: Any Mollie PHP SDK version 2
  - PHPstan version: 0.11

## Describe the issue

We lint our PHP app with the `phpstan` static analysis tool[1], and the version 2 Mollie PHP SDK triggers warnings/errors when dereferencing a property of any of the `amount*` fields of the `\Mollie\Api\Resources\Payment` class. This would be solved by updating the PHPdoc typehints to `\stdClass`.

[1] https://github.com/phpstan/phpstan

## Example:
```php
assert($payment instanceof \Mollie\Api\Resources\Payment);
$x = $payment->amount->value;
```

will yield the following error while running `phpstan analyse` with `--level=6` or `--level=7`:
```
example.php:2:Access to an undefined property object::$value.
```

**Comment by nederdirk** [comment]
I'm working on a PR for this issue

**Comment by willemstuursma** [comment]
That's great @nederdirk, maybe the PR can also include running phpstan?

**Comment by nederdirk** [comment]
> That's great @nederdirk, maybe the PR can also include running phpstan?

That would be slightly more work, and a different unit of work. I'll work on a separare PR
