### ISSUE TITLE
Mandate filter

### ISSUE THREAD

**Issue by a3020** [mollie/mollie-api-php#39]
The docblocks mention a [filter parameter](https://github.com/mollie/mollie-api-php/blob/master/src/Mollie/API/Resource/Customers/Mandates.php#L32) for the all() method in the Mandate Resource class.

How does this filter work exactly? It's not in the [API docs](https://www.mollie.com/en/docs/reference/mandates/list) nor in the examples. 

For example, it would be helpful to filter on VALID mandates. That way we don't have to write custom methods like this company [did](https://github.com/Cloudstek/mollie-php-api/blob/124d741a2e17c8e67d017c3bfc3d6b4388908bc7/src/Resource/Customer/MandateResource.php#L107).

**Comment by Thijs-Riezebeek** [comment]
Dear a3020,

Thank you for bringing this to our attention. The `all()` method has `$offset` and `$count` as its first two parameters. These are used for pagination and are added as GET parameters to the URL (e.g. `?offset=10&count=15`). The third `$filter` parameter can be used to dynamically provide any other GET parameters to the query. For most `all()` functions this is irrelevant, but some do allow for additional parameters to be present. I will list these here.

* [List Methods](https://www.mollie.com/en/docs/reference/methods/list): Allows the `locale` parameter.
* [List Settlements](https://www.mollie.com/en/docs/reference/settlements/list): Allows the `reference` parameter.
* [List Invoices](https://www.mollie.com/en/docs/reference/invoices/list): Allowsthe `year` and `reference` parameter and also the `include` parameter (more on this below).

For more details on what these parameters do, visit their documentation page. An example of how to use them:

```php
$mollie_api_client->methods->all(0, 50, array(
    "locale" => "en_US"
))
```

Furthermore, some endpoints also allow you to pass the `include` parameter. This does not impact which resources are returned, but allows you to include additional data on that resource. See the [List Invoices page](https://www.mollie.com/en/docs/reference/invoices/list) for an example of this.

Finally, some endpoints (when used via OAuth) allow you to specify the `profileId` and `testmode` parameters (e.g. [List Payments](https://www.mollie.com/en/docs/reference/payments/list)).

As for your specific request on retrieving only valid mandates, this feature is currently unavailable in our API and I would not expect it to be there any time soon.
