### ISSUE TITLE
Apple Pay not available - status

### ISSUE THREAD

**Issue by mvdnbrk** [mollie/mollie-api-php#393]
## Specifications

  - API Version: 2.10.0

## Describe the issue

When a customer chooses "Apple Pay" and it is not available (see screenshot) the customer is redirected back to the `Redirect URL`. The status of that payment is `open` in Mollie.

Is this desired behaviour?
In this case I would expect a status `failed` rather than `open`.

<img width="419" alt="Schermafbeelding 2019-06-12 om 16 25 25" src="https://user-images.githubusercontent.com/802681/59359670-11048900-8d2f-11e9-9c33-4f05e3e2be9a.png">

**Comment by willemstuursma** [comment]
Thanks @mvdnbrk. 

Are you testing that the shopper's browser supports Apple Pay with the `window.ApplePaySession && window.ApplePaySession.canMakePayments()` check? 

See https://docs.mollie.com/wallets/applepay#adding-apple-pay-to-the-method-selection.

**Comment by mvdnbrk** [comment]
@willemstuursma I could certainly do that javascript check on the client side, which would disable or hide the selection for "Apply Pay".

However that is just a javascript check which will only hide/disable that option in the form. It is still a regular HTML form which can be altered or spoofed by a user. 

If for some reason a user hits the Mollie payment screen and Mollie responds with "_Apple Pay is not available, please try another payment method_" the user will be redirected back to the given `Redirect URL` promptly. 

At that point the payment status will still be `open`. In this situation I would expect a payment status of `failed`.  There is no need to keep he payment status `open` because it is not available at the client side and should be considered as failed.

**Comment by willemstuursma** [comment]
@mvdnbrk of course, we'll fix it. 

Please be aware that the check is required per Apple guidelines.

I'll update here when the issue has been resolved.

**Comment by mvdnbrk** [comment]
Thanks :)

**Comment by sandervanhooft** [comment]
@albert-carreras any update on this?

**Comment by willemstuursma** [comment]
Sorry, we don't have any updates on this.

**Comment by willemstuursma** [comment]
@sandervanhooft a fix will be deployed early next week. The payment will be considered canceled if the shopper does not have Apple Pay on the device.
