### ISSUE TITLE
De-couple from Guzzle

### ISSUE THREAD

**Issue by XedinUnknown** [mollie/mollie-api-php#395]
## The Problem
This library is explicitly coupled to Guzzle, which presents the following issues:

1. Forces consumers to use and ship Guzzle.
1. Makes it impossible to correctly integrate with WordPress (and other engines) by using the engine's own HTTP client.

## Suggested Solution
Re-factor to consume [PSR-18][] instead of Guzzle.

[PSR-18]: https://www.php-fig.org/psr/psr-18/

**Comment by sandervanhooft** [comment]
> ## The Problem
> This library is explicitly coupled to Guzzle, which presents the following issues:
> 
> 1. Forces consumers to use and ship Guzzle.
> 2. Makes it impossible to correctly integrate with WordPress (and other engines) by using the engine's own HTTP client.

@XedinUnknown Thanks for opening this ticket.

This relates to PR #230, which was closed . See my comment [here](https://github.com/mollie/mollie-api-php/pull/230#issuecomment-409607860) in particular.

I agree with point 1, but that's not an issue without taking point 2 into consideration.

There are some workarounds for point 2 which have been proven to work with Wordpress and the like.

What do you think @MollieRick ?

**Comment by MollieRick** [comment]
I agree with @sandervanhooft. It can cause a lot of broken integrations.
Guzzle is not known HTTP client in the PHP-world. I don't see a reason for changing it now, maybe in the future with a v3.

**Comment by sandervanhooft** [comment]
Thanks @XedinUnknown and @MollieRick .

I've added this to the list for [the next major version](https://github.com/mollie/mollie-api-php/projects/1).

**Comment by XedinUnknown** [comment]
Thanks for considering this.

I disagree that point one doesn't matter without point 2: in my view, point 1 is the real problem (broken SOLID) and point 2 is simply a consequence. Nevertheless, regardless of how you look at it, I believe that together addressing this point holds a lot of practical value (contrary to the [comment][1]). Forcing a particular implementation breaks architecture, and AFAIK makes proper integration completely impossible. I am not aware of any workarounds that would work with WordPress - would you kindly be able to point me in their direction?

Of course, I understand that this is a BC break, and I agree that no matter how small, it requires a major version increase. Which I am completely fine with, just as well as using an unstable version of that build. We would really like to have proper integration in one of the upcoming releases of [mollie/WooCommerce][], which we are now maintaining.

Would it be possible to change the target of the old PR to a new e.g. `3.0` branch? When do you think it could be considered and merged? I would be happy to contribute, if this could move things along.

[1]: https://github.com/mollie/mollie-api-php/pull/230#issuecomment-409607860
[mollie/WooCommerce]: https://github.com/mollie/WooCommerce/

**Comment by willemstuursma** [comment]
Lets have a look at this tomorrow @XedinUnknown.

In WooCommerce, we used to use a scoped version of this client with all dependencies wrapped in a dedicated namespace. A scoped version can be found at the downloads, the Makefile contains instructions for building it.

**Comment by XedinUnknown** [comment]
Sure, will be happy to provide feedback or code.

> In WooCommerce, we used to use a scoped version of this client with all dependencies wrapped in a dedicated namespace.

Scoping may be a good idea to avoid namespace conflicts, but it doesn't make your solution any less coupled to now the scoped classes. With PSR-18, anyone can use this SDK with whichever client they are working with.

**Comment by sandervanhooft** [comment]
Yeah, I think we're all on the same page on that :).

**Comment by XedinUnknown** [comment]
Hi! Any updates on this? :)

**Comment by willemstuursma** [comment]
Hi @XedinUnknown. I thought a bit about it but I'm not really hot on it. 

As you pointed out: since it is backwards incompatible, it will require a new major version to be released. 

However, we have a lot of installs of the current version and want to keep supporting our clients that are using this version. That means that we will have to update two versions, every time we add a new endpoint, property or feature to our API. This will be costly and annoying, and confusing to our customers (which version to choose). 

I'm a big van of the PHP Framework Interop Group, but I feel that PSR-18 has failed. Not because it is a bad specification, but because Guzzle is almost the de-facto standard for HTTP clients in the PHP world.

Therefore, I don't see much value in supporting PSR-18 right now.

**Comment by alcohol** [comment]
@XedinUnknown not sure if you're still interested, but my client uses the Symfony http client contracts a lot (which also offers PSR17 / PSR18 interoperability), and I worked around this limitation for my client by implementing the `MollieHttpAdapterInterface`. It still feels a bit hacky, but you can provide your own implementation as an entry-point at least.

> Note: this is a very stripped down version, but it gets the idea across I think.

```php
<?php declare(strict_types=1);

namespace Foo\Mollie;

use Mollie\Api\Exceptions\ApiException;
use Mollie\Api\HttpAdapter\MollieHttpAdapterInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class HttpClientAdapter implements MollieHttpAdapterInterface
{
    public function __construct(
        private readonly HttpClientInterface $client
    ) {
    }

    public function send($httpMethod, $url, $headers, $httpBody)
    {
        try {
            $response = $this->client->request($httpMethod, $url, [
                'headers' => $headers,
                'body' => $httpBody,
            ]);

            return json_decode($response->getContent(), false, 512, JSON_THROW_ON_ERROR);
        } catch (\Throwable) {
            throw new ApiException();
        }
    }

    public function versionString()
    {
        return 'Foo/1.0';
    }
}
```
```php
<?php
 
$adapter = new Foo\Mollie\HttpClientAdapter($myClient);
$mollie = new Mollie\Api\MollieApiClient($adapter);
```

I'm not sure how PSR18 can be considered to have failed nor why anyone would think Guzzle is the de-facto standard (if anything, that would be cURL). Both httplug and psr18 actually have done a lot of good for API client libraries IMHO.

**Comment by XedinUnknown** [comment]
Thanks, @alcohol! I hope your solution will help those who came here looking for a solution!

🙏
