### ISSUE TITLE
PHP API update for PHP 7.2+ - guzzlehttp

### ISSUE THREAD

**Issue by StonehengeCreations** [mollie/mollie-api-php#396]
The most recent version of the Mollie PHP API (2.10.0) is still using a (soon to be) outdated version of guzzlehttp. 

In /vendor/guzzlehttp/promises/src/functions.php, lines 222, 257 and 313 use the function each(). That has been deprecated since PHP 7.2 (2017-11-30) and should be replaced with a foreach() loop.

Since PHP is not known for keeping backward compatibility (for a long time anyway), could you please update this soon to prevent future errors? PHP 7.3. has already been released and 7.4 is just a few months away.

Thank you very much in advance.

**Comment by willemstuursma** [comment]
How are you installing Guzzle? Our version constraint is set to `^6.3`, so installing the most recent version 6.3.3 (from April) should not be a problem.

**Comment by StonehengeCreations** [comment]
By using the default composer as stated on the main page. So the install is done automatically.

**Comment by willemstuursma** [comment]
See https://github.com/guzzle/promises/issues/93, that explains that the function call `each` there does not refer to the `each` function from PHP but for `\GuzzleHttp\Promise\each()` that lives in the same file.

**Comment by StonehengeCreations** [comment]
It still gives warnings (and probably errors if deleted in PHP soon) when doing a PHP check. It should still be changed to avoid confusion.
