### ISSUE TITLE
Can't update order when fetched with related resources

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [mollie/mollie-api-php#397]
When an order is fetched with related (embedded) resources, updating the order fails with an exception `Non-existent query parameter "embed" for this API call.. Field: embed.`. The queryparameters are probably sent alongside the request because of the preceding get.

Reproduce:

```php
$client = new \Mollie\Api\MollieApiClient();
$client->setApiKey(xxx);

$order = $client->orders->get('ord_xxx', ['embed' => 'payments']);

$order->billingAddress->email = 'joehoe@werkaandemuur.nl';
$order->update();
```

Throws the described exception. 

It's possible to work around this by fetching the order (again) without embedded payments, but I think it would be nice when the library can properly handle this.

**Comment by willemstuursma** [comment]
Looks like a bug in our API, I think it should be possible to update the order and immediately get the payments too.

@MollieRick can you create an issue on our end and resolve it?

**Comment by willemstuursma** [comment]
This has been resolved @SanderVanLeeuwen, can you confirm that it now works?

**Comment by SanderVanLeeuwen** [comment]
Yes, works without the workaround. Thanks for the quick fix :)
