### ISSUE TITLE
Retrieve payments with oAuth not working in testmode

### ISSUE THREAD

**Issue by RyonMB** [mollie/mollie-api-php#398]
## Specifications

  - API Version: 
v2.10.0
## Describe the issue

I have got an issue that I can't retrieve payments through oAuth with the testmode enabled.
It is the same issue as in this thread, but it is still not working for me: 
https://github.com/mollie/mollie-api-php/issues/232

This is the code I am using: 
`$customer = $mollie->customers->get($customerid->customer_id, ['testmode' => 'true']); $betalingen = $customer->payments();`

And this is the error I am getting:

'Error executing API call (404: Not Found): Customer cst_H7UqgxMDzH exists, but the wrong mode is used. Try switching live / test API keys. '

**Comment by sandervanhooft** [comment]
Thanks @RyonMB , can you (double) check in the Mollie dashboard that this customer was created in test mode?

**Comment by RyonMB** [comment]
Hello!

I already found the issue, with the composer require command, it installed 2.0, even when I mentioned I wanted 2.10. Thanks for your quick response!

**Comment by sandervanhooft** [comment]
No problem, glad it worked out 🎉
