### ISSUE TITLE
 The start date can not be changed when the subscription is already charged. Field: startDate. 

### ISSUE THREAD

**Issue by RyonMB** [mollie/mollie-api-php#399]
## Specifications

  - API Version: 2.10.0

## Describe the issue

I am trying to update a subscription with this code. It's not with all subscriptions, only some of them

```
$customer = $mollie->customers->get($customerid);
            $subscription = $customer->getSubscription($subid);
            if ($operator == '-') {
                $geld = $subscription->amount->value - env($module);
                $active = 'inactive';
            } else if ($operator == '+') {
                $geld = $subscription->amount->value + env($module);
                $active = 'active';

            } else {
                return ('ERROR');
            }
            $subscription->amount = (object) [
                "value" => number_format($geld, 2, '.', ''),
                "currency" => "EUR",
            ];
            $subscription->update();
```

I am getting this error:  The start date can not be changed when the subscription is already charged. Field: startDate. 

It happens when i am trying to update a subscription where the first directdebit shows up in the payments.

When i am trying the same with Curl it is working.
Also is it possible to edit the next payment date?

**Comment by sandervanhooft** [comment]
@RyonMB can you try whether `curl` yields the same error when you include the (unchanged) `startDate`?

The php client includes all fields that _can_ be updated in the call, whether they have been changed or not.

> Also is it possible to edit the next payment date?
No, unfortunately not. For this kind of advanced behaviour you'll need to obtain a mandate (via a first payment) and schedule subsequent payments yourself - instead of using the Subscription API.

**Comment by MollieRick** [comment]
Hi @RyonMB,

Did the answer of Sander helped you fixing the error?

**Comment by MollieRick** [comment]
Same problem as #403. I'll close this one.
