### ISSUE TITLE
Improve api_key validation

### ISSUE THREAD

**Issue by a3020** [mollie/mollie-api-php#40]
These checks could be improved:
- https://github.com/mollie/mollie-api-php/blob/master/src/Mollie/API/Client.php#L250
- https://github.com/mollie/mollie-api-php/blob/master/src/Mollie/API/Client.php#L320

If somehow the .env file in a Laravel application isn't loaded correctly, [the default key in the Laravel library remains "test_xxx"](https://github.com/mollie/laravel-mollie/blob/master/config/mollie.php#L38), and that will pass the tests in the Client.php class.

The API will respond with an "Unauthorized request". A better response would be "Invalid API-key", which would be in line with the for example the "The payment id is invalid" [error message](https://www.mollie.com/en/docs/errors).

Note: this is not a bug, but a suggestion.

**Comment by willemstuursma** [comment]
Thanks @a3020
