### ISSUE TITLE
__wakeUp() breaks when extending MollieApiClient class.

### ISSUE THREAD

**Issue by HenriNijborg** [mollie/mollie-api-php#400]
## Specifications

  - API Version: v2.10.0

## Describe the issue

In the MollieApiClient.php the following function causes some trouble:
```
    public function __wakeup()
    {
        $this->__construct();
    }
```

In our case we have an internalclient extending the MollieApiClient and with it's own __construct($param1, $param2, $param3), three params . Whenever the __wakeUp function is called it will throw an error because of the lack of params as $this refers to our internalClient instead of MollieApiClient.php.

It might be better to do the following?
```
    public function __wakeup()
    {
        self::__construct();
    }
```

In our case it will solve the issue.

**Comment by sandervanhooft** [comment]
@willemstuursma Does this cause a BC?

Relates to:

https://github.com/mollie/mollie-api-php/blob/65eb23e49725c13f9453d1c209d240d02add1be7/src/MollieApiClient.php#L509:L519

**Comment by willemstuursma** [comment]
I don't think this causes a BC but I am also not sure it will actually fix it @HenriNijborg. 

To be honest, for best results, you should _not_ serialize the client, not serialize any results and not extend the client (instead encapsulate it). 

I'm not sure there is a solution, can you actually confirm that it will fix it @HenriNijborg ?

**Comment by MollieRick** [comment]
Hi @HenriNijborg,

Do you still have this issue, or can we close it?

**Comment by HenriNijborg** [comment]
The suggestion of encapsulating it got me thinking and we will change it so we will do just that instead of extending the MollieApiCLient. It will no longer be an issue for us. Thx!

**Comment by HenriNijborg** [comment]
One last note, I tried changing it to ```self::__construct();``` and the problem was solved and the client still worked. ```self::__construct()``` will execute the __construct of the MollieApiClient. ```$this->__construct()``` will execute the __construct of MollieApiClient or their **parent** when extending it. We had a different __construct with one more param which is why it broke.
