### ISSUE TITLE
Onboarding API registrationType

### ISSUE THREAD

**Issue by Dennisprins93** [mollie/mollie-api-php#404]
Hi Guys,

I'm trying to build an app with your laravel-mollie package that uses OAuth to connect with the Mollie account of my customer, and I want to submit/fill the onboarding data for my customer through your Onboarding API. 

I'm facing a problem and that is that it's impossible to parse the Registration Type of the organization to the belonging Mollie Account. Whatever field I add to the organization array, (i.e. registrationType, legalForm, etc), it doesn't accept it. I'm not able to complete the onboarding via your API and now i'm still forced to send the customer to his mollie dashboard.

I'm facing this error:
`Error executing API call (422: Unprocessable Entity): Non-existent body parameter "organization.registrationType" for this API call.`

This is my code:

```
$mollie->onboarding()->submit([
                'organization' => [
                    'name' => $company->name,
                    'address' => [
                        'streetAndNumber' => $company->address,
                        'postalCode' => $company->zip,
                        'city' => $company->city,
                        'country' => $company->country
                    ],
                    'registrationType' => 'eenmanszaak',
                    'registrationNumber' => $company->kvk
                ]
            ]);
```
![image](https://user-images.githubusercontent.com/9679179/64078824-fca5ac00-ccdf-11e9-9689-af3c8fdce581.png)

**Comment by MollieRick** [comment]
Hi @Dennisprins93,

The parameter you try to submit (`registrationType`) is not supported (yet) by our API. Therefor you're getting the API error.

See the docs (https://docs.mollie.com/reference/v2/onboarding-api/submit-onboarding-data) for what types of data you can submit.
