### ISSUE TITLE
Settlement.settledDatetime not populated since 02-09-2019

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#406]
## Specifications

  - API Version: v1

## Describe the issue
It seems that as of yesterday 02-09-2019, the `Settlement.settledDatetime` is not populated anymore while:

- the [Changelog](https://docs.mollie.com/changelog/v1/changelog) does not mention this change
- the Mollie dashboard indicates that the `Settlement.status `= `paidout`
- the API indicates `Settlement.status` = `paidout`
- an e-mail from Mollie is sent: "Mollie outpayment September X"
- the money is transferred to our bankaccount

My question: is this on purpose? It broke our workflow, since we check whether a `Settlement` has actually been settled (by checking the `Settlement.settledDatetime` property) before we actually process it...

**Comment by mollierobbert** [comment]
Thanks for reporting this issue, @holtkamp. We will dive into it today. Our apologies for the inconvenience.

**Comment by holtkamp** [comment]
@mollierobbert I think this issue can be closed. Apparently yesterday there was a slight delay in settling the Settlements @ Mollie. Since we cached the response of the API, I was under the impression the Settlement was still not settled. 🤦‍♂

**Comment by mollierobbert** [comment]
Thanks for the response @holtkamp. Happy to hear you were able to resolve it!

Yes, some of the outpayments yesterday experienced a delay due to an issue on our side. Sorry for that as well. 😅

**Comment by willemstuursma** [comment]
@mollierobbert its a bit weird that the status is `paidout` but the `settlementDatetime` remains empty, don't you agree?

**Comment by mollierobbert** [comment]
I agree. @leonardogcsoares is this something we can improve in our Settlements API?

**Comment by holtkamp** [comment]
Hey guys, it seems that for the settlements of 14-10-2019 and 15-10-2019 the ```Settlement.settlementDatetime``` remains unset. Is this on purpose?

**Comment by holtkamp** [comment]
@ndijkstra it seems ```Settlement.settledDatetime ``` is populated again, nice. 

But it seems ```Settlement.settledDatetime ``` is "before" ```Settlement.createdDatetime ```. This is correct?
