### ISSUE TITLE
Status open while webhook call succes and payment has been made

### ISSUE THREAD

**Issue by dna75** [mollie/mollie-api-php#412]
## Specifications

  - API Version: 2.0

## Describe the issue
In some orders the payment is succesfull and also the Webhook was called succesfull but when the user returns to the redirectUrl the status of the payment is open.
this causes confusion for the buyer.
I can't figure out why some payment keep the Open status while the webhook was called succesfully.

**Comment by MollieRick** [comment]
Hi @dna75,

Is the payment open in our system, or in yours?

**Comment by dna75** [comment]
After the payment is made they return to the our website and the status is still open, It looks like the update of the status is changed at another moment because the Paid status is vibisible when I check these payments, looks like the payment status is pending.

**Comment by MollieRick** [comment]
Check! Can you please contact our support-team? They can help you with this problem and take a deeper look into your payments and events.

See https://www.mollie.com/en/contact on how doing this.

Have a great weekend, cheers!

**Comment by dna75** [comment]
I already contacted Mollie but haven't got a response.

**Comment by MollieRick** [comment]
Sorry to hear that, it currently very busy.
You can try to call or chat with us via your Mollie dashboard.
