### ISSUE TITLE
Readme outdated

### ISSUE THREAD

**Issue by willemstuursma** [mollie/mollie-api-php#413]
Some payment methods are missing such as Przelewy24.

Information on refunds is incorrect, refunds are supported for all methods except paysafecard and gift cards. I guess the sentence on support can be omitted.

**Comment by sandervanhooft** [comment]
I've updated the readme. Not sure why you'd like the support section to be removed?

<img width="500" alt="image" src="https://user-images.githubusercontent.com/7265703/72725888-44da4380-3b87-11ea-8ead-cbaee2ad4ace.png">
