### ISSUE TITLE
Mollie API conflicts with Concrete5 Framework

### ISSUE THREAD

**Issue by RobbinRook** [mollie/mollie-api-php#415]
Concrete5 8.5.2 & Concrete5 8.5.1
  - API Version: Latest 

Whenever i include the file:
  include "Mollie/vendor/autoload.php";

To create a new Mollie Api Client: 

 $mollie = new \Mollie\Api\MollieApiClient();

I get this error:
Call to undefined function _PhpScoper5d8cb17438769\GuzzleHttp\choose_handler()
@ /Mollie/vendor/guzzlehttp/guzzle/src/HandlerStack.php : 37

I was hoping that this bug was fixed already, by the amount of bugs reported in the last few years, which are exactly the same as mine. Any chance you guys can help me out? 

Thanks. 
...

**Comment by willemstuursma** [comment]
Hi @RobbinRook. Can't you use `composer` to install the API client in the Concrete5 framework?

**Comment by RobbinRook** [comment]
Hi @willemstuursma ,

What are the benefits from installing the client through composer? And why isn't it working if i manually integrate it with my system? Do you think it is conflicting with the already installed guzzle in Concrete5?

**Comment by willemstuursma** [comment]
I'm not going to go into the details of Composer. If you can use it, you should.

Else, try using the zip of the code (https://github.com/mollie/mollie-api-php/archive/v2.12.0.zip) instead of the pre-build version with PhpScoper.

**Comment by RobbinRook** [comment]
Well this is a ripoff, you're just saying: 'Too bad it isn't working for you, so shame on you'. Your API isn't working, and i am only asking what is gonna change when i'm using Composer. Is that too hard to tell?

**Comment by RobbinRook** [comment]
I nonetheless got it working through Composer, thanks for that!
