### ISSUE TITLE
Testmode is lost when fetching chargeback from payment entity

### ISSUE THREAD

**Issue by williamrijksen** [mollie/mollie-api-php#417]
## Specifications

  - API Version: v2.12.0

## Describe the issue

When fetching payments using 
```
$response = $this->mollieApiClient->payments->get([
            $payment->number,
            [
                     'testmode' => 'test'
            ]
]);
```
And afterwards calling
```
$response-chargebacks();
```

The testmode variable is lost. 
I would prefer to get the `testmode` variable from the response and reuse it for the `chargebacks` call.

**Comment by sandervanhooft** [comment]
It's using the ` _links.chargebacks`.

I suspect this problem occurs in more places (calls made from a retrieved Resource).

I think the best solution would be to have a central testmode flag/switch on the client. That way we can check in each call whether the `testmode` flag should be injected (depending on both `usesOauth` and the new central `testmode` flag).

**Comment by sandervanhooft** [comment]
Would be a significant refactor, but I could put it on my list :)

**Comment by sandervanhooft** [comment]
(Forgot to tag @willemstuursma )

**Comment by sandervanhooft** [comment]
Currently this behaviour is scattered across Resources / methods and error-prone.

**Comment by sandervanhooft** [comment]
Here's the method:

https://github.com/mollie/mollie-api-php/blob/a8540896e069fca409cf18351b33ec10f58622c6/src/Resources/Payment.php#L479:L502

**Comment by bobbybouwmann** [comment]
@sandervanhooft Yeah, this happens on almost all endpoints. Right now I'm working with chargebacks and refunds from payments as well. I have to do the calls myself and pass the test mode flag to the URL instead of using the `$payment->chargebacks()` or `$payment->refunds()` methods. 

Wouldn't it be better if the URLs that are returned from the API already have the `?testmode=true` appended to the URL? This way it would work automatically since the test mode is already requested in the initial request. However, this would also mean a breaking change!

Let me know if I can help in any way! I will dive into a possible, no breaking change, solution as well!

**Comment by willemstuursma** [comment]
@bobbybouwmann Yes, the URLs should have the `?testmode=true` bit included in the URL. We'll solve this in our API.

**Comment by bobbybouwmann** [comment]
@willemstuursma Do you have any ETA of when this will be available?

Also, should we consider this to be a breaking change? If someone is parsing the URL on their own, they might end up with breaking code. 

Thanks for all the great work so far :D

**Comment by willemstuursma** [comment]
@bobbybouwmann I think it will take a few weeks, I have to find some capacity to fix this within our teams. We'll consider the breaking cases.

**Comment by sandervanhooft** [comment]
@willemstuursma any news?

**Comment by willemstuursma** [comment]
Sorry @sandervanhooft, we looked into it but we were not able to figure it out yet.

**Comment by bobbybouwmann** [comment]
@willemstuursma What do you mean by "not able to figure it out"? Do you miss context or do you need a working example?

**Comment by willemstuursma** [comment]
@bobbybouwmann Sorry, the problem was completely clear but it too us a while to figure out a good way to approach the problem. We expect to release it within the week.

**Comment by willemstuursma** [comment]
This should now be fixed, please let us know if it works for you!

**Comment by bobbybouwmann** [comment]
@willemstuursma Thanks! Will give it a go!
