### ISSUE TITLE
Update paid payment - redirectUrl bug

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/mollie-api-php#418]
## Specifications

  - API Version: v2

## Describe the issue

See [comment](https://github.com/mollie/mollie-api-php/pull/405#issuecomment-545877134).

The `redirectUrl` is sent with the update payment payload, regardless of the Payment's status.

The `redirectUrl` however is rejected by the API endpoint if the Payment status is `paid`.

This should be either fixed in the client or the API endpoint.

**Comment by sandervanhooft** [comment]
Dealing with this at the API endpoint would make the best/cleanest integrator experience across all clients IMO.

**Comment by sandervanhooft** [comment]
@willemstuursma, what do you think?

**Comment by willemstuursma** [comment]
What value is sent, `null` or `""`?

**Comment by sandervanhooft** [comment]
Hi @willemstuursma ,

This issue is actually about fetching an existing PAID payment with for example redirectUrl `https://www.example.com`. Then doing this causes an exception:

```php
$payment->description = 'New description';
$payment->update();
```

This is throwing an exception because the redirectUrl is being sent along with the payload. 

Guarding against this behaviour in the client(s) requires complexity to be introduced.

While checking in the API endpoint whether the redirectUrl value was actually changed before throwing an exception would keep things clean.

**Comment by sandervanhooft** [comment]
> This is throwing an exception because the redirectUrl is being sent along with the payload.

More precisely: This is throwing an exception because the redirectUrl is being sent along with the payload and the API endpoint returns an exception response regardless whether the redirectUrl differs from Mollie's records.

**Comment by willemstuursma** [comment]
@sandervanhooft thanks for the clarification, we'll sort it in the back end.

**Comment by sandervanhooft** [comment]
That's great @willemstuursma ! Can you post back here?

**Comment by MollieRick** [comment]
We implemented a fix. Can you confirm it's fixed? :-)

**Comment by sandervanhooft** [comment]
@MollieRick works like a charm!
