### ISSUE TITLE
Handling service unavailable 

### ISSUE THREAD

**Issue by esprange** [mollie/mollie-api-php#419]
## Specifications

  - API Version: 2.0

## Describe the issue

I have noticed the following error:
[28-Oct-2019 13:20:14 UTC] PHP Fatal error:  Uncaught Mollie\Api\Exceptions\ApiException: Unable to decode Mollie response: '<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

'. in /XXXX/vendor/mollie/mollie-api-php/src/MollieApiClient.php:480
Stack trace:
#0 /XXXX/vendor/mollie/mollie-api-php/src/MollieApiClient.php(456): Mollie\Api\MollieApiClient->parseResponseBody(Object(GuzzleHttp\Psr7\Response))
#1 /XXXX/vendor/mollie/mollie-api-php/src/MollieApiClient.php(404): Mollie\Api\MollieApiClient->performHttpCallToFullUrl('GET', 'https://api.mol...', NULL)
#2 /XXXX/vendor/mollie/mollie-api-php/src/Endpoints/EndpointAbstract.php(99): Mollie\Api\MollieApiClient->performHttpCall('GET', 'methods/ideal?i...')
#3 /home/kl in /XXXX/vendor/mollie/mollie-api-php/src/MollieApiClient.php on line 480
[28-Oct-2019 13:21:53 UTC] PHP Fatal error:  Uncaught Mollie\Api\Exceptions\ApiException: cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /XXXX/vendor/mollie/mollie-api-php/src/Exceptions/ApiException.php:80
Stack trace:
#0 /XXXX/vendor/mollie/mollie-api-php/src/MollieApiClient.php(449): Mollie\Api\Exceptions\ApiException::createFromGuzzleException(Object(GuzzleHttp\Exception\ConnectException))
#1 /XXXX/vendor/mollie/mollie-api-php/src/MollieApiClient.php(404): Mollie\Api\MollieApiClient->performHttpCallToFullUrl('GET', 'https://api.mol...', NULL)
#2 /XXXX/vendor/mollie/mollie-api-php/src/Endpoints/EndpointAbstract.php(99): Mollie\Api\MollieApiClient->performHttpCall('GET', 'meth in /XXXX/vendor/mollie/mollie-api-php/src/Exceptions/ApiException.php on line 80
[28-Oct-2019 13:21:53 UTC] PHP Fatal error:  Uncaught Mollie\Api\Exceptions\ApiException: Unable to decode Mollie response: '<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

'. in /XXXX/vendor/mollie/mollie-api-php/src/MollieApiClient.php:480
Stack trace:
#0 /XXXX/vendor/mollie/mollie-api-php/src/MollieApiClient.php(456): Mollie\Api\MollieApiClient->parseResponseBody(Object(GuzzleHttp\Psr7\Response))
#1 /XXXX/vendor/mollie/mollie-api-php/src/MollieApiClient.php(404): Mollie\Api\MollieApiClient->performHttpCallToFullUrl('GET', 'https://api.mol...', NULL)
#2 /XXXX/vendor/mollie/mollie-api-php/src/Endpoints/EndpointAbstract.php(99): Mollie\Api\MollieApiClient->performHttpCall('GET', 'methods/ideal?i...')
#3 /home/kl in /XXXX/vendor/mollie/mollie-api-php/src/MollieApiClient.php on line 480

So it looks that there might be some missing error handling. Any idea how to solve this as I like to inform the customer and suggest to retry the purchase at a later moment.
...

**Comment by ndijkstra** [comment]
Hi @esprange, we had some problems around 2pm. You can find more information on our status page: https://status.mollie.com/
