### ISSUE TITLE
How to disable Paypal shipping?

### ISSUE THREAD

**Issue by arendvw** [mollie/mollie-api-php#42]
When using paypal the user gets an option at the paypal checkout screen to change the shipping address. 

![paypal-shipping](https://cloud.githubusercontent.com/assets/1571317/19777244/97ba797e-9c77-11e6-8b29-902975f694cb.jpg)

Our application handles it's own shipping calculation, so users being able to add shipping information is very confusing. (Especially because it's also hard to get this information back from mollie).  Also, we prefer not to ship to australia for the same price we will ship to europe.

On the mollie side of things - is there any way to disable the shipping method, similar to the NOSHIPPING parameter which can be passed to paypal? (Not quite sure which of the API's mollie is using, but paypal does seem to offer ways to disable shipping)

https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECCustomizing/

**Comment by Thijs-Riezebeek** [comment]
Hi arendvw,

Thank you for opening this issue.

I assume you are adding the shipping information that your customers have entered to the create payment API call. (See https://www.mollie.com/nl/docs/reference/payments/create, 'Payment method specific parameters' and then click PayPal.

I understand from your issue that when you send these parameters, PayPal displays them, but still allows the customer to change them.

Currently we do not support a parameter in our API that will send the `NOSHIPPING` parameter to PayPal and it is not on our roadmap either. So unfortunately we will not be implementing this anytime soon, if at all.

Kind regards,
Thijs Riezebeek

**Comment by Parcye** [comment]
Hi,

So if I understand correctly, not sending the address, will not show the address in PayPal and thus not show the option to change the address? That could be a work around.

I don't have many orders, but two paypal orders have 'gone wrong' in this way in the past. Never thought this could be the cause.

Regards,

**Comment by arendvw** [comment]
Hi Parcye, and Thijs,

thank you for your comments.

> I understand from your issue that when you send these parameters, PayPal displays them, but still allows the customer to change them.

The whole issue is that **not sending the address** will still show an "Ship to" option in paypal, and allow users to modify it. Sending shipping information has no influence on if paypal will show this information.

Paypal will always allow any user to change their shipping information independent on whether the paypal specific parameters were defined or not.

@Thijs-Riezebeek I am not related to parcye

**Comment by Parcye** [comment]
@Thijs-Riezebeek I am just a Mollie watcher and love the API ; starting to implement it for more of my clients and need to stay updated on issues and possible solutions.

**Comment by Thijs-Riezebeek** [comment]
Thank you @arendvw for providing us with some useful insight into how PayPal handles shipping information.

I will discuss this internally, but unfortunately I will have to reiterate that we are unlikely to change this for now.

Thanks again for bringing this to our attention.
