### ISSUE TITLE
Not redirecting to website when payment status is failed in testmode

### ISSUE THREAD

**Issue by sandeep-tlt** [mollie/mollie-api-php#420]
Iam using the mollie payment gateway in test mode. When i choose the payment status as failed its not redirecting to the return url (my website). I can see the redirect works only for the status paid.Also webhook is not being called for failed or expired status.

**Comment by sandervanhooft** [comment]
Hi @sandeep-tlt ,

A few questions:

Can you share the code in which you create the payment?

Did you check that Mollie correctly called your webhook (you can look this up in the Mollie Dashboard)?

Would it be possible for you to send a brief screen recording of the redirect issue?

**Comment by sandeep-tlt** [comment]
Please check the code below.

$protocol = isset($_SERVER['HTTPS']) && strcasecmp('off', $_SERVER['HTTPS']) !== 0 ? "https" : "http";
       $hostname = $_SERVER['HTTP_HOST'];
       $mollie = new MollieApiClient();
       $mollie->setApiKey("test_AAarzqGMPavtwKpsEMMavatqxTxyDn");
       $orderId = time();
       $protocol = isset($_SERVER['HTTPS']) && \strcasecmp('off', $_SERVER['HTTPS']) !== 0 ? "https" : "http";
       $hostname = $_SERVER['HTTP_HOST'];
   
       $payment = $mollie->payments->create([
        "amount" => [
            "currency" => "EUR",
            "value" => "1.00"
        ],
        "description" => "Order #{$orderId}",
        
        "redirectUrl" => "{$protocol}://{$hostname}/payment-return?order_id=$orderId",
        "webhookUrl" => "{$protocol}://{$hostname}/mollie_hook.php",

        "metadata" => [
            "order_id" => $orderId,
        ],
       
    ]);
      
    return $this->redirect($payment->getCheckoutUrl(),303);

**Comment by sandeep-tlt** [comment]
When i choose status other than paid, it redirects back to the mollie payment method selection page.

**Comment by sandervanhooft** [comment]
Just discussed with Mollie support, this (non-)redirect behaviour is by design. It works the same in test mode as in production.

If no payment method is explicitly  configured on the payment, the customer is allowed to pick another payment method / try again. That's also why the webhook is not being called, the status is not definite yet.

**Comment by sandeep-tlt** [comment]
Thanks sandervanhooft. This solved the issue.

**Comment by holtkamp** [comment]
From the top of my head I remember I "read" this behavior somewhere in the documentation... It allows you to really simulate a failure/timeout of the payment...

**Comment by sandervanhooft** [comment]
@holtkamp Be sure to share the link. Can't find it that easily.
