### ISSUE TITLE
Unable to revoke tokens

### ISSUE THREAD

**Issue by jlmmns** [mollie/mollie-api-php#429]
## Specifications

  - API Version: v2

## Describe the issue

First off, in order to send this request we have to manually use `performHttpCall` or `performHttpCallToFullUrl`, since there doesn't seem to be a "tokens" implementation.

Using `performHttpCall`, the package will automatically prepend "v2" to the endpoint, resulting in a `404 Invalid resource endpoint` response.

After checking the API reference, it seems the `/oauth2/tokens` endpoint should be used without the "v2" portion.

So, using `performHttpCallToFullUrl`, to circumvent the "v2" portion, the request seems to go through, but then it fails when parsing the response, giving me the following error:
`Undefined property: stdClass::$status` on line 99 of `/src/Exceptions/ApiException.php`

**Comment by willemstuursma** [comment]
We recommend using https://github.com/mollie/oauth2-mollie-php for OAuth implementations, as that client is completely aimed at OAuth. 

Please let us know if that client is useful.
