### ISSUE TITLE
Exception on cancelling a subscription

### ISSUE THREAD

**Issue by MelvinRook** [mollie/mollie-api-php#430]
Cancelling a subscription results into the following exception:
`Error executing API call (422: Unprocessable Entity): The subscription has been cancelled.`

However, the docs state that I should expect a `200 OK` response with a subscription object. Is this expected behaviour, or should I executed this call in a different way?

There is a similar issue from 2017 (#88), but questions remained unanswered.

**Comment by sandervanhooft** [comment]
Hi @MelvinRook

To be sure, is `$subscription->delete();` triggering this response, or a subsequent call trying to fetch that subscription?

**Comment by MelvinRook** [comment]
Using the API call from the Mollie library. In the end resulting into a REST DELETE command indeed.
```
$customer = $this->mollie->customers->get($user->customer_id);
$customer->cancelSubscription($user->subscription_id);
```

**Comment by sandervanhooft** [comment]
And the `$user->subscription_id` relates to an active subscription?

**Comment by MelvinRook** [comment]
Correct, an active subscription in test mode.

**Comment by sandervanhooft** [comment]
I can't reproduce the problem. I only get the 422 exception only when trying to cancel an already canceled subscription. Not when canceling an active subscription.

**Comment by MollieRick** [comment]
Hi @MelvinRook,

Could it be that the subscription is charged for the last time already?

**Comment by MelvinRook** [comment]
Hi @MollieRick 

Went to check again and finally managed to reproduce the issue. A test subscription is cancelled automatically after some time. There is a small note about this in the docs: https://docs.mollie.com/reference/v2/subscriptions-api/create-subscription `Subscriptions in test mode will be canceled automatically after 10 charges.`

Unsure though if I received a webhook call for that, because the subscription was still active on our end.

Will verify that and open a new issue in case there is an issue. Thanks for all the help. Much appreciated!

**Comment by MollieRick** [comment]
Hi,

Good to hear. Please be aware that we do not call any webhooks for subscriptions. We only send them for payments (e.g. created by the subscriptions) and orders. 

Enjoy the holidays!

**Comment by MelvinRook** [comment]
Check! That answers my last question.

Happy holiday season!
