### ISSUE TITLE
Feature request: update frequency of subscriptions

### ISSUE THREAD

**Issue by Tsjippy** [mollie/mollie-api-php#431]
## Specifications

  - API Version: 2.12.0

## Describe the issue
Sometimes I need to update the frequency of an given subscription, that is not possible at the moment. Can this be added?

**Comment by MollieRick** [comment]
Hi @Tsjippy,

Thank you for your suggestion, it's added it to our backlog. I can not say when and if we gonna implement this but you can be sure that we'll look at it.

**Comment by sandervanhooft** [comment]
Hi @Tsjippy,

Today's release `v2.13.0` supports updating the subscription interval. That should solve your issue.

https://github.com/mollie/mollie-api-php/releases/tag/v2.13.0
