### ISSUE TITLE
[Q] createPayment - Recurring

### ISSUE THREAD

**Issue by dnsBlah** [mollie/mollie-api-php#433]
## Specifications
  - API Version: 2.12.1

## Describe the issue
I'm still in testing round, but when I created a recurring payment I received the message that "The amount is higher than the maximum"
Where is the maximum set? Is this set during the firstpayment?

So, if a customer changes his/her subscription on my service, I need to revoke the mandate and create a new First payment and use the new mandate from then?

**Comment by robindirksen1** [comment]
> I'm still in testing round, but when I created a recurring payment I received the message that "The amount is higher than the maximum"
> Where is the maximum set? Is this set during the firstpayment?

From my experience, you have to contact Mollie support to increase the maximum amount, this is because of the risk for you/your company.

Maybe you can find something here: https://help.mollie.com/hc/en-us/articles/115000972585-What-are-the-risks-of-payments-via-credit-card-

**Comment by dnsBlah** [comment]
Hi Robin,

Thank you so much for your response, so it has nothing to do with the 'intial' payment amount?
As I've just followed the tests within this project with 10 euro, and now trying to take off my normal licenses by recurring which is about 3000.
I will contact mollie about this and discuss with my partner a max. amount of licenses they can take for this recurring payments based on mollie's response.

Thanks again!
