### ISSUE TITLE
Images from issuers

### ISSUE THREAD

**Issue by lode** [mollie/mollie-api-php#44]
Could the issuers endpoint provide images per issuer? Just like they are provided for the payment methods themselves.

**Comment by Thijs-Riezebeek** [comment]
Hi lode,

Thank you for opening this issue and sorry for the late reply!

We have made a note of your request and put it on our backlog. Keep an eye on our [API changelog](https://www.mollie.com/nl/docs/changelog) to find out when this is released.

Kind regards,

Thijs Riezebeek
