### ISSUE TITLE
Can we have a  public function payments() method on the subscription resource?

### ISSUE THREAD

**Issue by ReneBakkerBBIT** [mollie/mollie-api-php#441]
## Specifications

  - API Version: latest

## Describe the issue
The Mollie API is able to retrieve subscription payments, but this package does not (yet?) implement that. Not sure why not.

It is easy to implement: just copy over the public function payments() method from the settlement resouce. It did the trick for me.

Thanks in advance.

**Comment by sandervanhooft** [comment]
Thanks for noticing this @ReneBakkerBBIT. I'll pick it up.

**Comment by sandervanhooft** [comment]
Released: https://github.com/mollie/mollie-api-php/releases/tag/v2.15.0

**Comment by ReneBakkerBBIT** [comment]
Bedankt Sander!

Met vriendelijke groet,
René Bakker


Van: Sander van Hooft <notifications@github.com>
Verzonden: maandag 3 februari 2020 10:56
Aan: mollie/mollie-api-php <mollie-api-php@noreply.github.com>
CC: René Bakker <rb@bbit.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [mollie/mollie-api-php] Can we have a public function payments() method on the subscription resource? (#441)


Released: https://github.com/mollie/mollie-api-php/releases/tag/v2.15.0

**Comment by sandervanhooft** [comment]
Thanks for the ❤️ @ReneBakkerBBIT . I'm removing your message though as it's leaking your email address (downside of replying via mail).
