### ISSUE TITLE
Enabling Apple Pay through the API enables creditcard only

### ISSUE THREAD

**Issue by jarnovanleeuwen** [mollie/mollie-api-php#446]
## Specifications

  - API Version: 2.x

## Describe the issue

Not sure if this is the right place because it is probably an issue with the API itself and not the PHP implementation of it, but...

When enabling the `applepay` payment method on a website profile through the Mollie Connect API (authorized using Hosted Onboarding) it seems that the creditcard payment method gets enabled instead. This has been tested on website profile that has creditcard already enabled. The `createForId('pfl_xxxx', 'applepay')` on the `ProfileMethodEndpoint` returned the `creditcard` payment method and Apple Pay remained disabled while Creditcard remained enabled.

If you need more information, please let me know.

**Comment by willemstuursma** [comment]
Thanks for reporting, we'll have a look and report back here.

**Comment by ndijkstra** [comment]
Hi @jarnovanleeuwen, we've deployed a fix for this and it should now work. Can you give it a try?

**Comment by jarnovanleeuwen** [comment]
Thank you for the quick fix! It works now.
