### ISSUE TITLE
V2.16.0 triggers error in Guzzlehttp (for some)

### ISSUE THREAD

**Issue by StonehengeCreations** [mollie/mollie-api-php#447]
## Specifications

  - API Version:  2.16.0

## Describe the issue
There appears to be a (known) error in Guzzlehttp version 6.5.2. _Some_ end users (not all) get a fatal error "undefined function".  See https://github.com/guzzle/guzzle/issues/2511

The solution is really simple: downgrade to version 6.5.0 of Guzzlehttp to prevent any errors.

Since the Mollie composer will install the latest release (v6.5.2) and that is also included in the manual download, perhaps you might want to change that to using version 6.5.0 explicitly. So no errors will occur for anyone installing or updating Mollie PHP through composer.

FYI: I got complaints from users of my Mollie plugins after upgrading to V2.1.6.0. I did not get the error myself, but downgrading only Guzzlehttp to 6.5.0. solved it for my clients. 
...

**Comment by sandervanhooft** [comment]
Thanks for reporting this, these things can be a pain to figure out.

We'll keep your report on record for future support issues.

But since the issue is in a minor Guzzle release and a patch is in the works the composer dependency will remain unchanged.
