### ISSUE TITLE
orders/return.php not found in example

### ISSUE THREAD

**Issue by straightlight** [mollie/mollie-api-php#453]
## Specifications

  - API Version: 
v2
## Describe the issue
Cannot find the file in the package in: examples/orders/create-order.php file. 

line 59:

```"redirectUrl" => "{$protocol}://{$hostname}{$path}/orders/return.php?order_id={$orderId}",```

What should be the returned page for the orders as an example?
...

**Comment by sandervanhooft** [comment]
The redirectUrl should point to a page in your app. It’s where the customer is sent to after a) completing the payment or b) cancelling it

More info [here](https://docs.mollie.com/payments/overview).

**Comment by straightlight** [comment]
So what it says on the above is that the route is wrong. /orders/return.php does not exist but payments/return.php does exist. In the same file, create-order.php file as the above, we also have the "Ideal" method while other PHP files has:

```\Mollie\Api\Types\PaymentMethod::IDEAL```

This API documentation is a bit confusing on those ends. When sending the results to the webhook without the ideal method for instanc,e, what would be the actual codes aside from the bunch of text paragraphs we need to read so to understand the array keys we need to either submit or receive on those ends?

More information is needed.

**Comment by sandervanhooft** [comment]
I’m trying to help, can you clarify what you are trying to achieve?


About the documentation, note that there is:

- some rudimental example code included with this package. It’s not intended for production, only as a reference. (This issue was opened with a request to clarify the example code.)

- the API documentation and guides on docs.mollie.com, which details the payment/order processing and checkout flow.

**Comment by straightlight** [comment]
I am also noticing in the orders/webhook.php file that $_POST['id'] is used. Where does this posted ID originating from? ...

**Comment by MollieRick** [comment]
Hi @straightlight,

The POST-call with the `id` is coming from our (Mollie) end. We will call your url with that body if you specify a `webhookUrl`on you create request when a status change of the payment occurs.
