### ISSUE TITLE
Testing webhooks

### ISSUE THREAD

**Issue by larsjanssen6** [mollie/mollie-api-php#456]
## Specifications

Currently I'm mocking all webhook response data from Mollie. I want to use the
test api for this.

  - API Version: latest

## Describe the issue

What would be the best way of testing webhooks? I know I can setup something like
ngrok (already did that) but I'm not in control when a webhook is called. Let's say I want to test the following responses from the webhook:

```
paid
expired
failed
canceled
```

How should I do this without mocking, what is best practice here? I know for example that stripe has a CLI for this.

**Comment by sandervanhooft** [comment]
You can actually easily perform your own test webhook call. It’s a simple POST call with the payment ID in the payload.

**Comment by larsjanssen6** [comment]
@sandervanhooft oops did not thought of that yet haha 😅

**Comment by sandervanhooft** [comment]
No problem, enjoy!

**Comment by larsjanssen6** [comment]
@sandervanhooft  1 more question :) how do I test `chargebacks` ? In the documentation I read this:

> For paid test mode payments the resource will also include the `changePaymentState` URL which allows you to create a refund or chargeback for that payment directly from our hosted payment page. This can be used to test refund and chargeback functionality.

But when I try that I only see 2 options:

![options](https://i.ibb.co/hX2RMkD/Schermafbeelding-2020-05-05-om-13-34-08.png)


I cannot select `Chargeback` any idea if there is a work around?  A chargeback can have multiple failing reasons for example `MD06 ` (stornering). Is it possible to test this aswel ?


Thanks for helping 👍

**Comment by sandervanhooft** [comment]
You’ll have to use the Chargeback API for this. A `chargeback` is not a payment state.

**Comment by larsjanssen6** [comment]
@sandervanhooft that makes sense, when I check the [chargeback API  ](https://docs.mollie.com/reference/v2/chargebacks-api), I'm not seeing any functionality for creating a chargeback only for fetching 🤔 .  Any idea how I can create a chargeback in my test account?

**Comment by sandervanhooft** [comment]
Oh sorry, no you can’t. The only way I can think of would be to mock the Payment resource

**Comment by larsjanssen6** [comment]
Thanks

**Comment by sandervanhooft** [comment]
Hm, this is what the testing guide tells us:

![image](https://user-images.githubusercontent.com/7265703/81065594-0cfbcf80-8edc-11ea-96a8-43d7a44e3cfd.jpeg)

**Comment by sandervanhooft** [comment]
I’ll check with support

**Comment by sandervanhooft** [comment]
Are you sure you're using the changePaymentState url after marking the payment as paid using the checkout url? If so, can you share the payload you're using to create the payment, as well as the payment id?

It does show the chargeback / refund options in my case.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/7265703/81066129-ee4a0880-8edc-11ea-95e5-340cecad72ab.png">

**Comment by larsjanssen6** [comment]
I only see this when I visit the `changePaymentState url` with a `SEPA pending incasso`:



![](https://i.ibb.co/Njvssrm/Schermafbeelding-2020-05-05-om-14-57-07.png)
 
But that ^ is status `Mislukt` I need to fake a `Chargeback` (BTW weird that `Mislukt` is dutch and `Chargeback` english).  

When I visit a `changePaymentState url` for a `PAID payment` (`tr_jBz2SSEW3w`) I only see: `Volledige terugbetaling aanmaken`.

**Comment by larsjanssen6** [comment]
Maybe because I use `sequence type first`. Let me check.

**Comment by larsjanssen6** [comment]
Does not matter still only see `Volledige terugbetaling aanmaken` when I use for example sequence type `SequenceType::SEQUENCETYPE_ONEOFF`.

**Comment by MollieRick** [comment]
Hi @larsjanssen6,

I see the option `Volledige terugboeking aanmaken` in test mode after setting the payment to `paid`. Please try to create a customer with a first payment and then a `recurring` one. Can you try if it works then for you?

![image](https://user-images.githubusercontent.com/42934521/85863688-cdf34780-b7c3-11ea-9623-aa431f2e8dfa.png)
