### ISSUE TITLE
Cannot test Testmode payments that uses OAuth

### ISSUE THREAD

**Issue by Runonstof** [mollie/mollie-api-php#457]
## Specifications

  - API Version: latest

## Describe the issue
**What happens?**
1. I create a payment in testmode, this is an OAuth payment, I specifically passed testmode=true
2. I set the status  to paid
3. My webhook dummy test url wants to get the payment, but it gives the error below

![image](https://user-images.githubusercontent.com/36049776/81570356-c78a4700-93a0-11ea-846b-35ede64a7428.png)

**What I have tried**
 - On the Mollie dashboard checking if its a testmode payment (it is)
 - Checking if I used the test api key (Yes It does)

**What id expect**
That im able to retrieve testmode payments with the test API key active

**Conclusion**
So Its using the test API key and on created of the payment I specifically passed testmode=true.
And it still says I should switch mode.

Do I need to call an extra method on the API indicating it should be testmode?

I can't really test things in live mode

**Comment by sandervanhooft** [comment]
When fetching the payment, are you passing the testmode setting as well?

**Comment by Runonstof** [comment]
Ohmygod you're right, I didnt knew you had to pass a array as second argument with testmode => true.

this is why i'm still a Junior

Thanks! It works now, my boss should be happy
