### ISSUE TITLE
Error with a dependency on composer require

### ISSUE THREAD

**Issue by SebHoremans** [mollie/mollie-api-php#461]
## Specifications

  - API Version: 2.17.1

## Describe the issue
When doing the composer require command I receive an error : 
composer require mollie/mollie-api-php:^2.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Package operations: 4 installs, 0 updates, 0 removals
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.5.3): Loading from cache
  - Installing composer/ca-bundle (1.2.7): Loading from cache
  - Installing mollie/mollie-api-php (2.17.1): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
Symfony operations: 1 recipe (7819c009da3d85e2d9c426d356e65181)
  - Configuring composer/ca-bundle (>=1.2.7): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  Symfony\Component\ErrorHandler\Error\UndefinedMethodError {#46
!!    #message: "Attempted to call an undefined method named "getName" of class "Composer\CaBundle\CaBundle"."
!!    #code: 0
!!    #file: "./vendor/symfony/http-kernel/Kernel.php"
!!    #line: 370
!!    trace: {
!!      ./vendor/symfony/http-kernel/Kernel.php:370 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:123 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
!!      ./vendor/symfony/console/Application.php:140 { …}
!!      ./bin/console:42 {
!!        › $application = new Application($kernel);
!!        › $application->run($input);
!!        › 
!!      }
!!    }
!!  }
!!  2020-05-22T10:59:46+02:00 [critical] Uncaught Error: Call to undefined method Composer\CaBundle\CaBundle::getName()
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json to its original content.

...

**Comment by sandervanhooft** [comment]
Seems like an issue with Symfony, triggered when running the post-install scripts (in this case `cache:clear`.

**Comment by sandervanhooft** [comment]
/ issue with CABundle. It’s not caused by tuis package.
