### ISSUE TITLE
Redeclare issue in the package

### ISSUE THREAD

**Issue by nicholean** [mollie/mollie-api-php#462]
## Specifications
I'm trying to integrate Mollie into my PHP site.

  - API Version: Latest version

## Describe the issue
I've followed the guide to download release zip, extract and place the entire folder (mollie-api-php) on public_html directory. I created a page for checkout including vendor/autoload.php , but if prompt me these errors after I hitting the url directly.

Fatal error: Cannot redeclare _PhpScoper5ec23d31ce65e\mb_ord() (previously declared in /public_html/mollie-api-php/vendor/symfony/polyfill-mbstring/bootstrap.php:219) in /public_html/mollie-api-php/vendor/symfony/polyfill-php72/bootstrap.php on line 63

What I understand is there are duplicates function declaration in both files above. After trying to access mollie-api-php/example/payments/create-payment.php , still the same error.
...

**Comment by sandervanhooft** [comment]
Hi @nicholean ,

Do you have the option of installing the package into your Symfony project using composer?

**Comment by ajmwegman** [comment]
Hi Sander, 
I Have the same issue with package 2.18. I don't use composer, just uploaded the files, changed the API key,

**Comment by ajmwegman** [comment]
Moved on to another payment provider, no luck with git, no luck with support mail, Mollie is not responding to any questions. Installed it, We where active next day.... You have to do something with your support desk Mollie!

**Comment by sandervanhooft** [comment]
Thanks for the feedback @ajmwegman and congratulations on going live!

Scoper issues tend to be complex to tackle and scoper-based solutions like these tend to be brittle. That’s why I recommend to switch to composer if you can.

I’m closing this issue for now, @nicholean let me know if it should be reopened.

**Comment by chriscollins405** [comment]
Same issue here. Rolling out across 2 servers, one on php 7.3 the other on 7.1

The 7.1 server uses the 7.2 polyfill, and this is where the redeclare issue happens.

WSOD, entire site down.

The only workaround I found was to open.....

**/vendor/symfony/polyfill-php72/bootstrap.php**

And comment out the following functions....

```
if (!\function_exists('mb_ord')) {
    // function mb_ord($s, $enc = null)
    // {
        // return \_PhpScoper5ed105407e8f2\Symfony\Polyfill\Php72\Php72::mb_ord($s, $enc);
    // }
}
if (!\function_exists('mb_chr')) {
    // function mb_chr($code, $enc = null)
    // {
        // return \_PhpScoper5ed105407e8f2\Symfony\Polyfill\Php72\Php72::mb_chr($code, $enc);
    // }
}
if (!\function_exists('mb_scrub')) {
    // function mb_scrub($s, $enc = null)
    // {
        // $enc = null === $enc ? \mb_internal_encoding() : $enc;
        // return \mb_convert_encoding($s, $enc, $enc);
    // }
}
```
