### ISSUE TITLE
Payment description truncated in Mollie test Backend

### ISSUE THREAD

**Issue by rodekker** [mollie/mollie-api-php#468]
## Specifications

  - API Version: 2.18

## Describe the issue

I'm using iDEAL in my test environment and ever since the iDEAL Qrcode is part of the test-payment environment, my **long description** is truncated to 35 chars. And this is exactly the maximum length the iDEAL QR specifications specifies. As long as the payment is 'Open' the backend shows the long description and also querying the payment from my server gives back the long description. But as soon as I pay and the status becomes 'Paid', the description is truncated to 35 chars in the backend and also the query gives back the truncated description.

No matter what, I would expect the backend to always show me the long description

**Comment by sandervanhooft** [comment]
@willemstuursma do you recognize this truncating behavior?

**Comment by willemstuursma** [comment]
Yes. We'll have a fix out end of next week.

**Comment by feyyazesat** [comment]
@sandervanhooft this should be fixed. Could you please verify the behavior?

**Comment by rodekker** [comment]
Thx guys. I did test it and the Mollie test backend now shows the long description.
