### ISSUE TITLE
Add ability to revoke mandates

### ISSUE THREAD

**Issue by cascer1** [mollie/mollie-api-php#47]
I would like to be able to revoke customer mandates using this tool, instead of having to resort to using cURL.

**Comment by Thijs-Riezebeek** [comment]
Hi cascer1,

This is already possible with our mollie-api-php client. See the following example:

```php
$mollie->customers_mandates->withParentId("cst_D9hGvKCKGu")->delete("mdt_PHGSjF4nNd"));
```

Just pass the customer ID to the `withParentId` function and the mandate ID to the `delete` function and the customer mandate will be deleted ;)

**Comment by cascer1** [comment]
You guys may want to update the documentation then! https://www.mollie.com/en/docs/reference/mandates/delete

**Comment by Thijs-Riezebeek** [comment]
Thank you for pointing that out, cascer1!

I have passed this on and we will update the documentation.
