### ISSUE TITLE
Increase cURL timeout

### ISSUE THREAD

**Issue by xqsit94** [mollie/mollie-api-php#470]
## Specifications

  - API Version: v2

## Describe the issue

I get this following error due to timeout of 10 seconds

![2020-07-08_19-45](https://user-images.githubusercontent.com/20275754/86929673-b9179c00-c153-11ea-8224-e6e7d534b307.png)

`cURL error 28: Resolving timed out after 10000 milliseconds`

![2020-07-08_19-42](https://user-images.githubusercontent.com/20275754/86929173-2d057480-c153-11ea-84af-8fb3a0557482.png)

Increase the curl timeout to at-least 20 - 30 seconds which is added in this PR #291

**Comment by sandervanhooft** [comment]
The timeout is currently 10 seconds, which should be long enough. What are you trying to do?

If you really need a longer timeout, you can inject a customized Guzzle client into the MollieApiClient.

**Comment by xqsit94** [comment]
Every single api takes more than 10s to respond you can see it in attached screenshot. How could you say it is long enough? Server response time is not same across the world.

**Comment by sandervanhooft** [comment]
I understand.

As a default setting, the 10s is fine. Further increasing the timeout may cause issues in other integrations. Also note that Mollie is only available to European merchants, and for legal reasons (GDPR) their servers generally need to be in Europe.

Again, if you need a longer timeout, you can inject a customized Guzzle client into the MollieApiClient constructor:

```php
$timeout = 20; // or 30, whatever you need

$guzzleClient = new Client([
                \GuzzleHttp\RequestOptions::VERIFY => \Composer\CaBundle\CaBundle::getBundledCaBundlePath(),
                \GuzzleHttp\RequestOptions::TIMEOUT => $timeout,
            ]);

$mollie = new MollieApiClient($guzzleClient);
$mollie->setApiKey(/*...*/);

// Ready to go
$mollie->payments->page();
```

**Comment by willemstuursma** [comment]
Hi @xqsit94. Can you let me know where in the world you are operating from?

**Comment by xqsit94** [comment]
@sandervanhooft Thanks for your response. I injected that already, I'm working for an European client the response time of server is 15+ seconds here and @willemstuursma I'm operating from India.

**Comment by holtkamp** [comment]
Note that this reminds me of https://github.com/mollie/mollie-api-php/issues/414

**Comment by willemstuursma** [comment]
Thanks @xqsit94. That's an insane slowness.

Can you post a traceroute here: 
```
traceroute api.mollie.com
```

Maybe that will clear up where this slowness is coming from.
