### ISSUE TITLE
sequenceType "first:" The amount contains an invalid value Field: amount.value.

### ISSUE THREAD

**Issue by CodeAdraas** [mollie/mollie-api-php#477]
## Specifications

  - API Version: 2.0

## Describe the issue
When I'm trying to start a "first recurring payment" with "00.01" as price, it gives me this error. I think the API can't distinguish regular payments from _first sequence_ payments.

**Comment by sandervanhooft** [comment]
There's a preceding `0` too many. Should be `"0.01"` instead of `"00.01"`
