### ISSUE TITLE
Uncaught Error: Cannot use object of type Mollie\Api\Resources\Customer as array in...

### ISSUE THREAD

**Issue by CodeAdraas** [mollie/mollie-api-php#478]
## Specifications

  - API Version: 2.0

## Describe the issue
When I'm trying to use things like a fetched payment status or payment id, I can't use them in arrays. Even when defining it in a variable:
Uncaught Error: Cannot use object of type Mollie\Api\Resources\Customer as array in....
I'm kinda stuck here...

**Comment by sandervanhooft** [comment]
Can you share a code sample that is triggering his behaviour?

**Comment by CodeAdraas** [comment]
**my API 'add-mandate' endpoint**

```
$customer = self::$App->sanitize(self::payload(), ["id"], ["id"]);
if(!$customer) self::$Response::http(["code" => 400, "die" => true]);

$created_at = self::$Date::currDate(true);
$ngrok = "https://83cea64d6d8a.ngrok.io";
$mollie = self::mollie();

$customer = $mollie->customers->get($customer["id"]);

$payment = $customer->createPayment([
    "amount" => [
        "value" => "0.01",
        "currency" => "EUR"
    ],
    "description" => "Autorisatie / Eerste betaling",
    "redirectUrl" => "{$ngrok}/app/dashboard",
    "webhookUrl" => "{$ngrok}/klant/v1/payments/status",
    "sequenceType" => \Mollie\Api\Types\SequenceType::SEQUENCETYPE_FIRST
]);
```

**^ all goes well**

```
$addPayment = self::$SQL->query([
    "sql" => "INSERT INTO payments ( payment_id, customer_id, status, created_at) VALUES (?, ?, ?, ?)",
    "binds" => [$payment->id, $customer["id"], $payment->status, $created_at],  
    "options" => [
        "close" => true
    ]
]);
```
**^ the error in my script is pointing at the $payment properties I'm trying to insert into my binds array, however in my status webhook that is similar, I _can_ actually use payment object properties in my binds array. But I do must note that I use payments->get method in my status webhook** 

Btw, just that you know, this is my own sort of API framwork so don't worry!
