### ISSUE TITLE
Problem to connect to different bank-apps from webview. Only ING gives no error.

### ISSUE THREAD

**Issue by KeithHurry** [mollie/mollie-api-php#479]
## Specifications

  - API Version: 

## Describe the issue

Bij bijvoorbeeld koppeling richting RABO-app krijgen we:
Webpagina niet beschikbaar
De webpagina op nl.rabobank.ideal://ideal-payment?trxid=20003336503587&random=ae127f12f05ab2cc97d64e71bf519a254a7ce6d8914cbc6580b3afb7a3b25ac2 kan niet worden geladen vanwege het volgende:
net::ERR_UNKNOWN_URL_SCHEME

Met de ING-app werkt het wel.

**Comment by sandervanhooft** [comment]
@KeithHurry thanks for opening this ticket.

What OS (version) and browser (version) are you using?

**Comment by MollieRick** [comment]
Hi @KeithHurry , Thanks for your feedback!

Do you try to open the the bank app from **inside** your app? This is not possible in most of the situation due to security. Please follow our guide here: https://docs.mollie.com/mobile-apps/getting-started-payments

**Comment by KeithHurry** [comment]
> @KeithHurry thanks for opening this ticket.
> 
> What OS (version) and browser (version) are you using?

OS: Android  10
Browser: Google Chrome versie 84.0.4147.89

**Comment by KeithHurry** [comment]
> Hi @KeithHurry , Thanks for your feedback!
> 
> Do you try to open the the bank app from **inside** your app? This is not possible in most of the situation due to security. Please follow our guide here: https://docs.mollie.com/mobile-apps/getting-started-payments

Yes, we try to open from "inside" our app. It looks like we have to use a different url_scheme for each bank. But we cannot find the different URLS. As mentioned with ING it is working, but for Rabobank and SNS for example we get the errormessage.

**Comment by MollieRick** [comment]
@KeithHurry You should open the checkout URL in the native browser of the phone, not inside the app.
I'll close this issue since this is out of our scope.
