### ISSUE TITLE
Releases don't include the composer-loaded things

### ISSUE THREAD

**Issue by Healyhatman** [mollie/mollie-api-php#480]
The readme state that the files in the releases page include everything for those of us unable to use composer, but as of 3 releases ago they don't include everything.  No vendor folder.

**Comment by sandervanhooft** [comment]
Confirmed.

@willemstuursma did anything change on the repo settings / build? (not at my end)

**Comment by sandervanhooft** [comment]
The issue lies with the Travis build. Will need to investigate further.

**Comment by sandervanhooft** [comment]
@willemstuursma The vendor-included build is failing on Travis due to bad GitHub credentials. See for example this [build](https://travis-ci.org/github/mollie/mollie-api-php/jobs/713007777).

Can you check these credentials?

**Comment by Noordkust-nikolai** [comment]
Any updates on this?? :) I am still waiting for mollie's response now on this subject.. after a week.. with the missing autoloader being the main problem..

**Comment by sandervanhooft** [comment]
We're looking into this @Noordkust-nikolai . If you're looking for a quick fix, take a look at the makefile. You can try and run these commands to build the autoload directory locally:

https://github.com/mollie/mollie-api-php/blob/df60ebfc2463cdffc1faeb1fa9419911812ac6f8/Makefile#L6:L22

**Comment by Noordkust-nikolai** [comment]
@sandervanhooft ok ok! thanks! I'll take a look into that :)

**Comment by willemstuursma** [comment]
> @willemstuursma The vendor-included build is failing on Travis due to bad GitHub credentials. See for example this [build](https://travis-ci.org/github/mollie/mollie-api-php/jobs/713007777).
> 
> Can you check these credentials?

I've updated the credentials.

**Comment by sandervanhooft** [comment]
Just released [v2.22.1](https://github.com/mollie/mollie-api-php/releases/tag/v2.22.1) to fix this issue.

Thanks all!

**Comment by Noordkust-nikolai** [comment]
I'm getting this from the vendor, PHP version 5.6.40. 
[Thu Aug 20 12:49:33.198978 2020] [:error] [pid 15015] [client 85.241.130.64:50426] PHP Parse error:  syntax error, unexpected ':', expecting '{' in ...../public_html/new-admin/vendor/guzzlehttp/guzzle/src/functions.php on line 14

**Comment by sandervanhooft** [comment]
You may be right. I am suspecting a Guzzle version is used that does not support your php version (5.6).

@Noordkust-nikolai can you share what's on line 14 of `/public_html/new-admin/vendor/guzzlehttp/guzzle/src/functions.php`?

**Comment by Noordkust-nikolai** [comment]
@sandervanhooft 
function describe_type($input) : string

**Comment by sandervanhooft** [comment]
then the Guzzle version is definitely the issue in combination with php 5.6. Any chance you can upgrade your php version to 7.2? @Noordkust-nikolai

**Comment by Noordkust-nikolai** [comment]
@sandervanhooft unfortunately not..

**Comment by sandervanhooft** [comment]
Can you try on your php 5.6 system:

- cloning this package from repo
- running `make mollie-api-php.zip` from the package root?

**Comment by Noordkust-nikolai** [comment]
The old website is still in place and the new one in a subdirectory. So I would prefer not to have any interference with it..
How do I run that code? Make mollie-api-php.zip? And won't that have the same problem with the php versions of guzzle?

**Comment by sandervanhooft** [comment]
you can create another temporary directory for this test, clone the package there and run `make mollie-api-php.zip` from within the downloaded package directory.

Note that this requires a commandline (Linux/Mac), and `composer` globally available from the commandline (this is a typical webserver setup).

Running the makefile will pull in the dependencies that work for your setup, or notify you that it cannot be done.

**Comment by sandervanhooft** [comment]
Hi @Noordkust-nikolai et al,

Can you give [the latest release](https://github.com/mollie/mollie-api-php/releases/tag/v2.22.3) a try?
