### ISSUE TITLE
guzzlehttp/guzzle version ^7.0 support

### ISSUE THREAD

**Issue by m-bosch** [mollie/mollie-api-php#481]
Serveral packages in our Laravel project are up-to-date and demanding  `"guzzlehttp/guzzle": "^7.0"`

Because of that we cant install `mollie/laravel-mollie`. This `mollie/laravel-mollie` requires this package (`mollie/mollie-api-php`).

This package demands guzzlehttp version `"guzzlehttp/guzzle": "^6.3"`

conclusion, we cant use the Laravel and/or mollie-api-php package because of the non-support of guzzlehttp/guzzle 7....
...

**Comment by sandervanhooft** [comment]
Thanks for bringing this to our attention. I'll whip up a PR.

**Comment by sandervanhooft** [comment]
[Guzzle upgrade guide](https://github.com/guzzle/guzzle/blob/7.0.0/UPGRADING.md#60-to-70)
