### ISSUE TITLE
payment return

### ISSUE THREAD

**Issue by simplyniceweb** [mollie/mollie-api-php#483]
## Specifications

  - API Version: 2.0

## Describe the issue

How can i retrieve the ID from the successful payment created? i can only get $payment->getCheckoutUrl(); but is it also possible to $payment->getPaymentId() or something? because i'm managing multiple company which i need to separate the payment id of each company payments.
...

**Comment by sandervanhooft** [comment]
See the [Payment](https://github.com/mollie/mollie-api-php/blob/master/src/Resources/Payment.php) resource for the complete set of available methods and attributes.
