### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by herve-02** [mollie/mollie-api-php#487]
## Specifications

version 2.22.1
php 7.0.33

## Describe the issue
```php
include($_dir_data.'vendor/autoload.php');
$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setApiKey("test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM");
```
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/herve/www/flog_new/ief/data/mollie_13678/guzzlehttp/guzzle/src/Client.php on line 173

   173 ->  public function getConfig(?string $option = null)

...

**Comment by herve-02** [comment]
version 2.22.1
php5  5.6.7
```php
include($_dir_data.'vendor/autoload.php');
$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setApiKey("test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM");
```
Parse error: syntax error, unexpected ':', expecting '{' in /var/www/blog/ief/data/mollie_13678/guzzlehttp/guzzle/src/functions.php on line 14

14 -> unction describe_type($input) : string

**Comment by sandervanhooft** [comment]
Hi,

Can you give [the latest release](https://github.com/mollie/mollie-api-php/releases/tag/v2.22.3) a try?

**Comment by herve-02** [comment]
works on both case :-)
thanks

**Comment by sandervanhooft** [comment]
No problem, enjoy! 🎉
