### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by spee** [mollie/mollie-api-php#490]
## Specifications

As soon as I try to fetch an order, I hit this memory error:

```
<b>Fatal error</b>: Allowed memory size of 134217728 bytes exhausted (tried to allocate 125833216 bytes) in [...]
```
  - API Version: v2.22.3

## Describe the issue

In my webhook, I instantiate a Mollie client and try to fetch an order:

```php
$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setApiKey($this->apiKey());
$mollie->orders->get('123', array('testmode' => true));
```

If I increase the allowed memory size (default at 128M), even up to 3G, I always hit this error; it seems like a leak that just fills up infinite memory. Any tips how to debug this? Should I try an older version of the PHP API?

**Comment by spee** [comment]
Sorry, I found the problem lies elsewhere in the code. I'm able to get the order just fine.

**Comment by sandervanhooft** [comment]
Thanks for following up, glad you fixed it. Enjoy! 🚀
