### ISSUE TITLE
How to set limit at settlement API

### ISSUE THREAD

**Issue by danielschweiger** [mollie/mollie-api-php#493]
`$payments = $mollie->settlements->get('ref')->payments();`

how can I use page() here? I want to ask for 250 items.

**Comment by kbemvindo** [comment]
https://github.com/mollie/mollie-api-php/issues/493#issue-700312710

**Comment by sandervanhooft** [comment]
> `$payments = $mollie->settlements->get('ref')->payments();`

@MollieRick is this a paginated response? (I don't have settlements in my test account)

**Comment by MollieRick** [comment]
> @MollieRick is this a paginated response? (I don't have settlements in my test account)

Nope! Only our `LIST` endpoints are paginated. :)

**Comment by willemstuursma** [comment]
@MollieRick this is not an embed or include, it is a separate API call.

@sandervanhooft [List Settlement Payments API](https://docs.mollie.com/reference/v2/settlements-api/list-settlement-payments) supports the `limit` parameter. How must it be passed to the `->payments()` call?

**Comment by MollieRick** [comment]
Wauw, sorry. I also missed it.

**Comment by sandervanhooft** [comment]
Solved in [latest release](https://github.com/mollie/mollie-api-php/releases/tag/v2.23.0).

Thanks for reporting this @danielschweiger

**Comment by sandervanhooft** [comment]
@MollieRick since we both glanced over this tiny little detail, perhaps it makes sense to just inline the parameters instead of referring to the payments endpoint?
