### ISSUE TITLE
/payments/ twice in URL's

### ISSUE THREAD

**Issue by JatGitHub** [mollie/mollie-api-php#494]
## Specifications

  - API Version: 2.0

## Describe the issue

...

When using the examples, I get constantly the error URL ..../payments/payments/..... not found.
It seems the /payments/ in the code should be deleted.
Am I the only one having this issue?

Example:
create-payments redirectURL = ...... /payments/return.php
When activated, the redirect is to .../payments/payments/return.php, as the file itself is in the folder payments.

**Comment by sandervanhooft** [comment]
You may be right:

https://github.com/mollie/mollie-api-php/blob/cf3b7a3259e9dd502014dc6a4f446b2f82b6429a/examples/payments/create-payment.php#L25-L41

**Comment by WouS95** [comment]
This still seems to be the case and it has been a few months, is this a mistake in the code or am I missing something?

**Comment by sandervanhooft** [comment]
Now fixed on master
