### ISSUE TITLE
Re-pay the transaction after a failed one

### ISSUE THREAD

**Issue by yooouuri** [mollie/mollie-api-php#50]
I could not find anything about it, sorry if it is there.

When a payment fails, what is the best way to start a new payment? I am asking this because the payment will be not completed at the mollie systems..

So start a new payment or use the payment ID and re-pay?

**Comment by cascer1** [comment]
I believe a customer can continue attempting to pay a transaction using any available method as long as none of them went through. As soon as a payment is completed (regardless of later status changes) it cannot be paid again. 

So basically, so long as the transaction did not receive a payment (and as such, its status is open), you can direct customers there to pay. As soon as the transaction status is anything other than open, it cannot be paid. 

[this documentation might help](https://www.mollie.com/en/docs/status)

> I am asking this because the payment will be not completed at the mollie systems..

I'm not sure what this means :(

**Comment by FaaPz** [comment]
Hi @yooouuri, the best option is indeed to start a new payment and don't forget to mark the other payment in your own system with the status the Mollie webhook gave you to stay in sync.

As @cascer1 mentioned, the documentation might help. Have another look at the [different expiry times for each payment method](https://www.mollie.com/en/docs/status#expiry-times-per-payment-method) if that's the main reason for your failing payments.
