### ISSUE TITLE
 Call to undefined function stream_for

### ISSUE THREAD

**Issue by gtraxx** [mollie/mollie-api-php#500]
## Specifications

  - API Version: 2.23
  - php 7.1.33

## Describe the issue
Hello after testing the API, I have a fatal error (not using Composer)

**( ! ) Fatal error: Uncaught Error: Call to undefined function _PhpScoper5f636c07d0f55\GuzzleHttp\Psr7\stream_for() in C:\wamp\www\project\plugins\mollie\mollie-api-php\vendor\guzzlehttp\psr7\src\Request.php on line 42**

with the code test  
```php
$payment = $this->mollie->payments->create([
                    "amount" => [
                        "currency" => "EUR",
                        "value" => "10.00" // You must send the correct number of decimals, thus we enforce the use of strings
                    ],
                    "description" => "Order #test",
                    "redirectUrl" => "https://www.project.test/fr/mollie/",
                    "webhookUrl" => "https://www.project.test/fr/mollie/",
                    "metadata" => [
                        "order_id" => 'test order',
                    ],
                ]);


```

**Comment by sandervanhooft** [comment]
Seems to be related to #244

**Comment by sandervanhooft** [comment]
@willemstuursma any ideas on how to approach this?

**Comment by gtraxx** [comment]
Hi, I thought it was fixed in this version, I installed with composer while waiting :)

**Comment by sandervanhooft** [comment]
Ok, so you have a workaround now?

**Comment by gtraxx** [comment]
yes, by recompiling with composer
