### ISSUE TITLE
ApplicationFee is not correct in Payment resource

### ISSUE THREAD

**Issue by bkaskes** [mollie/mollie-api-php#501]
## Specifications

  - API Version: 2.22.3

## Describe the issue

Code uses `applicationFeeAmount`, this should be `applicationFee` according to the API spec. The value can be obtained with `$this->applicationFee->amount->value`. Also the comments are not correct.

```
    /**
     * The total amount that is already captured for this payment. Only available
     * when this payment supports captures.
     * 
     * @return float
     */
    public function getApplicationFeeAmount()
    {
        if ($this->applicationFeeAmount) {
            return (float)$this->applicationFeeAmount->value;
        }

        return 0.0;
    }
```

**Comment by sandervanhooft** [comment]
Thanks @bkaskes , we'll look into this

**Comment by sandervanhooft** [comment]
It's now fixed on the `master` branch, will go out with the next release.
