### ISSUE TITLE
QR code with Bancontact

### ISSUE THREAD

**Issue by TimBiesmans** [mollie/mollie-api-php#508]
The Get Payment page makes it seem as if requesting an already existing payment with Bancontact (initialized with the include=details.qrCode param) would include the QR code, but once you have created a payment with a QR code, there is no way to retrieve it again from the API. The details-object is empty

**Comment by MollieRick** [comment]
@sandervanhooft Can you check this?

**Comment by Shnilj** [comment]
@sandervanhooft +1

**Comment by sandervanhooft** [comment]
> The Get Payment page makes it seem as if requesting an already existing payment with Bancontact (initialized with the include=details.qrCode param) would include the QR code, but once you have created a payment with a QR code, there is no way to retrieve it again from the API. The details-object is empty

@TimBiesmans In testmode, only `ideal` is supported for QR codes. Are you experiencing the same with `ideal` in testmode, and/or `bancontact` in production?

**Comment by sandervanhooft** [comment]
https://docs.mollie.com/guides/qr-codes

<img width="733" alt="image" src="https://user-images.githubusercontent.com/7265703/105702719-7c9f6800-5f0c-11eb-9292-321d876a175d.png">

**Comment by TimBiesmans** [comment]
Even in production it isn’t returning a QR code for Bancontact.

I’m using the API. Perhaps hardcoded it will work.

**Comment by sandervanhooft** [comment]
Thanks for checking this. I'll check if I can reproduce the issue using this package

**Comment by sandervanhooft** [comment]
I am able to create an `ideal` payment and see that the details are filled out ok in `testmode`.

These details are dynamically assigned from the API response, so if the information is present in the response it should be included in the details object.

Unfortunately however I have no means to test `bancontact` in production. Can you check your API response using something like Postman?

**Comment by powolnymarcel** [comment]
No news regarding this issue ?

**Comment by sandervanhooft** [comment]
@powolnymarcel what have you tried so far? Please include code samples so we can reproduce the problem.

**Comment by Yame-** [comment]
We want to implement a Bancontact QR code in our app but ran into this issue as well.  

When running with test API key, and using iDeal as a method, we get return with QR code inside of the details. 
But whenever we do this with a live API key, and using Bancontact as a method we don't get anything in side of the details. 

Using the following code: 
`$payment = \Mollie\Laravel\Facades\Mollie::api()->payments()->create([
        "amount" => [
            "currency" => "EUR",
            "value" => "10.00"
        ],
        'method' => ['bancontact'],
        "description" => "My first API payment",
        "redirectUrl" => "https://webhook.site/9d0b0c3c-7e9c-4e1a-8e0a-3d0e0e5e1f0e",
        "webhookUrl" => "https://webhook.site/9d0b0c3c-7e9c-4e1a-8e0a-3d0e0e5e1f0e",
    ],[
        'include' => 'details.qrCode'
    ]);`

**Comment by sandervanhooft** [comment]
Not sure, let me check with the team.

**Comment by sandervanhooft** [comment]
Hi @Yame- ,

Can you check again now?

**Comment by Yame-** [comment]
@sandervanhooft thank you very much! We can indeed generate Banacontact QR codes now.

**Comment by sandervanhooft** [comment]
Thanks for reporting back. Mollie support double checked your account configuration. Looks like they've solved the issue.
