### ISSUE TITLE
Can you provide the code which we have to install from a zip or with composer just in a git repo

### ISSUE THREAD

**Issue by jeromba6** [mollie/mollie-api-php#509]
## Specifications

  - API Version: Latest

## Describe the issue

I really like the code en service from Mollie. With the v1 version of the api code I was able to use this repo as a sub repo of my own. That made installation and maintenance very easy. Now I have to use composer (not an option for me) or download a zip and unpack, which is harder to automate. Am I missing some thing or can you provide a repo that I can use?

**Comment by sandervanhooft** [comment]
Hi @jeromba6,

Take a look at the `makefile` in the source root. That one is used for creating the zip file for download using Travis. You should be able to run this locally too.

I know from experience there is one difference between Linux and Mac on one of the commands, let me know if you run into trouble on Mac, I may be able to help you out.

**Comment by jeromba6** [comment]
Can you point me to the makefile? I can't find it.

**Comment by sandervanhooft** [comment]
Sorry about that.

We switched to GitHub Actions last week. Here's the script we're using:

https://github.com/mollie/mollie-api-php/actions/runs/398068224/workflow#L19-L43

The old Makefile i mentioned is [here](https://github.com/mollie/mollie-api-php/blob/ae0ff0229b2f616997c224270eb50ed1b224239c/Makefile).
