### ISSUE TITLE
Update documentation for updating customers

### ISSUE THREAD

**Issue by cascer1** [mollie/mollie-api-php#51]
Hi!

I saw that release 1.7.0 added support for updating customers. Unfortunately, the [documentation](https://www.mollie.com/en/docs/reference/customers/update) still says this is not implemented.

Please update the documentation to represent the current state.

**Comment by Thijs-Riezebeek** [comment]
Thank you for opening this issue. We have opened an issue for this in our backlog and will be updating the documentation code snippets for our clients. I will close this issue once that has been resolved.

**Comment by FaaPz** [comment]
We have updated our [documentation](https://www.mollie.com/en/docs/reference/customers/update).
