### ISSUE TITLE
Some bugs/mistakes?

### ISSUE THREAD

**Issue by janssenr** [mollie/mollie-api-php#517]
## Specifications

  - API Version: 2.0

## Describe the issue

In https://github.com/mollie/mollie-api-php/blob/df60ebfc2463cdffc1faeb1fa9419911812ac6f8/tests/Mollie/API/Endpoints/ShipmentEndpointTest.php "profileId" is used in getShipmentResponseFixture (row 488)
But in https://github.com/mollie/mollie-api-php/blob/master/src/Resources/Shipment.php I cannot find "profileId"

In https://github.com/mollie/mollie-api-php/blob/master/tests/Mollie/API/Endpoints/OrderPaymentEndpointTest.php "dueDate" is used (row 35 and 97)
But in https://github.com/mollie/mollie-api-php/blob/master/src/Resources/Payment.php I cannot find "dueDate"

In https://github.com/mollie/mollie-api-php/blob/master/tests/Mollie/API/Endpoints/SettlementEndpointTest.php "percentage" is used (row 79, 103, 127, 151, 296, 320, 344 and 368)
But in https://docs.mollie.com/reference/v2/settlements-api/get-settlement its called "variable"

In https://github.com/mollie/mollie-api-php/blob/master/tests/Mollie/API/Endpoints/OrderEndpointTest.php the following fields are used:
orderline.quantityShipped
orderline.amountShipped
orderline.quantityRefunded
orderline.amountRefunded
orderline.quantityCanceled
orderline.amountCanceled
orderline.shippableQuantity
orderline.refundableQuantity
orderline.cancelableQuantity
But in https://github.com/mollie/mollie-api-php/blob/master/src/Resources/OrderLine.php I cannot find those fields

In https://github.com/mollie/mollie-api-php/blob/master/tests/Mollie/API/Endpoints/OrderEndpointTest.php the fields "productUrl" and "imageUrl" are used within "_links" (row 326 and 380)
Is this correct? 

Sometimes api.mollie.nl is used. Change this to api.mollie.com?

**Comment by sandervanhooft** [comment]
Hi @janssenr,

Everything is filled dynamically from the API response, but these resource fields can be helpful for autocompletion. Can you submit a PR?
