### ISSUE TITLE
Uncaught Error: Call to a member function create() 

### ISSUE THREAD

**Issue by Flued** [mollie/mollie-api-php#521]
When i try to create an order using 

$order = $mollie->orders->create([ 
i get this error:  Uncaught Error: Call to a member function create() ......

I really can"t figure it out.

my includes work.
require ("/mollie/vendor/autoload.php");
$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setApiKey("test_JJGawswskAFw6khduMyFEzKhBRE76a");

Anyone got a fix?

**Comment by Jules077** [comment]
I have same problem but almost every function errors like this maybe it has something to do with the includes or composer.

**Comment by sandervanhooft** [comment]
@Jules077 

What package version are you using?
How did you install it? (Downloaded zip / `composer install`)

**Comment by Jules077** [comment]
package version 2.0 installed with the composer

**Comment by sandervanhooft** [comment]
I'm unable to reproduce the error. Can you share the full exception stack trace here?

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
