### ISSUE TITLE
It would be great to create a subscription while creating a payment. Sending payment information is kind of redundant.

### ISSUE THREAD

**Issue by picocodes** [mollie/mollie-api-php#522]

**Comment by sandervanhooft** [comment]
Hi @picocodes,

Thanks for posting this feature request. Can you elaborate a bit on your use case?

**Comment by picocodes** [comment]
Thanks, @sandervanhooft,

Currently, we can not create a subscription for new customers (i.e, customers who do not have a valid mandate). We first have to execute [this code](https://github.com/mollie/mollie-api-php/blob/master/examples/customers/create-customer-first-payment.php), then create the subscription after successful payment.

If would be great if it was possible to pass the subscription parameters such as recurring interval and times to the "$customer->createPayment".

**Comment by sandervanhooft** [comment]
Ok, that clears it up. I had the same issue, therefore created [cashier-mollie](https://github.com/laravel/cashier-mollie) - but it's Laravel only.

@MollieRick can you perhaps register this feature request somewhere internally? I second it.

**Comment by MollieRick** [comment]
I do not really see the benefit here. These are really two separate actions and flows since creating a customer is not always only for subscriptions.

**Comment by sandervanhooft** [comment]
It's about the separate first-payment and start-subscription call, not the create-customer-call.

Having these calls separate requires a lot of complex logic to get a seamless experience in the initial checkout. With "seamless" I mean without making two payments (and invoices) to start the subscription.

I know this is not easily changed, but it makes sense to track requests like these somewhere.

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
