### ISSUE TITLE
Feature request: Add reason code for chargeback to Chargeback API

### ISSUE THREAD

**Issue by egogo-nl** [mollie/mollie-api-php#524]
When I do a SEPA payment and I receive a chargeback, I can only see the reason of the chargeback in the Mollie Dashboard, not with the API.

For example, a reason could be:
Rekening geblokkeerd voor incasso (AC06)

I would like to receive this information in the Chargeback API. Currently it only results if a transaction is charged back or not, not the reason why. With this information I can automate processes based on the reason code, so less manual actions.

**Comment by MollieRick** [comment]
Hello @egogo-nl,

Thank you for your message! I added your feature request to our backlog. Unfortunately I can not give you an ETA for this.
