### ISSUE TITLE
Open settlement endpoint times out

### ISSUE THREAD

**Issue by sweebee** [mollie/mollie-api-php#530]
## Specifications

  - API Version: 2.29.0 (Laravel package 2.14.0)

## Describe the issue

I'm getting a time-out on the settlements open endpoint ```settlements()->open()```. (after more than 60 seconds).

I only have this on a Mollie account with more than 2500 transactions in the last 24h. I know this might be a bug in the API but I'm posting it here since there are probably devs from Mollie here :)

**Comment by sandervanhooft** [comment]
@MollieRick ?

**Comment by sweebee** [comment]
Did some more diggin. By doing a request via Postman I get 10 seconds:

<img width="1572" alt="Schermafbeelding 2021-02-11 om 20 51 09" src="https://user-images.githubusercontent.com/10496485/107691980-764f1100-6cac-11eb-9ad4-3a01a97fb6c5.png">

By doing the same with the Mollie PHP API (```Mollie\Laravel\Facades\Mollie ```):

<img width="744" alt="Schermafbeelding 2021-02-11 om 21 00 13" src="https://user-images.githubusercontent.com/10496485/107692086-98489380-6cac-11eb-91d7-77dfa357db9e.png">

**Comment by sandervanhooft** [comment]
That call to the settlement endpoint is exactly the same across the Laravel / PHP clients, I don't think that's causing any (additional) performance issues here.

**Comment by sandervanhooft** [comment]
@leonardogcsoares any update on this?

**Comment by leonardogcsoares** [comment]
Hi Sander. This is a known problem and we are still looking into the best way to mitigate/accelerate it for the future. Unfortunately, I have no updates at this time but will push the urgency on with the appropriate parties involved.

**Comment by sandervanhooft** [comment]
Thanks @leonardogcsoares !

**Comment by sandervanhooft** [comment]
@sweebee is this problem still occurring for you?

**Comment by sweebee** [comment]
> @sweebee is this problem still occurring for you?

Haven’t checked lately. Currently on vacation. Will check it next week.

**Comment by sandervanhooft** [comment]
Thanks @sweebee ! Enjoy! 🏖️

**Comment by sweebee** [comment]
Did some "long term" testing and today i got my first error (internal server error):

GuzzleHttp\Exception\ServerException: Server error: `GET https://api.mollie.com/v2/settlements/open` resulted in a `500 Internal Server Error` response: {"status":500,"title":"Internal Server Error","detail":"Internal Server Error","_links":{"apiStatus":{"href":"https://st (truncated...)

**Comment by sandervanhooft** [comment]
@leonardogcsoares can you take a peak?

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
