### ISSUE TITLE
Mollie connect - How to know users Profile ID to start Payment

### ISSUE THREAD

**Issue by HugoVanPouderoijen** [mollie/mollie-api-php#534]
## Specifications

  - API Version: 2.0

## Describe the issue

I am integrating Mollie Connect to let our websites resellers/partners receive payments of bookings. We get it running but the issue starts when we want to initiate the first payment 
- When starting a payment with an acces code, you need to have a profile id. 
- But when i want to retrieve "the current profile_id" we get the error that that action is only valid with apikey not with an accesscode.  

How do we then ever know the profile id to submit initiating a payment?

Driving me crazy for days now, but just can't find the right way... completely lost. 

Thanks in advance..

**Comment by robindirksen1** [comment]
You need to list all profiles, this is a separate endpoint.

Then, you need to provide the profile_id to the endpoints when creating the payment.

**Comment by robindirksen1** [comment]
You need to list all profiles, this is a separate endpoint.

Then, you need to provide the profile_id to the endpoints when creating the payment.

**Comment by willemstuursma** [comment]
> Then, you need to provide the profile_id to the endpoints when creating the payment.

If there are multiple profiles, you should let the user select to which profile they want the payments of your app to go to.

**Comment by HugoVanPouderoijen** [comment]
@robindirksen1  Thats the problem. 

Using the profiles endpoint i get the error : 
"This API endpoint is only available with an API key and cannot be accessed with an OAuth access token.. "

And @willemstuursma  : If i approve the app with those permissions, on an account with one or more profiles i dont get an profile_id back in respons, nor can i a (as user point of view) select a profile. 

Somewhere i just miss something i assume..

**Comment by sandervanhooft** [comment]
The top of the API documentation pages list the possible authentication methods.

The _current_ profile endpoint is only accessible using an api key.

The [list](https://docs.mollie.com/reference/v2/profiles-api/list-profiles) and get endpoints can be used with an access token.

The list profiles endpoint is the one you'll need to (let the merchant) decide which one to use with your app.

```php
$mollie = new \Mollie\Api\MollieApiClient();

$mollie->setAccessToken("access_Wwvu7egPcJLLJ9Kb7J632x8wJ2zMeJ");

$profiles = $mollie->profiles->page();
```

**Comment by sandervanhooft** [comment]
To be clear: Mollie does not offer an UI to select the profile, because the authorization is at Account level. Which means you have access to all profiles related to that account once you have obtained the refresh and access token.

**Comment by HugoVanPouderoijen** [comment]
@sandervanhooft @willemstuursma @robindirksen1   

Thanks guys! You just made my weekend :) Finally!  It was the misunderstanding of using the current profile endpoint (and assumed also the list function wouldn't work).

**Comment by sandervanhooft** [comment]
Great work @HugoVanPouderoijen ! 🕺 

Feel free to open another issue if you need help getting unstuck.
