### ISSUE TITLE
How to insert values in database after the successful payment only.

### ISSUE THREAD

**Issue by Saad1379** [mollie/mollie-api-php#536]
## Specifications

  - API Version: 

## Describe the issue
I have a custom booking form in Wordpress and I use Mollie as a payment gateway. I want the values to be inserted into database after the payment is successful but right now I am doing it before the payment is made. Here is the code of my Save.php file:

```$mollie = new \Mollie\Api\MollieApiClient();
 $mollie->setApiKey("MY_API_KEY");


 $payment = $mollie->payments->create([
     "amount" => [
         "currency" => "EUR",
         "value" =>  $total_amount
    ],
     "description" => "My first payment",
    "redirectUrl" => "https://my_booking_page_url",
     "metadata" => [
         "order_id" => $orderId,
     ],
 ]);
global $wpdb;
$result = $wpdb->insert('my_table', array(
    'Name' => $name,
    'Email' => $email,
    'Phone' => $phone,
    'start_date' => $date,
    'booking_time' => $booking_time,
    'no_of_cars' => $cars_no,
    'extra_person' => $extra_person,
    'gps' => $gps,
    'food_person' => $food,
    'children_no' => $children,
    'payment_type' => $payment_type,
    'total_amount' => $total_amount,
    'order_id' => $orderId,
    'vat' => $vat,
    'adres' => $adres
));
header("Location: " . $payment->getCheckoutUrl(), true, 303);
```

**Comment by sandervanhooft** [comment]
The only way to know if the payment was paid is when your webhook gets called (you can define it on the payment payload).

Generally integrations store a _pending_ order or payment with the details you mentioned before redirecting the customer to Mollie's checkout. And then update the record to status paid when the webhook gets called (and the payment indeed was paid).

Optionally you can periodically remove all `failed` records but personally I'm a fan of keeping everything on record. Easier for debugging / customer support etc. .

https://docs.mollie.com/guides/webhooks
