### ISSUE TITLE
Is there any way to verify if the Webhook.php is being execute properly?

### ISSUE THREAD

**Issue by Saad1379** [mollie/mollie-api-php#540]
## Specifications
mollie php api
  - API Version: 

## Describe the issue
I have my payment method working properly and the code for payment status update is written inside the webhook.php file. My problem is that create_payment.php file is working properly  but the Webhook.php file is not updating the status of payment.
...

**Comment by sandervanhooft** [comment]
Your webhook needs to be reachable by Mollie. You can check this in the Mollie dashboard by looking up the payment.

A common way to test this locally is by setting up a tunnel, i.e. using [ngrok](https://ngrok.com), Laravel valet or Expose.

**Comment by Saad1379** [comment]
The webhook file is not on the localhost. It is on online server with active ssl.

**Comment by sandervanhooft** [comment]
What is the Mollie dashboard saying about the webhook calls for that payment?

**Comment by Saad1379** [comment]
![image](https://user-images.githubusercontent.com/16044705/112164125-73caca00-8c0f-11eb-8771-4930b1da8e5c.png)

**Comment by sandervanhooft** [comment]
> Is there any way to verify if the Webhook.php is being execute properly?

There you go. As you can see in the dashboard Mollie has tried to call it multiple times and was able to reach the webhook. A status 500 means something went wrong in your app while processing it. I recommend checking your logs or debugging it locally to see what's happening.
