### ISSUE TITLE
ShippingAddress becomes required on update

### ISSUE THREAD

**Issue by lukaskleinschmidt** [mollie/mollie-api-php#541]
## Specifications

  - API Version:  v2.30.0

## Describe the issue

When I try to update just the `webhookUrl` for a order that does not have a `shippingAddress` I get following error.

> Mollie\Api\Exceptions\ApiException
[2021-03-23T16:18:01+0000] Error executing API call (422: Unprocessable Entity): Non-existent body parameter "shippingAddress" for this API call. Did you mean: "shippingAddress.city"?. Field: shippingAddress. Documentation: https://docs.mollie.com/guides/handling-errors 

Initially I wanted to create a PR that simply filters any `null` values but this could potentially break something else as you would not be able to deliberately set a value to `null` then.

In this context I also noticed that it is currently not possible to remove a previously set `shippingAddress` in a order. Is that the intended behavior? Just curious.

Right now I "fixed" it like this.
```php
$order->webhookUrl = 'https://www.example.com/webhook';

if (! $order->shippingAddress) {
    $order->shippingAddress = $order->billingAddress;
}

$order->update();
```

**Comment by sandervanhooft** [comment]
There's probably some pay-after-delivery (Klarna) logic in the way here.

I'll check with Mollie

**Comment by sandervanhooft** [comment]
The update method here always sends the `shippingAddress`: https://github.com/mollie/mollie-api-php/blob/53f461ad6409a2d25a19d0336f88a285ade9b8e0/src/Resources/Order.php#L487-L493

The API seems to not accept the shippingAddress to be `null`.

**Comment by shirshir** [comment]
I can confirm the problem. I will have a look.

**Comment by shirshir** [comment]
@lukaskleinschmidt A fix was deployed to address this issue. Can you confirm your problem is solved?

**Comment by lukaskleinschmidt** [comment]
@shirshir Yes the problem is fixed. Thanks for looking into this 🙂

**Comment by sandervanhooft** [comment]
Nice, thanks @shirshir !
