### ISSUE TITLE
Invoices API v1 no longer allows to include Settlements

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#544]
## Specifications

  - API Version: v1

## Describe the issue
As documented here: https://docs.mollie.com/reference/v1/invoices-api/get-invoice#includes, the Invoices API allows to "include" Settlements in the response. 

Starting with Invoices from around 2020Q4:

- this information is not included in the response anymore.
- this information is also not on the PDF version of the Invoice anymore

My request would be to make it possible to include this information again. 

It is very useful to be able to determine which Settlements are covered by a specific Invoice.

Although the API v1 is deprecated, its behaviour should not change, right? Systems (might) rely on this behaviour / information to be available.

The Invoice [API v2 seems to not allow including the Settlements](https://docs.mollie.com/reference/v2/invoices-api/list-invoices#), I expect this has to do with it not being available in v1.

**Comment by sandervanhooft** [comment]
Thanks @holtkamp, I've notified the Mollie team about this.

**Comment by holtkamp** [comment]
@sandervanhooft any update on this? We use this functionality for bookkeeping purposes as well, which is now blocked by this change in behaviour...

**Comment by sandervanhooft** [comment]
Pinging Mollie again.

**Comment by sandervanhooft** [comment]
Just curious, Any chance you're upgrading to v2 anytime soon? 😎

**Comment by sandervanhooft** [comment]
Hi @holtkamp,

I just discussed with the API team at Mollie. Bad news. The link between settlements and ledger invoices has been dropped permanently. The basic stuff on `v1` like creating and retrieving payments will remain functional, yet it's strongly advised to upgrade to v2 and look into the settlements API there.

Closing this for now, let me know if it should be reopened. Also let me know if you need help upgrading.

**Comment by holtkamp** [comment]
Ok, understood. 

 `yet it's strongly advised to upgrade to v2 and look into the settlements API there.`

In summary: 

- we receive an Invoice X from Mollie, which covers Settlements Y and Z
- we want to use the API to know which Settlements an Invoice X covers
- this was possible, but not anymore

Since it is not possible to follow the path "Invoice => Settlement", am I correct that the new suggested approach is to use "Settlement => Invoice", meaning: iterate over **all** Settlements of a month and determine the used Invoice? Seems not very "intelligent". 

What do you suggest? Following this inefficient path, or open a request to support the Invoice => Settlement path?

**Comment by sandervanhooft** [comment]
The invoice behavior has changed a bit a while ago, and that's why the API followed suit.

Mollie now sends one invoice a month.

If the balance is sufficient, a settlement is performed, covering one or multiple invoices.

That means that

- an invoice can exist without settlement
- one settlement covers one or multiple invoices

What's your precise use case here?

**Comment by holtkamp** [comment]
The use case is: 

- money of Settlements is deposited on our bank account in a configurable frequency, for example: daily
- the amounts of the Settlements are lower than the realized turnover because transaction fees are subtracted automatically, for example:
  - for 100 euro turnover through Mollie, 99 euro is deposited on our bankaccount by Mollie
  - by the end of the month an Invoice of 1 euro is received, which is stored in our accounting software
- to process the deposits to our bankaccount in our accounting software automatically: 
  - wait for the Mollie Invoice
  - use the association Invoice => Settlements to determine which transactions on our bank account could be processed (assigned to a ledger account). That way we could process all deposits by Mollie in an administrative sound way and mark the stored Invoice as "paid"

The manual approach to this process is documented here: https://www.moneybird.nl/kennisbank/voorbeeld-mollie-uitbetaling-verwerken/

But doing this manually is not an option when volume grows...


> - an invoice can exist without settlement
> - one settlement covers one or multiple invoices

Especially the last one took some time to sink in... I think this is because my brain is used to daily Settlements. I suppose I will have to adapt to the new structure. It would have been nice to be "informed" about such changes as apparently it impacts your customers operations 😉

**Comment by sandervanhooft** [comment]
> It would have been nice to be "informed" about such changes as apparently it impacts your customers operations 😉 . In particular since v1 is supported until July 2023 according to this text

In part this is bad understanding from my part. You're right, the v1 api will remain fully supported. The change in "domain behavior" and especially the technical ramifications have caught me by surprise too, I'll take this up with Mollie.

As I understand it, depending on your accounting needs you can either check for new invoices, or for new settlements and then check the related invoices. I will check if including the invoices in the settlement responses on v2 could be an option.
