### ISSUE TITLE
Can't send email confirmation from webhook

### ISSUE THREAD

**Issue by BigBenJr** [mollie/mollie-api-php#546]
## Specifications

  - API Version: 3.0.0

## Describe the issue

Hi,

I use the Mollie Orders API and a webhook URL which is called by Mollie when an order is made on my website.
On this webhook I have a script to send email confirmation to my customers when the status order is 'paid'.
It was working well when I was using the php mail() function.
Now I am using Sendinblue API to send the transactional emails of my website and it does not work anymore.
Sendinblue API works everywhere on my website except from the webhook called by Mollie.
My php script which send the confirmation mail is working if I execute it manually from my website, but when the script is executed when Mollie calls my webhook it does not work.
I can't know exactly why as I do not know how to debug a webhook ?
I only get the message "Webhook failed with status code 500 (Internal Server Error)" in my Mollie transaction history when the script to send the email confirmation is on my webhook (otherwise everything is find).
Do you think it is a security feature which do not allow a webhook called from a post method to send an email using Sendinblue API ?
I don't know how to get help, I am not professional coder and I don't think it is a Sendinblue API issue as I am able to use that API in all the other contexts except on that webhook called by Mollie.
I would be glad if someone here could give me some hint about where to find a solution.
Thank you.

**Comment by sandervanhooft** [comment]
Hi!

From the outside I can't tell what's happening other than that the webhook url is returning an error. Best is to enable some logging on the webhook code and see what it says.
