### ISSUE TITLE
Missing @throws tag

### ISSUE THREAD

**Issue by mikey242** [mollie/mollie-api-php#551]
Just a potentially minor issue, it looks like ```cancelSubscription``` method of the class ```Customer``` can throw the ```\Mollie\Api\Exceptions\ApiException``` but has no @throws tag in the PHPDoc to reflect this. When testing to cancel an already canceled subscription using this method I get this output:

```
Mollie\Api\Exceptions\ApiException thrown
Error executing API call (422: Unprocessable Entity): The subscription has been cancelled. 
```
So it definitely can throw it. Hopefully I am not missing something and this isn't related to #430.

Thanks

https://github.com/mollie/mollie-api-php/blob/c1a500d251255e29919c6250d5c741ae4fe4e178/src/Resources/Customer.php#L132

**Comment by sandervanhooft** [comment]
Any interaction with the Mollie api can throw that exception. Feel free to provide a PR :)
