### ISSUE TITLE
Status / roadmap Mollie Reseller-API: which one to use?

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#56]
Hey guys, 

I am currently checking on how to use Mollie's Reseller functionality. 

On https://github.com/mollie/reseller-api/ one can read:

> De Reseller API maakt gebruik van geheime sleutels en signatures voor authenticatie en beveiliging, anders dan bij de nieuwe Mollie API. Komend jaar zullen we de nieuwe Mollie API uitbreiden met reseller-functies, maar in de tussentijd wordt u geadviseerd deze Reseller API te gebruiken en krijgt u daar uiteraard volledige ondersteuning bij.

Since a specific date lacks, I have to ask, which year is "komend jaar"? 

In the "new" [Mollie API](https://github.com/mollie/mollie-api-php) I already noticed files about Organizations, Profiles, etc. Can it already be used to manage Reseller information? And if not, are there any time lines available, like a roadmap?

**Comment by willemstuursma** [comment]
Hi @holtkamp. We recommend that you'd make any new implementations on the basis of our OAuth APIs. If you need anything not provided by these APIs, you can use the Reseller APIs. 

If you have any big plans, we'd love to hear from you so feel free give us a call or email.

**Comment by willemstuursma** [comment]
@FaaPz could you update our documentation.

**Comment by FaaPz** [comment]
Updated our [Reseller API](https://github.com/mollie/reseller-api) documentation on GitHub.
