### ISSUE TITLE
Unsupported Input Received when submitting payment

### ISSUE THREAD

**Issue by mikey242** [mollie/mollie-api-php#560]
## Specifications

  - API Version:  2.32.1

## Describe the issue

Just updated from 2.32.0 to 2.32.1 and noticed my test payments were immediately failing with the error:

`Error executing API call (415: Unsupported Input Received): This API only accepts application/json or application/x-www-form-urlencoded as content-type`

Downgrading to 2.32.0 immediately fixes the issue. Seems to be related to this #556 

...

**Comment by xyzqtc** [comment]
Same for me.

**Comment by sandervanhooft** [comment]
Thanks for reporting this! I have released `2.32.2` to revert this. Will investigate later to see if I can reproduce this.

**Comment by sandervanhooft** [comment]
> Thanks for reporting this! I have released 2.32.2 to revert this. Will investigate later to see if I can reproduce this.

That's a lot of sentences ending with "this". That's what you get when hotfixing before coffee 😴 😅 .

**Comment by xyzqtc** [comment]
![Screen Shot 2021-06-07 at 6 15 15 PM](https://user-images.githubusercontent.com/78330971/121194643-391c1980-c86f-11eb-94c1-817aacdcb7e6.jpg)

**Comment by sandervanhooft** [comment]
> ![Screen Shot 2021-06-07 at 6 15 15 PM](https://user-images.githubusercontent.com/78330971/121194643-391c1980-c86f-11eb-94c1-817aacdcb7e6.jpg)
> 
> 

This is from 2.32.1 right? @xyzqtc

**Comment by lode** [comment]
@sandervanhooft probably this still goes wrong. We just did a composer update and got 2.32.1. This might be because the latest release is 2.31.2 (notice 31) instead of 2.32.2. Could you do a new release for that?

**Comment by boxblinkracer** [comment]
Hi @lode 
heres a fix i did in the meantime 
https://github.com/mollie/mollie-api-php/pull/562/files

can you see if the upper case "T" fixes your problem
(could be that the code was reverted) but its only the Content-Type stuff in the MollieApiClient

then it worked again for me

**Comment by sandervanhooft** [comment]
ouch sorry about the version issue. Will fix that right away.

**Comment by sandervanhooft** [comment]
Done! https://github.com/mollie/mollie-api-php/releases/tag/v2.32.2

**Comment by mikey242** [comment]
Working as expected now @sandervanhooft . Thanks for the quick action.

**Comment by sandervanhooft** [comment]
@lode if you have a moment, can you give the PR provided by @boxblinkracer a try? I cannot reproduce the issue here locally.

**Comment by sandervanhooft** [comment]
> @lode if you have a moment, can you give the PR provided by @boxblinkracer a try? I cannot reproduce the issue here locally.

Same request for @mikey242 😄

**Comment by sandervanhooft** [comment]
[This one](https://github.com/mollie/mollie-api-php/pull/562/files)

**Comment by mikey242** [comment]
> [This one](https://github.com/mollie/mollie-api-php/pull/562/files)

Test payment worked for me with the new MollieApiClient.php changes in #562.

**Comment by boxblinkracer** [comment]
THANKS for testing @mikey242

**Comment by lode** [comment]
> @lode if you have a moment, can you give the PR provided by @boxblinkracer a try? I cannot reproduce the issue here locally.

I didn't run 2.32.1 or 2.31.2, I only followed this ticket and noticed that we didn't get the expected version when doing a composer update.

But it seems resolved now. Thanks!
