### ISSUE TITLE
Invoices API v1: internal server error when trying to include InvoiceLines

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#564]
## Specifications

  - API Version: 1.0

## Describe the issue
When loading "all" Invoices, it is allowed to "include" the (invoice) `lines` in the response: https://docs.mollie.com/reference/v1/invoices-api/get-invoice#includes

Trying to do so results in: 

```
[Mollie_API_Exception]                                                                                
  Error executing API call (system): Internal server error; we have been informed about this incident. 
```

When leaving out the `lines` value as include, this error does not occur.

**Comment by sandervanhooft** [comment]
Hi @holtkamp , is this behaviour still occurring?

**Comment by holtkamp** [comment]
@sandervanhooft yes it does...

- including `settlements` => works
- including `lines` => fails
- including `settlements,lines` => fails

**Comment by holtkamp** [comment]
@sandervanhooft any update on this, just checked and this behaviour still occurs 👀

**Comment by sandervanhooft** [comment]
Let me check

**Comment by sandervanhooft** [comment]
Hi @holtkamp ,

Can you share the specific code you're using? We cannot reproduce the issue here.

**Comment by holtkamp** [comment]
@sandervanhooft something like this:

```php
$offset = 0;
$limit = 250;
$filters = [
    'include' => 'lines',
];
$result = $apiClient->invoices->all($offset, $limit, $filters);
```

results in 

```
[Mollie_API_Exception]                                                                                
  Error executing API call (system): Internal server error; we have been informed about this incident.
```

The error message suggests it is logged and the team is/will be informed, so hopefully the request can be easily identified? 😉

**Comment by sandervanhooft** [comment]
Hi @holtkamp,

That code snippet really helped to pinpoint the problem on Mollie's end. Can you check if the issue has been solved now?

**Comment by holtkamp** [comment]
@sandervanhooft thanks, now it works again!

Can you share details of the cause? (always curious 😉 )

**Comment by sandervanhooft** [comment]
Thanks @holtkamp for following up! It seemed to have been an internal error. May have slipped in with v1 being deprecated for some time and Mollie moving forward quite fast on v2.
