### ISSUE TITLE
Feature request: Add getCheckoutUrl() to Order resource

### ISSUE THREAD

**Issue by Flaschenzug** [mollie/mollie-api-php#567]
## Specifications

  - API Version: 2.35.0

## Describe the issue

I need to load an existing order, using 
$payment = $mollie->payments->get(PAYMENTID);

If the order is still open, I need to generate the checkoutUrl again:
$payment->getCheckoutUrl()

But the getCheckoutUrl() seems to be only working for creating payments?
So how do I get the checkoutURL for an existing order?

Thanks

**Comment by sandervanhooft** [comment]
How about

``` php
$order->_links->checkout->href;
```

?

**Comment by Flaschenzug** [comment]
Thanks @sandervanhooft 

I tried that, but got situations where checkout link didn't exist.
But looked into it again and it seems to be available when status is "open" but not when it is "paid".
And that would make sense ...

If I am thinking right, that should work.. ?

**Comment by sandervanhooft** [comment]
You're right. Nevertheless we'll explore adding a `getCheckoutUrl()` to the Order resource.

**Comment by ciungulete** [comment]
<img width="1133" alt="Screenshot 2021-06-23 at 22 43 15" src="https://user-images.githubusercontent.com/742128/123158515-8d7ce700-d474-11eb-907a-09a5e1848683.png">

**Comment by sandervanhooft** [comment]
Eh... my bad. It's already there. 🤦 🎉

**Comment by sandervanhooft** [comment]
https://github.com/mollie/mollie-api-php/blob/19f69c116d47a3600f0ed629e0df925a43d3a8f5/src/Resources/Order.php#L420

**Comment by Flaschenzug** [comment]
If it is already there, how do I use it? Thanks

**Comment by sandervanhooft** [comment]
Hi @Flaschenzug,

Note that `$order->getCheckoutUrl()` returns `null` if the API response does not provide a checkout url. This in turn depends on the payment status. Also, one Order can have multiple Payments, so there's probably a bit more logic going on there I'm not fully aware of (yet). Let's see if we can figure it out.

Can you elaborate a bit on your use case?
