### ISSUE TITLE
The status remains on 'pending-review'

### ISSUE THREAD

**Issue by MitchBred** [mollie/mollie-api-php#569]
## Specifications

  - API Version: 2
  - API Call: [https://api.mollie.com/v2/methods/all](https://api.mollie.com/v2/methods/all)

## Describe the issue

When SEPA Direct Debit is activated in the dashboard, the status remains on 'pending-review'.

    "status": "pending-review"

**Comment by sandervanhooft** [comment]
Hi @MitchBred,

Best is to contact Mollie support directly for this, as this account specific.

https://www.mollie.com/en/contact
