### ISSUE TITLE
Allow organization access keys

### ISSUE THREAD

**Issue by 4BRobby** [mollie/mollie-api-php#571]
## Specifications

  - API Version: 2.0

## Describe the issue

Api Client restricts keys to live_ and test_ and therefor restricts usage of access_ (organization API keys). This is easily solvable.

ApiClient.php line 328:
`if (!\preg_match('/^(live|test|access)_\\w{30,}$/', $apiKey)) {`

**Comment by sandervanhooft** [comment]
Hi @4BRobby,

Can you try setAccessToken instead?

**Comment by MollieRick** [comment]
Organizations Access Tokens should be set via `setAccessToken` indeed. 
Since there's no comment anymore, lets close it.

**Comment by 4BRobby** [comment]
Sorry have missed the first update on this issue.
You are absolutely right, setAccessToken is the right way to do it and it meets the requirements - documentation now contains also a hint on this function.
