### ISSUE TITLE
Missing attribute timesRemaining in Subscription Resource

### ISSUE THREAD

**Issue by cbl** [mollie/mollie-api-php#572]
## Specifications

  - API Version: v2.37.0

## Describe the issue

According to the [Subscription docs](https://docs.mollie.com/reference/v2/subscriptions-api/get-subscription) the Subscription resource should have an attribute named `timesRemaining`. However this attribute is missing in the resource of this package: https://github.com/mollie/mollie-api-php/blob/master/src/Resources/Subscription.php

**Comment by sandervanhooft** [comment]
👍 Correct, we're preparing a PR.

**Comment by sandervanhooft** [comment]
The release was just tagged as `v2.37.1`. Thanks for reporting @cbl !
