### ISSUE TITLE
Webhook handling problem (seems like clearing cookie)

### ISSUE THREAD

**Issue by telefoniero** [mollie/mollie-api-php#574]
## Specifications

  - API Version: 2.0

## Describe the issue
File structure of project:
- pay.php
- mollie-webhook.php
- mail.php
- mollie-api-php (folder)

All steps were made based on github examples.

1. I create a payment by calling pay.php and passing JSON data to set a cookie. The response is a checkoutUrl (working properly). Moreover, i have manually checked cookie data, and it was all right.
2. My webhookUrl is mollie-webhook.php. The only state i test is "isPaid", so, if it is, I send an e-mail, the content of which is processed in the mail.php. There I get the data from cookie and handle it.

So, the issue is: there is no letter sent, but redirect happens.

pay.php:
<img width="702" alt="Снимок экрана 2021-08-16 в 17 43 06" src="https://user-images.githubusercontent.com/68998223/129582267-970e3972-8b08-4090-bee2-955cdfec7e03.png">

mollie-webhook.php:
<img width="404" alt="Снимок экрана 2021-08-16 в 17 39 42" src="https://user-images.githubusercontent.com/68998223/129582286-d01c8372-3c52-40c7-a884-2770ee4cd6aa.png">

mail.php (just handling the data, is tested manually):
<img width="347" alt="Снимок экрана 2021-08-16 в 17 39 55" src="https://user-images.githubusercontent.com/68998223/129582304-54541288-42e6-4ef3-89de-284275e102aa.png">

P.S. Yes, that's my first issue, so i'm newbee :)
...

**Comment by sandervanhooft** [comment]
Hi @telefoniero ,

In the Mollie dashboard, look up the payment. The column on the right lists the events happened. Can you check what it says about the webhook calls?

**Comment by telefoniero** [comment]
Hi @sandervanhooft,

Each webhook was called successfully, and the corresponding test payment was also made.

**Comment by telefoniero** [comment]
It looks, like my handler is faulty, but i've created a buffer-like file to set a cookie there, then to redirect to mail.php - e-mail had been sent as I expected.

**Comment by DeryabinSergey** [comment]
When mollie request webhook- mollie server has no cookie, that you set to client, when making a payment

**Comment by telefoniero** [comment]
Hi @DeryabinSergey,

So, i need to use third party API?

**Comment by DeryabinSergey** [comment]
You should save order data at your side, in DB for example.

**Comment by telefoniero** [comment]
I got you. Thank you very much!
