### ISSUE TITLE
How to solve time out errors

### ISSUE THREAD

**Issue by MartijnOud** [mollie/mollie-api-php#578]
- API Version: 2.37.1

Hello! I'm unexpectedly getting time out errors when creating new payments. I'm not getting these errors consistently (maybe 40% of the time?) and haven't experienced this on similar projects on the same server so I'm having a hard time debugging this.

The error message:
```
[2021-09-15T15:10:40+0200] Curl error: Resolving timed out after 2516 milliseconds
--
[2021-09-15T15:50:53+0200] Curl error: Resolving timed out after 2512 milliseconds
```

I did find #470 with an example of how to overwrite the DEFAULT_TIMEOUT but since that is set to 10 seconds and mine times out after 2.5 seconds I don't think that will resolve my issue. The DEFAULT_CONNECT_TIMEOUT is set to 2 seconds so that doesn't appear to be it either.

Any advice on how to find out exactly what is timing out and how to resolve that?

**Comment by sandervanhooft** [comment]
Hey!

That's unfortunate!

If I understand your description correctly it's still possible to be the DEFAULT_CONNECT_TIMEOUT ?

Where is the server (geographically) located?

**Comment by sandervanhooft** [comment]
Ah wait, given the error message it looks like a dns issue.

**Comment by MartijnOud** [comment]
Hi Sander, thanks for the quick reply! 

I've been testing with manually setting the DEFAULT_CONNECT_TIMEOUT & DEFAULT_TIMEOUT really low (and really high) but I can't seem to replicate it at all today which is a bit frustrating. The server is a TransIP VPS hosted in Amsterdam. DNS would make sense but [it looks like that's not easy configurable](https://stackoverflow.com/questions/4226000/how-can-i-change-the-php-curl-timeout-when-curl-attempts-to-resolve-host-curl-e)?

**Comment by sandervanhooft** [comment]
It sound like a hiccup at your DNS provider.

DNS issues are hard to trace/debug unless your dns provider has some sharable status monitoring.

I'll inform the Mollie team to keep a lookout for any known DNS issues, but from Mollie's side the monitoring shows no issues.

Closing this for now, let me know if it should be reopened.

**Comment by MartijnOud** [comment]
Unfortunately, I'm still getting this exact issue occasionally. Like just now. 

```
[2022-04-12T22:03:04+0200] Curl error: Resolving timed out after 2000 milliseconds
```

I bumped `DEFAULT_CONNECT_TIMEOUT` to 5 which still gave me issues, after setting it to 15 customers can at least finish the transaction now. Since creating this issue I've seen it on multiple servers (and DNS servers) but only rarely.

Is there a way I can more elegantly time-out when this happens?

**Comment by sandervanhooft** [comment]
@rares-mollie have there been any dns resolution issues lately?

**Comment by rares-mollie** [comment]
@MartijnOud Please reach out to tech support so we can debug as your problem is persistent, not spurious. It's not clear to me from your message what endpoint is failing and if the failure is from the perspective of your application or from the perspective of the consumer.

**Comment by MartijnOud** [comment]
Hi! Thanks for the advice. Just after sending everything over via the contact form it seems I've found the issue, I've re-issued the SSL certificate and things seem to be working again. Hopefully it keeps working!

**Comment by MartijnOud** [comment]
Just wanted to update that this issue returned. This time on a different server. Unfortunately the only information I can find about it is this very ticket. I've now created a ticket with the requested information (response apparently will take a few days), but a week-long not being able to take payments is very painful. This seems very much like a Mollie issue to me.

Is there really nothing you can do to resolve or handle this more gracefully?

**Comment by Naoray** [comment]
Hi @MartijnOud,

I will bring this ticket to the attention of the mollie team and get back to you ASAP

**Comment by fjbender** [comment]
From our end we don't have any similar reports so far - so from here it looks like it's pretty much isolated to our system. I understand it's frustrating to debug, but I don't think there is anything on our end that we can do to help.

Is it a TransIP VPS again? Have you reached out to their support? Have you tried reconfiguring your `resolv.conf` to try using a different DNS server, or hardcode api.mollie.com in your `/etc/hosts`? Alternatively, you could also try [injecting a `Guzzle` HTTP Client](https://stackoverflow.com/questions/56192218/make-request-to-explicitly-given-ip-but-use-explicitly-given-hostname-for-the-p/56193653#56193653) with an appropriate `CURLOPT_RESOLVE` [flag](https://curl.se/libcurl/c/CURLOPT_RESOLVE.html) (`api.mollie.com:443:34.111.71.221`) for debugging purposes.

I mean, those are all Bad Ideas™ to have on for a prolonged time, but might help pinpoint the issue.

**Comment by MartijnOud** [comment]
The transip support stopped at "try plesk repair all -y". 

I get that you maybe don't hear issues with this often, but as you can see this isn't the first time I'm fighting to get Mollie to accept my payments. It worked for many months, and then just stopped working. There are no other issues related to dns, curl, or something like that.

I've created a support request (1873988) where I was asked for more information.

I can curl the mollie.com homepage, so it doesn't seem like a dns or firewall block or something to me. But I can try to hard code the dns, I've added to my /etc/hosts (and rebooted):

```
34.111.71.221 mollie.com
```

But that doesn't seem to change anything (I might have done something wrong though, this is new to me). I'm going to inject the guzzle client too to see what I can learn from that.

**Comment by MartijnOud** [comment]
Last night at ~21:50 it started working again. I can't reproduce the issue anymore. The last change I made is the /etc/hosts but that was 4-5 hours earlier and like I said, that didn't seem to be the issue.

Any idea? Because it's baffling me and I'm scared it'll happen again.

**Comment by fjbender** [comment]
I am as baffled by this as you are... Glad to hear it's working again, though.

**Comment by MartijnOud** [comment]
It's not only baffling, it's also extremely dehumanizing that I can't get anyone in your organization to help or even care. Is there a monetary threshold that you need to cross before Mollie replies to your emails, or is this just a not-so-subtle way of telling me you no longer process payments?

For the record: this is 100% an issue on your end. I think you might have banned my IP or something.
