### ISSUE TITLE
Code suggestion for : create-payment.php

### ISSUE THREAD

**Issue by flaneurette** [mollie/mollie-api-php#579]
## Specifications

  - API Version: Latest release, august 9th.

## Describe the issue
https://github.com/mollie/mollie-api-php/blob/master/examples/payments/create-payment.php
https://github.com/mollie/mollie-api-php/blob/master/examples/payments/create-ideal-payment.php

I noticed in: mollie/examples/payments/create-payment.php, that there is a header re-direct being performed, however, not all browsers respect a header redirect. Some browsers even ignore it, leaving a user stranded. Would it be an idea to add a piece of text? and also: exit after a re-direction, as all PHP code below it still executed which might lead to undesired code practices.

`header("Location: " . $payment->getCheckoutUrl(), true, 303);`

Suggestion:
```
header("Location: " . $payment->getCheckoutUrl(), true, 303);
echo 'If your browser did not redirect, <a href="'.$payment->getCheckoutUrl().'">click here</a>';
exit;
```

Also, I noticed that the folder /database/ did not exist in the latest build when I cloned it, therefore I had to create it manually, as seemingly, it writes txt files to them which I never would have discovered when playing with the above code. 👍

**Comment by himanshu007-creator** [comment]
Hi!
I would like to work on this issue

**Comment by MollieRick** [comment]
Hi @flaneurette, @himanshu007-creator,

Feel free to open a pull request :-)
