### ISSUE TITLE
Mollie_API_Exception: Error executing API call (request): Unauthorized request

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#580]
## Specifications

  - API Version: 1

## Describe the issue
Without any changes to the way our software communicates with the Mollie API, as of 28-09-2021 16:42 Amsterdam time a lot of exceptions are generated by the API v1 when OAuth2 authorized API clients are used, a screenshot from our logs with the exceptions:

![Screenshot 2021-09-28 at 18 52 01](https://user-images.githubusercontent.com/776405/135131301-49a49a9f-41c3-4dc5-85cc-8bd163a3828f.png)

The exception indicates that unauthorized requests are made, while nothing changed on our side.

```
Mollie_API_Exception: Error executing API call (request): Unauthorized request. in /app/vendor/mollie/mollie-api-php/src/Mollie/API/Resource/Base.php:353
Stack trace: 
#0 /app/vendor/mollie/mollie-api-php/src/Mollie/API/Resource/Base.php(100): Mollie_API_Resource_Base->performApiCall() 
#1 /app/vendor/mollie/mollie-api-php/src/Mollie/API/Resource/Base.php(272): Mollie_API_Resource_Base->rest_create() 
#2 ......: Mollie_API_Resource_Base->create()
...
```
Also checking Payment status fails:

```
Mollie_API_Exception: Error executing API call (request): Unauthorized request. in /app/vendor/mollie/mollie-api-php/src/Mollie/API/Resource/Base.php:353
Stack trace:
#0 /app/vendor/mollie/mollie-api-php/src/Mollie/API/Resource/Base.php(127): Mollie_API_Resource_Base->performApiCall('...', '...')
#1 /app/vendor/mollie/mollie-api-php/src/Mollie/API/Resource/Base.php(288): Mollie_API_Resource_Base->rest_read('...', '...', Array)
#2 /app/vendor/mollie/mollie-api-php/src/Mollie/API/Resource/Payments.php(68): Mollie_API_Resource_Base->get('...', Array)
#3 .....: Mollie_API_Resource_Payments->get('...', Array)
...
```

https://status.mollie.com displays no problems. 

Was something changed today? This seems to affect only OAuth2 authorized API clients of users that connected their Mollie account.

I tried contacting using:
- [Twitter](https://twitter.com/MollieNL)
- Chat in the Mollie Dashboard (available Monday / Friday 09:30-16:30...)
- phone (available Monday / Friday 09:00-18:00...)

So I post this issue hoping that someone will see it quickly...

**Comment by sandervanhooft** [comment]
@holtkamp if you use a mollie oauth client, can you let me know which one/version and try reverting to a previous version?

**Comment by holtkamp** [comment]
@sandervanhooft `composer show` indicates:

```
mollie/mollie-api-php                              v1.19.13                                     
mollie/oauth2-mollie-php                           v1.0.5
```                                         

So the `mollie/oauth2-mollie-php` is quite old 😉

**Comment by holtkamp** [comment]
@sandervanhooft please standby, might have pinpointed the issue in our own code base. My apologies, closing until I gather more information...

**Comment by mollierobbert** [comment]
Good to hear you found it!

The metrics look normal on our end for the v1 API and for the OAuth authentication method, but let us know if the issue persists.

**Comment by sandervanhooft** [comment]
No problem @holtkamp, happy you've solved it.

The p1 Mollie support team also checked everything at their end and it seems fine. They however will look into the communication issue. We'll ping you here if we can use your input there, ok?

Enjoy your evening!

**Comment by holtkamp** [comment]
Just to confirm: the problem originated in user land code, not at the Mollie API. 

About the communication: yeah, after office hours it would be nice to have a place to get support / submit requests. Maybe a Slack channel for external developers can be considered?

**Comment by mollierobbert** [comment]
We have been considering something like that, indeed. :-) It's a good suggestion. I'll bring it up internally once more.
