### ISSUE TITLE
Feature Request: allow easy access to Invoice.settlements

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#583]
## Specifications

  - API Version: 2

## Describe the issue
Given a loaded Settlement, the related Payments can be loaded using [`Settlement::payments()`](https://github.com/mollie/mollie-api-php/blob/4afa8165e84f1be3478f504a94eab4fa77eb911b/src/Resources/Settlement.php#L127-L130), nice!

Given a loaded Invoice, it would be nice to be able to load the Settlements using `Invoice::settlements()`.

Request: would it be possible to implement `Invoice::settlements()`?

**Comment by holtkamp** [comment]
@sandervanhooft has this request been noticed? Just wondering 😉

**Comment by sandervanhooft** [comment]
Sorry for the delay @holtkamp , overlooked this one.

If I understand correctly, there's no such relation available, nor will it be.

One settlement covers one or multiple invoices. There's no way to retrieve settlements vice versa.

**Comment by holtkamp** [comment]
Ok, thanks. 

For those interested: the rationale for the request is documented here: https://github.com/mollie/mollie-api-php/issues/544

Closing issue.
