### ISSUE TITLE
Feature request: Add refund timestamp to API

### ISSUE THREAD

**Issue by tjveldhuizen** [mollie/mollie-api-php#586]
## Specifications

  - API Version: 2

## Describe the issue

Due to lack of funds in our Mollie account, the processing of a refund occurs a few days after the refund was created. In the API, there is only an indication at which timestamp the refund is created, but not the timestamp at which it was processed. For our own dashboard, we prefer to retrieve the actual processing timestamp, instead of providing our customers with the settlement timestamp. I hope it's possible to add this to the API.

It might be difficult to add, since also at the website the processing timestamp is not mentioned and can only be guessed from the webhook call in the history. However, this history is (also) not available in the API.

**Comment by tjveldhuizen** [comment]
Hi @sandervanhooft, do you maybe have an update on this question? I struggle to inform my colleagues about the moment of the refund. For example: we've created a refund on December 17th, it was executed on December 27th (after adding funds on December 21st), but was reported in a settlement on January 21st (due to lack of new payments). The only date in API responses on which I'm sure the refund has been processed was January 21st (settlement), but the first questions about the status arose on January 3rd already.

We also check the refund status when our web hook is called (December 27th), but the refund status at that moment was still 'processing', as far as I can see now.

![image](https://user-images.githubusercontent.com/779998/152041660-78d99f51-bdad-4653-a7c6-9c38cdcc12e8.png)

**Comment by sandervanhooft** [comment]
@tjveldhuizen thanks for the reminder! I'll check again and get back to you.

**Comment by Naoray** [comment]
Hello @tjveldhuizen,

I apologize for the delay in getting back to you! I have informed the relevant team once more, and they are aware that many customers have requested this feature. They are currently investigating the possibility of implementing it.

**Comment by tjveldhuizen** [comment]
@Naoray Does closing this issue mean it is implemented and will be released in an upcoming version?
