### ISSUE TITLE
No mandate on 'first' recurring payment with 'Bancontact/Mistercash'

### ISSUE THREAD

**Issue by Factuursimpel** [mollie/mollie-api-php#59]
Hi Mollie,

A succesful live payment using the 'first' recurring parameter should always return a valid mandate. Usually this works excellent. 

But this fails for my Belgium customers using 'Bancontact/Mistercash'. The payment gets status paid but an active recurring mandate is not generated. Hope you can fix this swiftly. Test mode works fine by the way. It only happens with live payments.

Kind regards,

Factuur Simpel

**Comment by robin-mollie** [comment]
Hi @Factuursimpel,

We're currently looking into fixing this issue and will update this issue once it is!

**Comment by Factuursimpel** [comment]
Awesome! Thanks!

**Comment by robin-mollie** [comment]
@Factuursimpel, the issue should now be fixed. You don't need to make any changes on your side, but would it be possible to verify that the fix is working for you? :)

**Comment by Factuursimpel** [comment]
Great! That was fast. Thanks! 
I will have to wait for one of my Belgian customers to pay again. The moment they do I will inform you. 
Perhaps you could suspend the issue until further notice?

By the way, could you manually assign a mandate to the customer where the issue occurred? If I would give you the Mollie customer number and Mollie transaction Id.
Perhaps you could personal message me about this? info@factuursimpel.nl or +31 (0) 85 303 3942
