### ISSUE TITLE
Payment exists, but the wrong mode is used

### ISSUE THREAD

**Issue by helemaaldebom** [mollie/mollie-api-php#595]
## Specifications

  - API Version: 2.39.0

## Describe the issue

I switched the API from test to live and I got an error when trying to launch a payment: Uncaught Mollie\Api\Exceptions\ApiException: [2021-12-23T12:40:12+0000] Error executing API call (404: Not Found): Payment tr_yQass8PRuq exists, but the wrong mode is used. Try switching live / test API keys.

I have checked the client list, that one is empty so no clients made in test mode. How can I solve this issue?
![Schermafbeelding 2021-12-23 om 13 40 36](https://user-images.githubusercontent.com/5968301/147247485-53ddac18-035a-4d47-aa84-60e81b5b02cf.png)

**Comment by sandervanhooft** [comment]
Hi @helemaaldebom ,

Can you share some code you used so we can reproduce the issue?

Not sure what you mean about the "client".

**Comment by helemaaldebom** [comment]
Hi @sandervanhooft ,

Thanks for your reply. Hereby my code:

`$mollie = new \Mollie\Api\MollieApiClient();
			 	 $mollie->setApiKey("{LIVE_API}");

				 $packages = auto_listings_get_packages();

				 foreach ( $packages as $package_id => $package ){

				 if(isset($_POST["auto-listings-purchase"])) {

					 $package_id = $_POST['auto-listings-package'];
		 		 }

				 // Create Mollie payment
				 $payment = $mollie->payments->create([
				 		"amount" => [
				 				"currency" => "EUR",
								"value" => "10.00",
						],
						"description" => "VAGplace order",
						"redirectUrl" => "{SITE_URL}/mijn-autos/?payment=success&gateway=ideal",
						"webhookUrl"  => "{SITE_URL}/mijn-autos/",
						"method"      => \Mollie\Api\Types\PaymentMethod::IDEAL,
						"metadata" => [
								"email" => $this->purchase_data['user']['email'],
								"date" => $this->purchase_data['date'],
		        ],
			 	 ]);

				 $payment = $payment->update();

				 header("Location: " . $payment->getCheckoutUrl(), true, 303);
			 }
		 }

		 require __DIR__ . "/../../../mollie-api-php/examples/initialize.php";
		 $payment = $mollie->payments->get($payment->id);

		 if($payment->isPaid()){
//execute code after payment has succeeded
}`

**Comment by sandervanhooft** [comment]
At what action / line does the exception get triggered?

Why are you calling the `update` method here?

**Comment by helemaaldebom** [comment]
I thought I need the `update` method to complete the payment.

The exception gets triggered in multiple files:

`Documentation: https://docs.mollie.com/overview/handling-errors in /customers/3/5/d/vagplace.nl/httpd.www/wp-content/mollie-api-php/src/HttpAdapter/CurlMollieHttpAdapter.php:111 Stack trace: #0 /customers/3/5/d/vagplace.nl/httpd.www/wp-content/mollie-api-php/src/HttpAdapter/CurlMollieHttpAdapter.php(64): Mollie\Api\HttpAdapter\CurlMollieHttpAdapter->parseResponseBody('{"status":404,"...', 404, NULL) #1 /customers/3/5/d/vagplace.nl/httpd.www/wp-content/mollie-api-php/src/MollieApiClient.php(409): Mollie\Api\HttpAdapter\CurlMollieHttpAdapter->send('GET', 'https://api.mol...', Array, NULL) #2 /customers/3/5/d/vagplace.nl/httpd.www/wp-content/mollie-api-php/src/MollieApiClient.php(376): Mollie\Api\MollieApiClient->performHttpCallToFullUrl('GET', 'https://api.mol...', NULL) #3 /customers/3/5/d/vagplace.nl/ht in /customers/3/5/d/vagplace.nl/httpd.www/wp-content/mollie-api-php/src/HttpAdapter/CurlMollieHttpAdapter.php on line 111`

**Comment by sandervanhooft** [comment]
Can you try it without the `update` method?

**Comment by helemaaldebom** [comment]
Just did but sadly I get the same result

**Comment by sandervanhooft** [comment]
Ok. I'll need a bit more to go on here.

1. Can you double check you're not resetting the api key somewhere during the procedure, from live back to the test key, or vice versa?

2. Where in this code you shared the exception gets triggered?

```php
$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setApiKey("{LIVE_API}");

// Create Mollie payment
$payment = $mollie->payments->create([
	"amount" => [
			"currency" => "EUR",
		"value" => "10.00",
],
"description" => "VAGplace order",
"redirectUrl" => "{SITE_URL}/mijn-autos/?payment=success&gateway=ideal",
"webhookUrl"  => "{SITE_URL}/mijn-autos/",
"method"      => \Mollie\Api\Types\PaymentMethod::IDEAL,
"metadata" => [
		"email" => $this->purchase_data['user']['email'],
		"date" => $this->purchase_data['date'],
		  ],
]);

$payment = $payment->update();

header("Location: " . $payment->getCheckoutUrl(), true, 303);
}
}

require __DIR__ . "/../../../mollie-api-php/examples/initialize.php";
$payment = $mollie->payments->get($payment->id);

if($payment->isPaid()){
                //execute code after payment has succeeded
            }
```

**Comment by helemaaldebom** [comment]
1. I have checked every file and as far as I can see, I'm not.

2. It doesn't give me a line. Just that message (see screenshot in first message).

3. When I replace `$payment = $mollie->payments->get($payment->id);` with `$payment = $mollie->payments->get('tr_dudK93PwPw')` it works. But I will have the wrong payment ID.
		 //

**Comment by helemaaldebom** [comment]
Solved it. When I removed `$payment = $mollie->payments->get($payment->id);`, it worked.
I have placed that piece of code now right after the `create` array and it works. Thank you for your help, @sandervanhooft

**Comment by sandervanhooft** [comment]
NP, glad you solved it. By the way:

```php
// Create Mollie payment
$payment = $mollie->payments->create([...]);
$payment = $mollie->payments->get($payment->id); // you can drop this call, it's redundant
```
