### ISSUE TITLE
Payment succeeded but Mollie doesn't send 'paid' status to my application

### ISSUE THREAD

**Issue by helemaaldebom** [mollie/mollie-api-php#596]
## Specifications

  - API Version: 2.39.0

## Describe the issue

I have included Mollie API in my website to handle iDeal payments. Paying with iDeal works, Mollie even shows me that the payment has succeeded but still I won't receive a 'paid' status from Mollie.
And for some reason Mollie shows me 2 different payment_id's inside one payment. See screenshot for more information:
<img width="1461" alt="Schermafbeelding 2021-12-25 om 13 22 50" src="https://user-images.githubusercontent.com/5968301/147384765-b85986ce-86de-4e83-b4d9-cb176fb9ae10.png">

I have been dealing with this problem for a few weeks now and I have been unable to fix it. Can someone help me please?

CODE:
```
$mollie = new \Mollie\Api\MollieApiClient();
			 	 $mollie->setApiKey("xxx");

				 // Create Mollie payment
				 $payment = $mollie->payments->create([
				 		"amount" => [
				 				"currency" => "EUR",
								"value" => $prijs,
						],
						"description" => "VAGplace order: ".$orderId,
						"redirectUrl" => "https://vagplace.nl/mijn-autos/?".$orderId,
						"webhookUrl"  => "https://vagplace.nl/webhook.php",
						"method"      => \Mollie\Api\Types\PaymentMethod::IDEAL,
						"metadata" => [
								"payment_id" => $payment->id,
								"order_id" => $orderId,
		        ],
			 	 ]);
				 header("Location: " . $payment->getCheckoutUrl(), true, 303);
			 }
		 }


		 //If payment succeeds, publish package
		 require __DIR__ . "/../../../mollie-api-php/examples/initialize.php";
	 	 $payment = $mollie->payments->get($payment->id);

		 if($payment->isPaid()) {
// DO SOMETHING
}
```

**Comment by MollieRick** [comment]
Hi Bas,

Lets tackle your questions, starting with; 

> Mollie even shows me that the payment has succeeded but still I won't receive a 'paid' status from Mollie.

We send the signal (which is called webhook) to your `webhookUrl`. Based on your screenshot this will be `/webhook.php`. We do not include this in the return since that is not secure. Have you set up there everything correctly?


> And for some reason Mollie shows me 2 different payment_id's inside one payment.

The `metadata` is data that you set by yourself during the creation of your payment. The ID that we assign can you find in the `id` field. In other words; we do not set any `metadata` by ourselves.

Hopefully this helps you. Please also check the following examples in the repo:
* `examples/payments/create-ideal-payment.php`
* `examples/payments/webhook.php`

**Comment by helemaaldebom** [comment]
@MollieRick Thanks for your reply!
Tbh, I didn't know what I should put in the webhook.php so I just copied it.
Is this wrong? And if so, how can I make sure that my application receives a 'paid' response from Mollie?

Webhook.php:
```
try {
    /*
     * Initialize the Mollie API library with your API key.
     *
     * See: https://www.mollie.com/dashboard/developers/api-keys
     */
    require __DIR__ . "/wp-content/mollie-api-php/examples/initialize.php";

    /*
     * Retrieve the payment's current state.
     */
    $payment = $mollie->payments->get($_POST["id"]);
    $orderId = $payment->metadata->order_id;

    /*
     * Update the order in the database.
     */
    //database_write($orderId, $payment->status);

    if ($payment->isPaid() && ! $payment->hasRefunds() && ! $payment->hasChargebacks()) {

      echo 'Paid.';

    } elseif ($payment->isOpen()) {
        /*
         * The payment is open.
         */
    } elseif ($payment->isPending()) {
        /*
         * The payment is pending.
         */
    } elseif ($payment->isFailed()) {
        /*
         * The payment has failed.
         */
    } elseif ($payment->isExpired()) {
        /*
         * The payment is expired.
         */
    } elseif ($payment->isCanceled()) {
        /*
         * The payment has been canceled.
         */
    } elseif ($payment->hasRefunds()) {
        /*
         * The payment has been (partially) refunded.
         * The status of the payment is still "paid"
         */
    } elseif ($payment->hasChargebacks()) {
        /*
         * The payment has been (partially) charged back.
         * The status of the payment is still "paid"
         */
    }
} catch (\Mollie\Api\Exceptions\ApiException $e) {
    echo "API call failed: " . htmlspecialchars($e->getMessage());
}
```

**Comment by MollieRick** [comment]
Hi @helemaaldebom!

The webhook URL will receive the payment ID as a POST request, you should then check the payment status. How this works is described in our documentation; https://docs.mollie.com/overview/webhooks.

**Comment by helemaaldebom** [comment]
@MollieRick I believe I'm checking the payment status but for some reason Mollie doesn't return a 'paid' status. But if I check the Mollie dashboard, I can see that the payment has been paid. I don't know what I'm doing wrong here but the webhook doesn't work in my script. And I have read the documentation and imo I have installed everything correctly. What can I do to make this work? I hve been trying to fix this for weeks now...

**Comment by MollieRick** [comment]
@helemaaldebom We do not give technical support via GitHub. You can try to reach out to our technical support via info[at]mollie.com. 

Please be aware that we do not provide personal support at code level.

Enjoy your evening :-)

**Comment by helemaaldebom** [comment]
Quick update: @MollieRick was right, my webhook wasn't set up correctly. After fixing that, I received that correct status of the payment. Thanks again, @MollieRick!

**Comment by MollieRick** [comment]
Nice to hear @helemaaldebom! Have a great 2022!
