### ISSUE TITLE
Usage of testmode parameter when creating Payments on behalf of other account

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#60]
The ```testmode``` [parameter suggests it is possible to create a payments with a paymentFee in test mode](https://www.mollie.com/en/docs/reference/payments/create#pfp-params)

However, when setting ```testmode``` to TRUE, the following exception is thrown:

```
Mollie_API_Exception: Error executing API call (request): Application feature is not available in test mode.
```

So what is the idea of usage? What *Application feature* is being referred to? Might be useful to include that / detail that in the exception message?

**UPDATE**
When **not** setting the ```applicationFee``` this exception is not thrown, so I guess this is the *Application feature* being referred to. Might be useful to include these details in both the exception message and the documentation...

**Comment by willemstuursma** [comment]
Thanks, we've changed the error message to be more descriptive. Let us know if you have any further issues.

**Comment by holtkamp** [comment]
From the changelog at https://www.mollie.com/en/developers/changelog#2017-07 I derive that ApplicationFees **can** now be used in test mode? Nice!

**Comment by willemstuursma** [comment]
@holtkamp yes, this is correct, we have removed this restriction. Of course it won't move any money but it should help you integrate application fees in your applications. 

Let us know what you need to be successful with our products, we are listening.
