### ISSUE TITLE
Re-enable static analysis with PHPStan

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#603]
## Specifications

  - API Version: 2

## Describe the issue

It seems static analysis using PHPStan is disabled. 

Using PHPStan would have prevented problems like https://github.com/mollie/mollie-api-php/pull/602 at inspection level 2:

```
  Line   src/Resources/Payment.php                                                             
 ------ -------------------------------------------------------------------------------------- 
  287    Property Mollie\Api\Resources\Payment::$routing has unknown class array as its type.  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols   
 ```

It would be nice to re-enable static analysis to prevent such minor problems which have consequences for user land code when running static analysis there, for example I got for my own code:

```
Property Mollie\Api\Resources\Payment::$routing (array|null) does not  accept array|null.
```

A "baseline" can be used to prevent having to fix a lot of issues when starting with PHPStan: https://phpstan.org/user-guide/baseline

**Comment by sandervanhooft** [comment]
Hi @holtkamp ,

Phpstan is triggered only on php7.3 builds and up. What php version are you experiencing the issue with?

**Comment by sandervanhooft** [comment]
👍 Nice suggestion @holtkamp , I am putting that on the backlog to look into.
