### ISSUE TITLE
Missing methods `listFor` and `listForId` in PaymentChargebackEndpoint

### ISSUE THREAD

**Issue by adrenth** [mollie/mollie-api-php#606]
## Specifications

  - API Version: v2.40.2

## Describe the issue

It would be nice to have the methods `listFor` and `listForId` in `\Mollie\Api\Endpoints\PaymentChargebackEndpoint` as well. To be consistent with the `\Mollie\Api\Endpoints\PaymentRefundEndpoint` class.

E.g.

```php

// Get the refunds
$collection = $this->client->paymentRefunds->listForId('tr_....');

// Get the chargebacks
$collection = $this->client->paymentChargebacks->listForId('tr_....');
```

**Comment by sandervanhooft** [comment]
Hi @adrenth !

Thanks for opening this ticket. 

I'll put it on the backlog; feel free to submit a PR if you need the feature sooner.
