### ISSUE TITLE
PHP message: PHP Warning:  curl_getinfo(): supplied resource is not a valid cURL handle resource ...

### ISSUE THREAD

**Issue by newmediacrew** [mollie/mollie-api-php#608]
## Specifications

  - API Version: 2.39.0

## Describe the issue

We got this error message in our nginx logs. Using php 7.4. 

 _FastCGI sent in stderr: "PHP message: PHP Warning:  curl_getinfo(): supplied resource is not a valid cURL handle resource in /var/www/xxx/public_html/wp-content/plugins/xxx/vendor/mollie/mollie-api-php/src/HttpAdapter/CurlMollieHttpAdapter.php on line 135" while reading response header from upstream...._

**Comment by sandervanhooft** [comment]
Hi,

Can you try upgrading to the latest release?
