### ISSUE TITLE
Set customer name for PayPal shipments

### ISSUE THREAD

**Issue by ParadoxNL** [mollie/mollie-api-php#61]
Maybe i missed it, but is it possible to set a name for a PayPal shipment instead of the NOT_PROVIDED message? I've tried by creating a customer and sending that ID with the request but that didn't seem to be it.

![pp shipment](https://cloud.githubusercontent.com/assets/3331772/22619385/e0f60cf0-eaf3-11e6-8839-c0bb8e3d8ec4.png)

**Comment by willemstuursma** [comment]
Thanks, we'll look into it. This probably won't be too hard to change.

**Comment by willemstuursma** [comment]
@ParadoxNL Could you check that it is working for you now? You'll need to send a `customerId` as well as all `shipping*` fields.

**Comment by ParadoxNL** [comment]
Working! Thanks for the fix!

![screen shot 2017-02-24 at 12 40 17](https://cloud.githubusercontent.com/assets/3331772/23302302/7ca398a8-fa8e-11e6-9b73-9beda997a84d.png)
