### ISSUE TITLE
Creating a payment with specified payment method shows incorrect 'back' button

### ISSUE THREAD

**Issue by gvdhoven** [mollie/mollie-api-php#611]
## Specifications

  - API Version: latest

## Describe the issue

Creating a payment using the payment api, with for example a pre-selected iDEAL payment as option shows a button called "Back to payment options" at the bottom of the screen. This assumes that we came from a payment selection screen, which might not be the case in an order flow; e.g. it might be that the previous page was the cart overview, or even an email that contained a link which led to the payment screen.

Therefore, i think it would be a good idea to change the "‹ Betaalmethodes" link to either be not visible, or to "‹ Annuleer" or something in this use-case; because the link of the form is also linking to "https://www.mollie.com/checkout/cancel-precreation/..." --> IF we skipped the payment selection screen that is off course.

**Comment by sandervanhooft** [comment]
Thanks for reporting @gvdhoven . I can confirm this behaviour and it's confusing to me too. Let me check with the team at Mollie.
