### ISSUE TITLE
cURL timeout error message creating new payments

### ISSUE THREAD

**Issue by bedrijfsportaal** [mollie/mollie-api-php#613]
## Specifications

  - API Version: latest

## Describe the issue
I'm receiving timeout errors in cURL request, the status page isn't showing any related issues regarding this? Is this some server setting that needs to be increased or something?

`ERROR - 2022-03-22 20:03:51 --> [2022-03-22T20:03:51+0100] cURL error 28: Resolving timed out after 2000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.mollie.com/v2/payments`

**Comment by bedrijfsportaal** [comment]
Apparently the problem was traced back to the firewall. This caused problems with the connection between Mollie and my application. Since 2 firewalls are already running, the 3rd was also redundant and therefore disabled. Now everything is running as it should!

**Comment by sandervanhooft** [comment]
Thanks for following up @bedrijfsportaal! Glad everything worked out ok.
