### ISSUE TITLE
 PHP Fatal error:  Uncaught Error: Class 'Composer\CaBundle\CaBundle' not found in /var/www/vhosts/websitename/test.websitename/wp-content/plugins/mollie-payments-for-woocommerce/vendor/mollie/mollie-api-php/src/HttpAdapter/CurlMollieHttpAdapter.php:81

### ISSUE THREAD

**Issue by Julianlu1** [mollie/mollie-api-php#616]
API Version: Latest

Hey there,

There is a wordpress website and I already have installed: `Mollie payments for woocommerce`. 

Now I am trying to make use of the mollie api php library, however I get the following error: ` PHP Fatal error:  Uncaught Error: Class 'Composer\CaBundle\CaBundle' not found in /var/www/vhosts/websitename/test.websitename/wp-content/plugins/mollie-payments-for-woocommerce/vendor/mollie/mollie-api-php/src/HttpAdapter/CurlMollieHttpAdapter.php:81
`

I get this error when I try to create a new payment. Creating a new instance and setting the api key is not giving me any errors. However I did not use composer or the manual installation, since I already installed `Mollie payments for woocommerce`.
See code below:

## functions.php
```php
add_action('rest_api_init', 'processPayment');

function processPayment() {
    register_rest_route('payment/v1', 'create', array(
        'methods' => WP_REST_SERVER::CREATABLE,
        'callback' => 'doPayment'
    ));
}
function doPayment() {

$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setApiKey("xxx");
$hostname = $_SERVER['HTTP_HOST'];

$payment = $mollie->payments->create([
        "amount" => [
              "currency" => "EUR",
              "value" => "10.00" // You must send the correct number of decimals, thus we enforce the use of strings
        ],
        "description" => "Order #12345",
        "redirectUrl" => "https://${hostname}/order/12345/",
        "webhookUrl" => "https://${hostname}/payments/webhook/",
        "metadata" => [
              "order_id" => "12345",
        ],
  ]);

  header("Location: " . $payment->getCheckoutUrl(), true, 303);

    return [];
}
```
## Logs
```
[19-Apr-2022 15:02:53 UTC] PHP Fatal error:  Uncaught Error: Class 'Composer\CaBundle\CaBundle' not found in /var/www/vhosts/websitename/test.websitename/wp-content/plugins/mollie-payments-for-woocommerce/vendor/mollie/mollie-api-php/src/HttpAdapter/CurlMollieHttpAdapter.php:81
Stack trace:
#0 /var/www/vhosts/websitename/test.websitename/wp-content/plugins/mollie-payments-for-woocommerce/vendor/mollie/mollie-api-php/src/HttpAdapter/CurlMollieHttpAdapter.php(52): Mollie\Api\HttpAdapter\CurlMollieHttpAdapter->attemptRequest()
#1 /var/www/vhosts/websitename/test.websitename/wp-content/plugins/mollie-payments-for-woocommerce/vendor/mollie/mollie-api-php/src/MollieApiClient.php(538): Mollie\Api\HttpAdapter\CurlMollieHttpAdapter->send()
#2 /var/www/vhosts/websitename/test.websitename/wp-content/plugins/mollie-payments-for-woocommerce/vendor/mollie/mollie-api-php/src/MollieApiClient.php(494): Mollie\Api\MollieApiClient->performHttpCallToFullUrl()
#3 /var/www/vhosts/websitename/test.websitename/wp-content/plugins/mollie-payments-for-woocommerce/vendor in /var/www/vhosts/websitename/test.websitename/wp-content/plugins/mollie-payments-for-woocommerce/vendor/mollie/mollie-api-php/src/HttpAdapter/CurlMollieHttpAdapter.php on line 81
[19-Apr-2022 15:02:53 UTC] PHP Warning:  Cannot modify header information - headers already sent in /var/www/vhosts/websitename/test.websitename/wp-content/plugins/activedemand/ActiveDEMAND.php on line 921
```

Thank you for your help!

Edit: I downloaded the zip, but I have no idea in which folder to put it in my Wordpress or Filezilla files. But I am also not sure if it is needed, since setting the api key did not gave any errors.

Edit2: I moved the `mollie-api-php` folder into my themes folder in FileZilla. Then I required them with `require_once __DIR__ . "/mollie-api-php/vendor/autoload.php";. Now I get a new error in my logs:

## New Logs
```
[20-Apr-2022 12:17:04 UTC] PHP Warning:  Cannot modify header information - headers already sent in /var/www/vhosts/websitename/test.websitename/wp-content/plugins/activedemand/ActiveDEMAND.php on line 921
[20-Apr-2022 12:17:09 UTC] PHP Warning:  Cannot modify header information - headers already sent in /var/www/vhosts/websitename/test.websitename/wp-content/plugins/activedemand/ActiveDEMAND.php on line 921
[20-Apr-2022 12:17:09 UTC] PHP Fatal error:  Uncaught Mollie\Api\Exceptions\ApiException: [2022-04-20T12:17:09+0000] Error executing API call (422: Unprocessable Entity): No suitable payment methods found. Documentation: https://docs.mollie.com/overview/handling-errors. Request body: {"amount":{"currency":"EUR","value":"10.00"},"description":"Order #12345","redirectUrl":"https:\/\/test.websitename\/order\/12345\/","webhookUrl":"https:\/\/test.websitename\/payments\/webhook\/","metadata":{"order_id":"12345"}} in /var/www/vhosts/websitename/test.websitename/wp-content/themes/porto/mollie-api-php/src/HttpAdapter/CurlMollieHttpAdapter.php:178
Stack trace:
#0 /var/www/vhosts/websitename/test.websitename/wp-content/themes/porto/mollie-api-php/src/HttpAdapter/CurlMollieHttpAdapter.php(102): Mollie\Api\HttpAdapter\CurlMollieHttpAdapter->parseResponseBody()
#1 /var/www/vhosts/websitename/test.websitename/wp-content/themes/porto/mollie-api-php/src/HttpAdapter/CurlMollieHttpAdapter.php(45): Mollie\Api\HttpAdapter\CurlMollieHttpAdapter->attemptRequest()
#2  in /var/www/vhosts/websitename/test.websitename/wp-content/themes/porto/mollie-api-php/src/HttpAdapter/CurlMollieHttpAdapter.php on line 178
```

**Comment by sandervanhooft** [comment]
Hi!

Essentially mollie-api-php verifies each request to the Mollie Api using the composer ca bundle package. It looks like your instance cannot find it. Can you try installing the composer ca package manually?

https://github.com/composer/ca-bundle

**Comment by sandervanhooft** [comment]
Your latest edit shows an error message saying that no eligible payment methods are enabled on your account.

Payment methods can be enabled in the Mollie dashboard.

On live mode, it can take a while before they're verified and enabled. On test mode, payment methods are enabled instantaneous.

**Comment by Julianlu1** [comment]
Hey Sander, thanks for your answer! Yeah I manually installed `mollie-api-php` and I enabled the payments methods and now it is working 👍 . I do have two questions  that I would like to ask you that I am a bit confused about:
- Should I now just return the checkoutUrl like such: `return $payment->getCheckoutUrl();`. I tried `  header("Location: " . $payment->getCheckoutUrl(), true, 303);` but this did not work for me
- There is an order endpoint in WooCommerce (https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order) and there is an order endpoint in Mollie (https://docs.mollie.com/reference/v2/orders-api/create-order). Which one should I call (before the payment endpoint). Or should I call both?

Thanks!

**Comment by sandervanhooft** [comment]
1. Have you tried the header statement without using a return?

2. I cannot help you with WooCommerce specifics, sorry.

**Comment by sandervanhooft** [comment]
PS: you either use Mollie's Orders endpoint, or the Payments endpoint. Not both.

**Comment by sandervanhooft** [comment]
Closing this for now. For additional issues please open a new issue ticket.

**Comment by Julianlu1** [comment]
Quick question, `
PS: you either use Mollie's Orders endpoint, or the Payments endpoint. Not both.`. Does this mean, that when I create an order, it will create a payment automatically?
And if I create a payment, it creates an order automatically?

**Comment by sandervanhooft** [comment]
That's right!

https://docs.mollie.com/orders/overview

**Comment by sandervanhooft** [comment]
> And if I create a payment, it creates an order automatically?

No.
