### ISSUE TITLE
Error executing API call (422: Unprocessable Entity): This order cannot be shipped..

### ISSUE THREAD

**Issue by Julianlu1** [mollie/mollie-api-php#617]
Hey there,

I am trying to create an order with shipping details and shipping costs. The steps that I do:
1. Create the order
2. Put order id in the variable
3. Call `createShipment` on that order

I was looking to add a parameter in the `orders->create` method, but I could not find any parameter related to shipping cost. Then I looked further and noticed the `createShipment` method (https://docs.mollie.com/reference/v2/shipments-api/create-shipment). When I try to execute the `createShipment` method, I get the following error message: `Error executing API call (422: Unprocessable Entity): This order cannot be shipped..`.

Is this the correct way? If so, what am I doing wrong? 
**FYI**: In wordpress, there is a shipment method selected and available.

Thanks for your help!

**Comment by Julianlu1** [comment]
Hi @sandervanhooft,

Yes I did that. I set the mollie status to paid (I went through the test payment process) and it does get rid of the error actually. However the shipping costs are not added into the order information.

See image for easy understanding: https://imgur.com/a/WJ6EwLP

**Comment by sandervanhooft** [comment]
Can you share some code that reproduces the issue?

**Comment by Julianlu1** [comment]
When creating the order, I do not add any shipping costs. After the order is created, I try to call `$mollie_order->createShipment` to add the shipping cost to that order.

A line contains an id of the product and a quantity, just like the documentation is saying: https://docs.mollie.com/reference/v2/shipments-api/create-shipment.

So the desired result should be: order created, and then shipping costs are added to that specific order.

**Comment by sandervanhooft** [comment]
Hi @Julianlu1 ,

The shipping costs should be part of the order lines, so it's being paid for when going through Mollie's checkout.

**Comment by Julianlu1** [comment]
Hi @sandervanhooft,

Hmm okay, that does make sense. I suppose you mean it should be part of `"lines" => $product_lines`  in the `$mollie->orders->create` method.

But where should I add the shipping costs? Currently one product line looks like this:
```php
	$product_line = [
			"sku" => $sku,
			"name" => $productName,
			"quantity" => $quantity,
			"vatRate" => round($vat_rate),
			"unitPrice" => [
				"currency" => "EUR",
				"value" => $productPrice
			],
			"totalAmount" => [
				"currency" => "EUR",
				"value" => number_format((float)$total_amount,2, '.', '')
			],
			"vatAmount" => [
				"currency" => "EUR",
				"value" => number_format((float)$vat_amount_total,2, '.', '')
			]
                        // Should I add the following shipping object here?
                        "shippingCost" => [
				"methodId" => "dhlpwc",
				"total" => "6.95"
			]
		];
```

Do I need to add the shipping cost per product? Normally the shipping costs is for all of the products right? I don't see any documentation on how to add the shipping cost in the order lines: https://docs.mollie.com/reference/v2/orders-api/create-order. Can you help me out with this?

Thanks.

**Comment by sandervanhooft** [comment]
The documentation page you're referencing offers child parameter specifications for `lines`.

The line type can be set to `shipping_fee`.

The exact configuration (single or multiple shipping fees) is up to you. 😄

**Comment by Julianlu1** [comment]
I indeed see `shipping_fee`, I will check it out and will let you know if it works :)

**Comment by Julianlu1** [comment]
Hey, @sandervanhooft Thanks for the help! I got it working now. The shipping costs are now included and can be seen in the mollie dashboard. Appreciate it very much :)

**Comment by sandervanhooft** [comment]
Glad to be of service. Enjoy!

**Comment by Julianlu1** [comment]
Thanks!
