### ISSUE TITLE
How can I know if the payment passed or failed after the payment is done with redirect or webhook url?

### ISSUE THREAD

**Issue by Julianlu1** [mollie/mollie-api-php#618]
Hi,

I made it possible to send the user back to the app after a payment, but I am struggling to redirect the user to the correct `app screen` (success screen or payment failed screen). After the `order` is created, a payment url is sent to the `client`. He then pays or declines the payment. How can I redirect the user with a parameter that says `success` or `failed`, since there is only 1 redirectUrl.

```php
 "redirectUrl" => "https://example.org/redirect",
 "webhookUrl" => "https://example.org/webhook",
```

I read that the `webhookUrl` is used to check for updates. This `url` will get called when the status of an order updates. The client then can listen for changes on that url.

Do I need to listen on the `webhookUrl`? Or can I pass a parameter to `redirectUrl`, however I do not know if the payment is `success` or `failed`.

Or do I need to call `get payment` directly after I redirected the user? https://docs.mollie.com/reference/v2/payments-api/get-payment 

Thank you!

**Comment by sandervanhooft** [comment]
Hi @Julianlu1 ,

This is how I usually solve this:

1. Redirect the user to something like a `ReturnFromMollieController` in your app.
1. In that controller, retrieve the payment from Mollie and check the payment status.
1. Depending on the payment status: display the correct message / redirect to the right page in your app.

**Comment by Julianlu1** [comment]
Hey Sander,

Thanks for your answer. I am still trying to implement your method. I will let you know when it works or if I am running into problems.

**Comment by sandervanhooft** [comment]
Great!

Closing this for now, let me know if it should be reopened.

**Comment by Julianlu1** [comment]
Yeah that's fine! Will let you know.
