### ISSUE TITLE
 Page Not Found!

### ISSUE THREAD

**Issue by vikingvoorhees** [mollie/mollie-api-php#622]
## Specifications

  - API Version: 

## Describe the issue

Hi there. apologies i have no tech experience. i've installed the mollie extension. also when i hit install, i get an error page. But when i refresh and go back to the payments list. Mollie is there and installed. when i go to edit it. it opens up but shows a Page not found message at the top to the left of the admin dashboard and a message saying The page you are looking for could not be found! Please contact your administrator if the problem persists.

Im using opencart 2.1.0.1

**Comment by sandervanhooft** [comment]
Hi @vikingvoorhees ,

This seems to be an issue with Mollie OpenCart. Can you post this issue there?

https://github.com/mollie/OpenCart

Thanks!
