### ISSUE TITLE
Invalid payment ID. A payment ID should start with 'tr_'.

### ISSUE THREAD

**Issue by Broder1991** [mollie/mollie-api-php#624]
## Specifications

  - API Version: V2

## Describe the issue

Create payment call is successful, with webhook url specified. When I set the payment id to post id i get these message:

Warning: Undefined array key "id"
API call failed: [2022-05-26T08:44:14+0000] Invalid payment ID: ". A payment ID should start with 'tr_'.

I have made a conditional to see if the id is getting posted to my webhook url:

`
if(isset($_POST['id'])):
$payment  = $mollie->payments->get($_POST['id']);
else: 
$payment  = $mollie->payments->get('12345');
endif;
`

This returns 12345 so no.

However if I manually add the order id like so: 
`$payment  = $mollie->payments->get('tr_example');`

It does work, and no errors are displayed. So that means data is posted, otherwise I wouldn't get the payment status? 

What am I doing wrong?

**Comment by sandervanhooft** [comment]
Hi @Broder1991 ,

This indeed seems to signal that  $_POST can be accessed but there is no id element defined.

1. What stack are you using?
2. How is this code triggered exactly? I.e. by Mollie calling the webhook, local Postman/curl, automated test?
3. Can you dump and share $_POST here in a human readable manner?

**Comment by Broder1991** [comment]
Hi, 

1. I´m running Wordpress with the PHP library 
2. Code gets triggered by Mollie calling webhook, to manually add a valid order ID for testing purposes I used postman to get it 
3. array (size=0)
  empty, which is weird, because it includes the payment status below that

**Comment by sandervanhooft** [comment]
Can you share a screenshot of your Postman setup?

**Comment by Broder1991** [comment]
Sorry for not replying sooner, this was an error on my end end and now is resolved. I do want to ask something quick, if you don't mind. Is there way in library to get the credit card error message based on payment id e.g. $mollie->$payments ->$details->$failureReason or something like that?

**Comment by Yorgv** [comment]
I'm sorry to bring up such an old issue, but I'm having the same problem. Can you elaborate what went wrong on your end?
I'm having the same issue. 9 times out of 10 it works, but sometimes I get `Invalid payment ID: ''. A payment ID should start with 'tr_'`

The payment is created successfully, but it seems to go wrong when redirecting to the /success route. In [MolliePayment](https://github.com/bagisto/bagisto-mollie-payment/blob/master/src/Payment/Molliepayment.php#L74) the payment ID gets put in the session, but it seems it's not found in the session in the [MollieController](https://github.com/bagisto/bagisto-mollie-payment/blob/master/src/Http/Controllers/MollieController.php#L92).

I'm currently going to try to pass the ID in another way to the MollieController to see if that could help.

**Comment by Naoray** [comment]
Hi @Yorgv,

This seems to be a problem related to the repository code that you are using.

Please ask this question on the [Bagisto repository](https://github.com/bagisto/bagisto-mollie-payment)
