### ISSUE TITLE
missing @thows tag

### ISSUE THREAD

**Issue by mPetzol** [mollie/mollie-api-php#626]
## Specifications

  - API Version: 2.44.1

## Describe the issue

missing @throws ApiException in Resources\Order::shipAll()

    /**
     * Create a shipment for some order lines. You can provide an empty array for the
     * "lines" option to include all unshipped lines for this order.
     *
     * @param array $options
     *
     * @return Shipment
     * @throws ApiException
     */
    public function createShipment(array $options = [])
    {
        return $this->client->shipments->createFor($this, $this->withPresetOptions($options));
    }

    /**
     * Create a shipment for all unshipped order lines.
     *
     * @param array $options
     *
     * @return Shipment
     */
    public function shipAll(array $options = [])
    {
        $options['lines'] = [];

        return $this->createShipment($options);
    }

**Comment by sandervanhooft** [comment]
Thanks. Feel free to send in a PR
