### ISSUE TITLE
How i can update client bank information ? in case of current subscription.

### ISSUE THREAD

**Issue by DiegoFirmiano** [mollie/mollie-api-php#636]
## Specifications

  - API Version:  V2

## Describe the issue

The customer lost his bank card, he wants to update his subscription with his new card.

What do I do in this case? 

Thanks

**Comment by sandervanhooft** [comment]
Hi @DiegoFirmiano ,

Thanks for reaching out and sorry for the delay.

You can create a new mandate using a new `first` payment (make sure to send along the same Mollie customerId for this customer), then update the `mandateId` on the subscription.

Does that answer your question?

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
