### ISSUE TITLE
description from type order

### ISSUE THREAD

**Issue by vacla** [mollie/mollie-api-php#640]
## Specifications

  - API Version: v2.42.1
  - Mollie/magento2 : 2.16.0

## Describe the issue

Can not get the description from type order, in this case this is a klarna pay later payment method.

In the image below, I want to get "Bestellung TEST6000000755" using the order resources.

![Screenshot from 2022-09-21 17-53-01](https://user-images.githubusercontent.com/10290022/191554381-a1c78f47-7b65-488b-89fb-d6433cc01e48.png)

**Comment by sandervanhooft** [comment]
Hi @vacla ,

Thanks for reaching out.

1. You're referencing the `mollie/magento2` package instead of this repository's `mollie/mollie-api-php` package, is that correct?
2. What have you tried so far? Can you share a code sample?

**Comment by vacla** [comment]
@sandervanhooft 

1. Yes that is correct but the issue is underlaying in the mollie/mollie-api-php package it seems
2.  We got this atm, this works if it is a "payment" type but this won't work if it is an order type and it will say that description doesn't exists

` 
$mollieOrder = $mollieApi->orders->get($transactionId, ['embed' => 'payments']);

            /** @var Payment $payment */
            $payment = $mollieOrder->payments()->offsetGet(0);
            $metadata = $payment->metadata ?? new \stdClass();
            $metadata->refunded = true;
            $payment->metadata = $metadata;
            $payment->update();

            $description = ['description' => 'XXXX Refund ' . $mollieOrder->description];
            if ($order->getState() === Order::STATE_CLOSED) {
                $mollieOrder->refundAll($description);
            } else {
                $orderLines = $this->orderLines->getCreditmemoOrderLines($creditmemo, $addShippingToRefund);

                $mollieOrder->refund(array_merge($description, $orderLines));
            }
`

**Comment by vacla** [comment]
Is there any update on this?

**Comment by sandervanhooft** [comment]
Hi @vacla, The description only exists on the (related) payments. You can either use that or the order's orderNumber attribute.
