### ISSUE TITLE
Catch refund status

### ISSUE THREAD

**Issue by SDanDyS** [mollie/mollie-api-php#641]
## Specifications

  - API Version:  2

## Describe the issue
I have a webhook which should catch the refunded status once it reaches "refunded". I see the webhook gets called correctly and I see in mollie a refunded status. However the status change never comes through. The docs state the payment remains as "paid", but does this mean when the webhook is called the status property is classified as "paid"? In the docs of refund it states that refunds do have their own status https://docs.mollie.com/payments/refunds. So what happens with this refund status? Maybe even a bold question, but: Why doesn't Mollie return a payment status of "refunded" when the webhook gets called?
Could anyone confirm that when the webhook gets called successfully when the payment becomes "refunded", the payment status it sends to the webhook remains as "paid"? If so, I could set it to refunded myself, but right now the docs are confusing to me.

A piece of a code I use which should confirm the status remains as paid (and comes straight out of the examples) when the webhook gets called would be:

```
 elseif ($this->payment->hasRefunds()) {
                    $this->has_refunds();
                    /*
                     * The payment has been (partially) refunded.
                     * The status of the payment is still "paid"
                     */
                } else
                {
                    // Both here and in the elseif block above I insert payment->status into the db, but it remains paid.
                }
```

**Comment by sandervanhooft** [comment]
Hi @SDanDyS,

You're correct, the status of the payment remains `paid`. Semantically, the payment remains paid.

Best is to check and track the status of each related refund and chargeback when the webhook gets called. Note that there can be multiple refunds (and theoretically chargebacks) on a payment.

The webhook request payload intentionally is minimal for security reasons, as to not leak any details about what is going on.

We'll take a look at the sample code, looks like a mistake has slipped in porting it over from v1. Thank you for noticing.

**Comment by SDanDyS** [comment]
Hi @sandervanhooft _"You're correct, the status of the payment remains paid. Semantically, the payment remains paid."_, so even when the webhook gets called it returns a "paid" status. That's good to know, at least I know I am not missing something. I would also like to clarifiy that the `$this->has_refunds()` is of my own class, just to make sure you or any further readers do not confuse it with Mollie their code. _"Note that there can be multiple refunds (and theoretically chargebacks) on a payment."_ correct, thank you. In my system this won't be the case, so all I need is the webhook to call and eventually be able to detect there was a refund on that payment.
