### ISSUE TITLE
Feature request: Call webhook informatie for payment(s)

### ISSUE THREAD

**Issue by erikkraijenoord** [mollie/mollie-api-php#643]
## Specifications
Read webhook events from a payment with transaction ID to determain if something hasn't worked correctly or stopped for some reason. The only possible way at this moment is on the user account itself and we do not have access to our clients only by oAuth2.

  - API Version: 2.46.0

## Describe the issue
We would like to be able to read the webhook events on a payment, this way we can show and/or read the information behind it.
For example (my 2-cents):

```php
$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setAccessToken('access_xxxxxxxxxx');

try {

    $webhook = $mollie->webhooks->get('tr_xxxxx', /*attr*/);
    print_r($webhook); // Webhook events
}
catch(\Mollie\Api\Exceptions\ApiException $e) {
    die( $e->getMessage() );
}

**Comment by sandervanhooft** [comment]
Marking this as a feature request.

**Comment by sandervanhooft** [comment]
This feature request has found its way to Mollie's product teams and will be further investigated. Closing this issue here.
