### ISSUE TITLE
Can't test payment checkout

### ISSUE THREAD

**Issue by alecpl** [mollie/mollie-api-php#648]
Sorry for using improper channel, but I feel I might get a developer support here faster than via the Mollie webpage.

So, I had my checkout tests working according to https://docs.mollie.com/overview/testing and the form used to look like in the documentation, but for a few months now it does not work. The form is different.
![mollie](https://user-images.githubusercontent.com/546788/202463856-a634aeba-acd4-499b-8ef1-5f32c44a7c9c.png)

So, it mentions test mode, but does not contain the documented fields for a test mode checkout form.

I see nothing in the changelog, so is it a Mollie bug or mine?

**Comment by sandervanhooft** [comment]
Hi!

This has changed on Mollie's end, particularly testing the creditcard flow.

Best to follow the component testing guide (card numbers) here: https://docs.mollie.com/components/testing

**Comment by alecpl** [comment]
Thanks, I'll see if I can make it working with the special credit card numbers. But why https://docs.mollie.com/overview/testing#test-mode-checkout-screen still exists then?

**Comment by sandervanhooft** [comment]
That testmode screen is still suited to most other payment methods at the moment. The docs could be clearer on this, let me raise an issue there.

**Comment by alecpl** [comment]
One more issue. If I do payment with the test visa card `4543 4740 0224 9996` it works, but with a small issue. After the payment, Mollie UI, as well as the API says it's Mastercard not Visa.

**Comment by sandervanhooft** [comment]
@Timollie can you take a look when you have a moment?

**Comment by robindirksen1** [comment]
Had the same issue with iBANs a few months ago, where the test said ING instead of the expected Rabobank (didn't test this recently).

**Comment by amadeann** [comment]
The same issue reported in Python client repo:
https://github.com/mollie/mollie-api-python/issues/261
