### ISSUE TITLE
Mijn webhook verandert de status in mijn MySql database niet

### ISSUE THREAD

**Issue by Djazz1995** [mollie/mollie-api-php#65]
Ik ben bezig met het implementeren van de mollie API op mijn website, maar ik heb problemen met de webhook. Het lijkt erop dat de webhook helemaal niet wordt aangeroepen. De url die ik meegeeft aan create-payement klopt en kan ook bereikt worden door de mollie servers(denk ik). Ik run mollie in test modus.

Het script van de webhook klopt en update wel de database wanneer ik een hard coded order_id in het script zet in plaats van de `$payment  = $mollie->payments->get($_POST["id"]);`.

Alvast bedankt!
Hieronder mijn webhook code:

```
/*
 * Example 2 - How to verify Mollie API Payments in a webhook.
 */
try
{
	/*
	 * Initialize the Mollie API library with your API key.
	 */

	include "initialize.php";
	
	/*
	 * Check if this is a test request by Mollie
	 */
	if (!empty($_GET['testByMollie']))
	{
		die('OK');
	}

	/*
	 * Retrieve the payment's current state.
	 */

	$payment  = $mollie->payments->get($_POST["id"]);


	$order_id = $payment->metadata->order_id;
	$email_cust = $payment->metadata->email;
	/*
	 * Update the order in the database.
	 */
	$status = $payment->status;
	$update_order_state = mysqli_prepare($mysqli, "UPDATE orders SET status = ? WHERE order_id = ? ");
	if($update_order_state){
		$update_order_state->bind_param('ss', $status, $order_id);
		$update_order_state->execute();
	} else{
		echo $mysqli->error;
		echo "could not update status";
	}
	
	if ($payment->isPaid() == TRUE)
	{
			echo "payment has been paid";
	}
	elseif ($payment->isOpen() == FALSE)
	{
			echo "payment is not open and most likely aborted";
	}
}
catch (Mollie_API_Exception $e)
{
	echo "API call failed: " . htmlspecialchars($e->getMessage());
}
```

**Comment by ndijkstra** [comment]
Hallo! Zou je een e-mail kunnen sturen met je Mollie Partner ID naar techsupport@mollie.com? Dan kijk ik even in je account wat wij voor foutmelding terugkrijgen.

**Comment by jimkaler** [comment]
i am getting same issue in laravel.
