### ISSUE TITLE
BUG: Wrong return values introduced in 2.49.0

### ISSUE THREAD

**Issue by Fahl-Design** [mollie/mollie-api-php#656]
## Specifications

  - API Version: 2.49.X

## Describe the issue

this commit changed some "chargebacks" returns

[https://github.com/mollie/mollie-api-php/commit/e3ccef19d70001a80def5f75cbe542e5a7b71083#diff-a5411460cae505a2d53740a[…]e450e32f7002fb4380078e74f1b0](https://github.com/mollie/mollie-api-php/commit/e3ccef19d70001a80def5f75cbe542e5a7b71083#diff-a5411460cae505a2d53740a8592316097d06e450e32f7002fb4380078e74f1b0)

eg:
`\Mollie\Api\Resources\Settlement::chargebacks`
-> should always return `ChargebackCollection` and NOT `BalanceCollection` OR `ChargebackCollection`
-> OR return annotation dose not match, but looks like a refactor problem

maybe use some phpstan magic to verify

**Comment by sandervanhooft** [comment]
Thanks for reporting!

I've found the issue, will try to patch later this evening.

**Comment by sandervanhooft** [comment]
Here you go!

https://github.com/mollie/mollie-api-php/releases/tag/v2.49.1
