### ISSUE TITLE
whereStatus on MandateCollection doesn't change count

### ISSUE THREAD

**Issue by JeroenVanOort** [mollie/mollie-api-php#658]
## Specifications

  - API Version: latest

## Describe the issue
I'm trying to check if a customer has a valid mandate. So I filter the MandateCollection using it's whereStatus function and check if count > 0. However, the new collection created by whereStatus always has the same count as the original collection. See: https://github.com/mollie/mollie-api-php/blob/34ad0d291b9d394ce1199f166ca51d68f5e05ab3/src/Resources/MandateCollection.php#L29

I don't have the time to fix this right now but I did want someone to know about this.

**Comment by sandervanhooft** [comment]
Fixed! Thank you for reporting @JeroenVanOort
