### ISSUE TITLE
API latency degration lead to duplicate payments: increase timeout?

### ISSUE THREAD

**Issue by Epskampie** [mollie/mollie-api-php#663]
Hi, januari 6 there was some latency degration on the API: https://status.mollie.com/

![Selection_016](https://user-images.githubusercontent.com/1692043/211601585-1f956991-d2c9-4836-9546-1928941c474b.png)

This led to some duplicate payments on our end, and after some digging we found: 
```
/**
     * Default response timeout (in seconds).
     */
    public const DEFAULT_TIMEOUT = 10;
```
in `CurlMollieHttpAdapter.php`.

It may be prudent to increase the timeout to something like 30 seconds, perhaps only on POST/PUT etc requests to prevent problems like this.

What do you think?

**Comment by robindirksen1** [comment]
Saw this (https://github.com/mollie/mollie-api-php/pull/639) a few weeks ago. 

Question for @sandervanhooft @mollierobbert; is this supported/ready-to-use to avoid duplicate payments?

**Comment by mollierobbert** [comment]
It's in open beta, but results are favorable so far. There's a high likelihood of us moving from open beta to public without further changes to the interface.

**Comment by sandervanhooft** [comment]
Closing this for now with idempotency in open beta, let me know if it should be reopened.
