### ISSUE TITLE
Rework the usage of dynamic properties

### ISSUE THREAD

**Issue by bobvandevijver** [mollie/mollie-api-php#671]
With PHP8.2 the usage of dynamic properties is deprecated. It would be best to no longer use them at all, but otherwise some care should probably be taken to identify the classes where this issue might arise (such as the dynamic API resource converters) and just add the [AllowDynamicProperties](https://www.php.net/manual/en/class.allowdynamicproperties.php) attribute.

**Comment by sandervanhooft** [comment]
Thanks for reporting @bobvandevijver .

Fixed in [the latest release](https://github.com/mollie/mollie-api-php/releases/tag/v2.52.1)
