### ISSUE TITLE
Bug in refunds example

### ISSUE THREAD

**Issue by vliegelientje** [mollie/mollie-api-php#675]
## Specifications

  - API Version: 2.53.0

## Describe the issue

Found a bug in the refunds example (/examples/payments/refund-payment.php)

`if ($payment->canBeRefunded() && $payment->amountRemaining->currency === 'EUR' && $payment->amountRemaining->value >= '2.00') {`

For example if the remaining value is 109 euro and a refund of 2 euro is requested, it will not match the condition. Note that "109.00" < "2.00", but floatval("109.00") > 2. 

So I'd suggest to: 

`if ($payment->canBeRefunded() && $payment->amountRemaining->currency === 'EUR' && floatval($payment->amountRemaining->value) >= 2) {`

**Comment by Naoray** [comment]
Hi @vliegelientje,

Thank you for bringing to our attention that there is a case in our examples where we compare two strings. I’ve updated the code in #676.

Note however, that in your mentioned case the if statement would still result in a truthy condition and therefore not produce any bug. 

`’109.00’ >= ‘2.00’ // is true`
