### ISSUE TITLE
$response->getBody()->getContents() returns empty value

### ISSUE THREAD

**Issue by Thedonsolo** [mollie/mollie-api-php#679]
Version: 1.0.3
in Payment: createFromResponse, the response is handled as:
        $response = json_decode($response->getBody()->getContents());
This returns an empty value.
When changing to below, it works: 
        $response = json_decode($response->getBody()->__toString());

Any idea?

**Comment by sandervanhooft** [comment]
Not sure why you'd need it, but the `getContents()` returns a `StreamInterface`. The `__toString()` is a shortcut to turn that into a string.
