### ISSUE TITLE
No paymentURL when payment is not paid?

### ISSUE THREAD

**Issue by nvomedia** [mollie/mollie-api-php#68]
When a payment is not successful ( != paid) there is no paymentUrl in the links in paymentObject. How can I let my customers try again by simply clicking on 'click here to try again'. ?

```
Mollie_API_Object_Payment Object
(
    [resource] => payment
    [id] => xxxxxx
    [mode] => live
    [amount] => 4.00
    [amountRefunded] => 
    [amountRemaining] => 
    [description] => xxxxxx
    [method] => ideal
    [status] => cancelled
    [expiryPeriod] => 
    [createdDatetime] => 2017-04-18T20:46:39.0Z
    [paidDatetime] => 
    [cancelledDatetime] => 2017-04-18T20:46:49.0Z
    [expiredDatetime] => 
    [profileId] => xxxxxx
    [customerId] => 
    [recurringType] => 
    [mandateId] => 
    [subscriptionId] => 
    [locale] => nl
    [metadata] => 
    [details] => 
    [links] => stdClass Object
        (
            [redirectUrl] => xxxxxxx
        )

    [countryCode] => NL
    [issuer] => ideal_ABNANL2A
)
```

**Comment by ndijkstra** [comment]
Hi!

We only have a redirectUrl. You have to check on that page if the payment is failed or succeed. You can find more info in this issue: #18

**Comment by nvomedia** [comment]
So, I have to create an new payment for those payments?

**Comment by ndijkstra** [comment]
That's correct. If a payment failed, the status can't go back to open: https://www.mollie.com/nl/docs/status#how-does-one-status-lead-to-another

**Comment by nvomedia** [comment]
That's clear. Thanks!
