### ISSUE TITLE
Mandate: Pending

### ISSUE THREAD

**Issue by petericebear** [mollie/mollie-api-php#69]
Hi,

When does a mandate gets the status 'pending'?
I have searched the docs, and found the pending status for a payment, but not for a mandate.

Thanks in advance,
Peter

**Comment by Smitsel** [comment]
Sorry for the late response.

Although the when of status pending is not documented explicitly you can read about how this works in our recurring payments guide: https://www.mollie.com/nl/docs/recurring#subscriptions

When setting up a subscription a mandate is created, when there is no first payment present this mandate will be pending until the first payment has been created.

Hope this helps!

**Comment by Smitsel** [comment]
Since this was not explicitly documented i added this to our API Reference.
https://www.mollie.com/nl/docs/reference/mandates/get
