### ISSUE TITLE
Orders API: CancelUrl not working for payment method "PayPal"

### ISSUE THREAD

**Issue by philippbuerger** [mollie/mollie-api-php#696]
## Specifications

  - API Version: v2

## Describe the issue

We are using the Mollie hosted checkout with the orders api. When creating an order we set the cancelUrl to our checkout overview so when the customer cancels the payment, he should be redirected back to the checkout. This works perfect in the most cases. But when the customer first selects the payment method "PayPal" and after that using the links at the bottom of the Mollie checkout page to "cancel" the payment, the customer isn't redirected to the cancelUrl but to the redirectUrl.

**Comment by sandervanhooft** [comment]
Hi @philippbuerger,

Thanks for reporting. The issue is being investigated.

**Comment by philippbuerger** [comment]
Why is this closed? Is it fixed now? @Naoray @sandervanhooft

**Comment by sandervanhooft** [comment]
Hi @philippbuerger ,

It's not an issue with this repository.
