### ISSUE TITLE
API call failed: Error executing API call (request): The webhook location is invalid.

### ISSUE THREAD

**Issue by sjorsvanheuveln** [mollie/mollie-api-php#70]
When I try to run the examples I'm getting this error. My PHP error log is not showing errors. What is going wrong?

**Comment by sjorsvanheuveln** [comment]
Nevermind, I tried it on a local adress. That must be the issue.

**Comment by sjorsvanheuveln** [comment]
Never mind, I was calling to a localhost. Oops :D. It's working now. Thank you.

**Comment by jimkaler** [comment]
how did you solve that issue while using localhost?

**Comment by sjorsvanheuveln** [comment]
Well the whole localhost thing is the problem. Mollie can't do a callback to a localhost as the server doesn't know where that is. You have to let it call a reachable IP address.

**Comment by jimkaler** [comment]
yes @sjorsvanheuveln i've implement it on testing server now.
But getting error : "trying to get property of non-object", while using 
$payment = $mollie->payments->get($payment->id);
I don't know why its giving me error when i try to update DB using webhook.

**Comment by sjorsvanheuveln** [comment]
Can you share your code, it's hard to interpret from here.

**Comment by arendvw** [comment]
> $payment = $mollie->payments->get($payment->id);

You're using the $payment variable before you've defined it?

**Comment by jimkaler** [comment]
Code of creating payment in mollie: 

![screenshot from 2018-04-11 15-55-44](https://user-images.githubusercontent.com/36437555/38611302-ef7b9d8e-3da0-11e8-8fa7-05280abea34c.png)


Code of Webhook function 

![screenshot from 2018-04-11 15-56-02](https://user-images.githubusercontent.com/36437555/38611334-00e52342-3da1-11e8-90e1-b2c5977b3434.png)

**Comment by jimkaler** [comment]
@arendvw  and @sjorsvanheuveln . Please tell me is it enough for let you know what I am doing?
