### ISSUE TITLE
Missing Fields in Capture PHP Class Relative to JSON Documentation

### ISSUE THREAD

**Issue by pepeh** [mollie/mollie-api-php#708]
## Specifications

  - API Version: 2

## Describe the issue
Upon integrating the Mollie API SDK for PHP, I noticed that there are discrepancies between the JSON response [documented for captures](https://docs.mollie.com/reference/v2/captures-api/get-capture) and the `Capture` [class in the PHP SDK](https://github.com/mollie/mollie-api-php/blob/master/src/Resources/Capture.php). Specifically, there are fields present in the JSON response that are not available or represented in the `Capture` class, potentially leading to incomplete data handling or missing functionality for developers utilizing the SDK.

### Identified Missing Fields

- **`status`**: The JSON documentation includes a `status` field indicating the status of the capture (e.g., "succeeded"), but this field is not present in the `Capture` PHP class. This field is crucial for understanding the state of a capture.

- **`metadata`**: The JSON example includes a `metadata` field that allows for the storage of additional information associated with the capture.

**Comment by maria-swierblewska** [comment]
Hi @sandervanhooft could you have a look into this?

**Comment by sandervanhooft** [comment]
Thanks for opening this ticket @pepeh !

I'll add the fields. Note that it will only help the IDE experience (autocomplete/hints) as Mollie's json response fields are assigned dynamically here.

**Comment by sandervanhooft** [comment]
Here it is! 

https://github.com/mollie/mollie-api-php/releases/tag/v2.66.0
