### ISSUE TITLE
Error "Class "GuzzleHttp\ClientInterface" not found" - in production

### ISSUE THREAD

**Issue by yachtino-dev** [mollie/mollie-api-php#710]
## Specifications

  - API Version: 2.66.0

## Describe the issue

I integrated Mollie payments in my project (no framework, own programming). In my composer.json is:

```
"require": {
	"php": ">=8.0 <9",
	...
	"mollie/mollie-api-php": "^2.66",
},
```
No require-dev.

On production server I get error:
`Class "GuzzleHttp\ClientInterface" not found (file GuzzleHttp/ClientInterface.php).`
Comming from:
`/vendor/mollie/mollie-api-php/src/HttpAdapter/MollieHttpAdapterPicker.php(45): interface_exists('\\GuzzleHttp\\ClientInterface')`

In Mollie, the dependency of Guzzle is only in require-dev. Why it is required in production?
What helped was that I added Guzzle to my own composer.json, so the class is loaded.
Is it not a bug?

**Comment by sandervanhooft** [comment]
Hi @yachtino-dev,

Thanks for reaching out.

The package is detecting whether Guzzle is present, and should fall back to curl if it isn't.

We've had a hard Guzzle dependency in the past, but it collided with lots of other frameworks and setups having Guzzle already present.

Is curl available in your system if you do not pull in Guzzle?

**Comment by yachtino-dev** [comment]
Yes, our productive system has curl 7.64.0 installed.

**Comment by sandervanhooft** [comment]
Thanks @yachtino-dev .

We will try to reproduce the issue here, keeping this ticket open for reference.

**Comment by Naoray** [comment]
Hi @yachtino-dev,

in order to reproduce this issue I'd need more information about your server or the project setup in general.

Normally the `interface_exists()` shouldn't throw a file not found exception...

**Comment by yachtino-dev** [comment]
Hi @Naoray,
thank you. That was the right hint. You are right, the exception should not have been thrown. That was my special autoloader.
Is fixed now.
Sorry for the inconveniences. You can delete/close this thread.

**Comment by Naoray** [comment]
@yachtino-dev glad you figured it out!
