### ISSUE TITLE
Code ResourceFactory.php not compatible with PHP 8.2 or higher

### ISSUE THREAD

**Issue by bsconnect-nl** [mollie/mollie-api-php#711]
https://github.com/mollie/mollie-api-php/blob/d7d09ac62a565e818bf49d04acb2f0432da758a9/src/Resources/ResourceFactory.php#L21C1-L22C1

Creation of dynamic property Mollie\Api\Resources\Method::$resource is deprecated

**Comment by sandervanhooft** [comment]
Hi @bsconnect-nl ,

Thanks for reporting this. Can you please share:

- the exact php (i.e. 8.2.1) version you are using
- any non-default php configurations
- the exact mollie-api-php package version you're using (i.e. 2.30.1)

Looking at the GitHub test action running on php 8.2 I wouldn't expect this to happen, so your input would help us pinpoint the issue.

**Comment by bsconnect-nl** [comment]
Hi @sandervanhooft,

Thank you for your quick response!

- PHP Version 8.2.11
- I followed the documentation for implementation. The only adjustment in the package I made for the time being: @$resource->{$property} = $value;
- The mollie-api-php package version is 2.66.0

The class BaseResource only knows these properties: $client and $resource. When trying to define a different value for $property in ResourceFactory line number 21, the error will occur.

**Comment by Naoray** [comment]
Hi @bsconnect-nl,

You are right that the `BaseResource` only has a few defined properties. However, by using the `#[\AllowDynamicProperties]` we are able to bypass the limitation that all properties need to be defined before runtime. 

I have quickly run a test by using the `orders` endpoint `$client->orders->page()[0])` which uses exactly the `ResourceFactory@createFromApiResult()` method where the line is defined that you mention as problematic.

I used php 8.2.16 and mollie-api-php version of 2.66.0 and I didn't receive any errors.

What was the exact code you executed when this error occurred?
