### ISSUE TITLE
Order refunds

### ISSUE THREAD

**Issue by pepeh** [mollie/mollie-api-php#713]
## Specifications

  - API Version: 2

## Describe the issue
Method [Order::refunds](https://github.com/mollie/mollie-api-php/blob/d7d09ac62a565e818bf49d04acb2f0432da758a9/src/Resources/Order.php#L475) never returns order refunds. 

What is the correct way to get order refunds?

**Comment by sandervanhooft** [comment]
Hi @pepeh ,

Thanks for reaching out. Can you please share:

1. the package version you're using, i.e. 2.60.0
1. a code sample that produces the issue
1. the exact result you're getting
1. the result you were expecting

That helps us pinpoint the issue.

**Comment by pepeh** [comment]
@sandervanhooft This issue exists in all package versions (Lines changed 4-6 years ago)
[Order documentation](https://docs.mollie.com/reference/v2/orders-api/get-order) says 
`_links` object will contain `self`, `checkout`, `dashboard`, and `documentation` objects inside but [here code](https://github.com/mollie/mollie-api-php/blob/d7d09ac62a565e818bf49d04acb2f0432da758a9/src/Resources/Order.php#L477)  uses `$this->_links->refunds` that will never present inside order object

**Comment by pepeh** [comment]
According to the API documentation at [Mollie's Orders API](https://docs.mollie.com/reference/v2/orders-api/get-order), it appears that refunds are only included within the order object if the embed=refunds parameter is utilized. However, even with this parameter, the Order::refunds method may not function as expected since it relies on _links to access refunds.

Furthermore, when examining the documentation for [Order Refunds](https://docs.mollie.com/reference/v2/refunds-api/list-order-refunds), it's clear that retrieving refunds requires a separate HTTP request as demonstrated in the provided CURL example. Despite this, the PHP code snippet suggests accessing refunds directly through the Order object, akin to how it's approached in Node.js with a method that iterates over order refunds. This discrepancy suggests that there might be a more streamlined way to access refunds similar to the Node.js implementation, which uses mollieClient.orderRefunds.iterate({ orderId: 'ord_stTC2WHAuS' }) for a more intuitive and direct method of retrieval.

**Comment by pepeh** [comment]
>a code sample that produces the issue

@sandervanhooft The PHP code snippet provided mirrors what is found in the documentation available at [Mollie's Refunds API](https://docs.mollie.com/reference/v2/refunds-api/list-order-refunds)

```php
<?php
$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setApiKey("test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM");

$order = $mollie->orders->get("ord_stTC2WHAuS");
$refunds = $order->refunds();
```

**Comment by sandervanhooft** [comment]
Hi @pepeh ,

It looks like you're right! Investigating.

**Comment by sandervanhooft** [comment]
A patch is being prepared in #714

**Comment by sandervanhooft** [comment]
@pepeh Once this patch is released you can shave off a call to the Mollie API:

```php
<?php
$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setApiKey("test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM");

// $order = $mollie->orders->get("ord_stTC2WHAuS"); // no longer required to fetch the Order first
$refunds = $mollie->orderRefunds->pageForId("ord_stTC2WHAuS");
```
