### ISSUE TITLE
Preparing for iDEAL 2.0

### ISSUE THREAD

**Issue by arjen-mediasoep** [mollie/mollie-api-php#719]
Hi, 

I've received an email notification about the new iDEAL 2.0 integration for WooCommerce, where you will have to disable to issuer list when you update the plugin July 1st. How will that work with this library? Will the following line become unnecessary? 
https://github.com/mollie/mollie-api-php/blob/ed5b2ba1dc8f30a4674f10ca78ad547c2df91008/examples/payments/create-ideal-payment.php#L66
Are there any other changes that I can take into account?

Thanks!

**Comment by sandervanhooft** [comment]
Excellent question! Let me check this with the Mollie team and get back to you.

**Comment by sandervanhooft** [comment]
Hi @arjen-mediasoep ,

I recommend leaving the `issuer` parameter in for now while keeping an eye out for further news.

Mollie is double checking with the new standard if this really needs to be deprecated.

In case of deprecation:
- Mollie will reach out with updated information
- Mollie will ensure continued use of the `issuer` parameter on the v2 api will not break your integration.

I hope that helps, feel free to reach out if you need any more information.
