### ISSUE TITLE
Webhook failed with status code 502

### ISSUE THREAD

**Issue by Wiering** [mollie/mollie-api-php#72]
My webhook always fails with code 502.
The code is never called, and I can even set the webhook to a non-existing URL and it still fails with 502 (not 404 as I would expect).
Any ideas?

**Comment by Wiering** [comment]
Strangely, I can set up the webhook on different websites and that works fine, except for one, which is hosted by the same provider (mijndomein) as the site I'm having this problem with.

**Comment by JorikMollie** [comment]
To investigate this issue I need some information that is private. So can you send a mail to techsupport@mollie.com with the transaction IDs from the payments that result in a 502?
