### ISSUE TITLE
[Question] mollie-api-php and iDeal 2.0?

### ISSUE THREAD

**Issue by Jelmerkeij** [mollie/mollie-api-php#739]
Hello, I would like to make sure that there are no changes needed for the introduction of iDeal 2.0 when using this package?
[This article on migrating to iDeal 2.0](https://help.mollie.com/hc/en-us/articles/19100313768338-iDEAL-2-0?input_string=mollie+ideal+2.0#h_01HYJ9GTTXN7A1WDAQ2NJT1MBW) mentions that "Mollie checkout" will be automatically migrated by July. I'm aware that the biggest change is not sending any issuer when creating a payment, but other than that is there any action required? Will the current 2.x version of `mollie-api-php` support iDeal 2.0 or are there any other changes or updated needed?

Thanks for your time!

**Comment by sandervanhooft** [comment]
Spot on, no further action required!
