### ISSUE TITLE
Incorrect example OAuth tokens

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#74]
_First of all, is the API documentation available on GitHub somewhere? Might be an idea to allow easy feedback from the community and prevent pollution of this repository with these (simple / typo-related) issues..._

The [example about OAuth tokens](https://www.mollie.com/en/docs/reference/oauth/tokens#example) contains the following snippet:

```php
$expires       = $response->getExpires();
...
echo "Access token expires in " . intval($expires) . " seconds.";
```

However, it seems `$response->getExpires()` returns the Unix timestamp when the token will expire, **not the number of seconds up until expiration** as can be derived from [this section](https://github.com/thephpleague/oauth2-client/blob/313250eab923e673a5c0c8f463f443ee79f4383f/src/Token/AccessToken.php#L76-L95) and [this PHPDoc of getExpires()](https://github.com/thephpleague/oauth2-client/blob/313250eab923e673a5c0c8f463f443ee79f4383f/src/Token/AccessToken.php#L143-L147)

**Comment by willemstuursma** [comment]
Hi @holtkamp. I am sorry to hear not everything is clear and will see if I can clear it up a bit today.

The PHPDoc says: _ Returns the expiration timestamp, if defined._ 

So it should return a timestamp. We do this correctly, but the examples are incorrect. I'll see to it that they are updated today. 

The field `expires_in` is used for the seconds until the token expires.

**Comment by holtkamp** [comment]
@willemstuursma yeah, it seems it is just the example that is confusing. Would you guys consider to place the API documentation on GitHub, so a simple pull request to change the example would have sufficed?

**Comment by willemstuursma** [comment]
@holtkamp We've thought about it a few times, but always run into the issue that it would be difficult to integrate the documentation in our public web site. I'll bring it up again.

The examples are now updated.
