### ISSUE TITLE
Pass queryparameters (like profileId) to the delete method

### ISSUE THREAD

**Issue by 3ops-jgheeraert** [mollie/mollie-api-php#743]
## Specifications

  - API Version: 2.8.1

## Describe the issue

When using the delete function, only a paymentlink id can be passed to the delete method. The profileId is required when using access token in stead of api key. Workaround is now to performHttpCall directly with the profileId as queryparam.

**Comment by sandervanhooft** [comment]
Hi @3ops-jgheeraert ,

Thanks for reaching out. I am not entirely sure if this was merged after your issue ticket, but it's possible to pass additional data:

https://github.com/mollie/mollie-api-php/blob/0a26175492d4c55bb461e44fe3e63546539b81c1/src/Endpoints/PaymentLinkEndpoint.php#L36-L51


If this doesn't work for you, could you please share a code sample that helps us reproduce the issue?

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
