### ISSUE TITLE
Is this 422 error valid?

### ISSUE THREAD

**Issue by alecpl** [mollie/mollie-api-php#745]
## Specifications

  - API Version: 2.73.0

## Describe the issue

Sorry if that's not the proper channel. I see in my logs that sometimes if I attempt to create a recurring payment, with mandateId field, it fails with 422 response: "The card was not found".

I'd like to note that I check mandate validity before attempting to create payment. So, I assume it was valid.

What "The card was not found" means exactly? Is this proper 422 reason?

ps. I'm not 100% sure, but if that happens the payment is being created anyway. Is it possible?

**Comment by sandervanhooft** [comment]
Hi @alecpl ,

Thanks for reaching out. This doesn't seem like an issue related to this package.

For support on this particular issue I recommend reaching out to Mollie support as this seems related to very specific transactions and to your account specifically.

https://www.mollie.com/gb/contact/merchants
