### ISSUE TITLE
OAuth2: Can expired AccessTokens be renewed / do the RefreshTokens expire?

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#75]
When working with OAuth, the acquired AccessTokens expire in 3600 seconds. To prevent them from expiring, they can be refreshed using the RefreshToken.

The documentation states about [the response](https://www.mollie.com/en/docs/reference/oauth/tokens#response):

- `refresh_token`: The refresh token, with which you will be able to retrieve new access tokens on this endpoint.
- `expires_in`: The number of seconds left before the access token expires. **Be sure to refresh your access token before this reaches zero**.

and: 

_"Now that we have a refresh token, we should **refresh the access token before its expiry date** as follows."_

**Two questions**
1. The combination of aforementioned documentation kind of "suggests" that the AccessToken can NOT be refreshed anymore after it has expired. This seems awkward to me. For example, after the AccessToken has expired for, lets say, two weeks, we should still be able to refresh it right? Or is it expected that an AccessToken is kept "valid" all the time by periodically refreshing them?

2. Does the RefreshToken itself have an expiry time? Some OAuth servers use this, it seems not documented how Mollie deals with this...

For some documentation, see:
- https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/
- https://github.com/bshaffer/oauth2-server-php/issues/628 

**Rationale**
The reason I am asking for some clarification / better examples, is that our attempts to refreshing a (long) expired AccessToken keeps on resulting in `invalid_grant` errors... When testing the refreshing/renewing functionality, it works when an AccessToken has been expired for a short period, but not for a long period, for example:

- expired 15 minutes ago: works
- expired 1,5 hour ago: works
- expired 12 hour ago : works
- expired 24 hour ago : **fails**
  - `Mollie_API_Exception: Error executing API call (request): Unauthorized request. in /app/vendor/mollie/mollie-api-php/src/Mollie/API/Resource/Base.php:353`

So when the AccessToken has been expired for multiple days / weeks, the error occurs; it seems the RefreshToken itself also expires? Some of our reseller partners do not have a "lot" of Mollie Payments. In these cases an RefreshToken that does NOT expire would be preferred.

**UPDATE**
After reading [this article](https://medium.com/@bantic/more-oauth-2-0-surprises-the-refresh-token-1831d71f4af6), I think the documentation can be clarified a bit. AccessTokens are *renewed* / replaced, not refreshed. 

This still leaves me with the question whether the RefreshTokens that are used to request new AccessTokens expire themselves as well?

**Comment by AntonShumin** [comment]
I'd also like to know this. 

I've been told that the access token lives 3600 seconds, which would be an hour. 
Fine, i stored the refresh token. Lets get it with  
`getAccessToken($grant, ["refresh_token" => $refresh_token]);`

But if the refresh token also expires as mentioned above (somewhere between 12 and 24h), then i should be building the code around `getAccessToken( "authorization_code", .. ` instead of refresh tokens 

which kinda makes sense for security reasons but makes me wonder how useful those refresh tokens are. I would imaging that if the access token is compromised, the refresh token would be as well.

**Comment by holtkamp** [comment]
>But if the refresh token also expires as mentioned above (somewhere between 12 and 24h), then i should be building the code around getAccessToken( "authorization_code", .. instead of refresh tokens.

Yeah, when also the RefreshToken has become invalid, a complete new authorization needs to be given, in our case by the reseller partner. Which would be difficult to realize / expect from them.

>Are we maybe expected to run a cronjob every day to keep refresh tokens alive?

I think that this would be the way to go, but I would rather not have this additional "responsibility" of keeping all the tokens valid. Therefore I plea for non-expiring RefreshTokens, which is also the way [Google Auth server works](http://stackoverflow.com/a/8954103)

**Comment by willemstuursma** [comment]
> Therefore I plea for non-expiring RefreshTokens, which is also the way Google Auth server works, which is an engineering decision. 

We're going to look into this (our reference INI-117). 

> Are we maybe expected to run a cronjob every day to keep refresh tokens alive?

For now, this is the way to go.

**Comment by AntonShumin** [comment]
> Yeah, when also the RefreshToken has become invalid, a complete new authorization needs to be given, in our case by the reseller partner.

Yes of course! If godforbid the refresh token expires (something like a cronjob server outage), our payment system would be rendered useless until the partner authorizes the app again. What a nightmare

**Comment by AntonShumin** [comment]
I've just used a 2 days old refresh token (created on friday, refreshed on monday)
and to my surprise it worked. 

So do they expire? And if so, when?

**Comment by willemstuursma** [comment]
> So do they expire? And if so, when?

Refresh tokens are valid for two weeks.

**Comment by holtkamp** [comment]
> Refresh tokens are valid for two weeks.

Ok, good to know. Will double check why mine failed to refresh after 24 hours...

**Comment by AntonShumin** [comment]
@holtkamp 

I've been refreshing multiple tokens older than 24h for about 3 weeks now. Have a cronjob running every 4 days, no problems so far.
Some of them were as old as 12 days. 

When you refresh a token, are you also saving the refreshed **refresh-token**

**Comment by holtkamp** [comment]
ok, thanks for sharing your experience. Then probably our refresh mechanism
needs a double check, will report back next week.

**Comment by holtkamp** [comment]
**Update**
I can confirm that there was a problem with the way we tried to refresh the AccessToken and the RefreshToken. Strange that using an expired AccessToken did work for up to around 20 hours...

**Conclusion**
Taken into account that:

>Refresh tokens are valid for two weeks.

One should implement a background task which periodically refreshes AccessTokens and RefreshTokens at least once every two weeks. When this is **not** done (properly), the access is revoked and a partner should explicitly grant access again.

I think this issue can now be closed? In case the expiry time of two weeks changes (investigated in Mollies internal issue `INI-117`, this can always be added as a comment...

**Comment by willemstuursma** [comment]
Thanks @AntonShumin for clearing this up. @holtkamp you can reach me here if you need any help.

**Comment by willemstuursma** [comment]
We are looking to make some changes soon:

* No longer expire refresh tokens.
* No longer grant a new refresh token each time a new access token is retrieved.

Any feedback @holtkamp and @AntonShumin?

**Comment by holtkamp** [comment]
@willemstuursma 

>No longer expire refresh tokens.

Great!

>No longer grant a new refresh token each time a new access token is retrieved.

mmm, on this subject I do not have an opinion backed by (objective) arguments. I would go with any 'industry best practice', if there is any...

Thanks for listening to the feedback of users!

**Comment by shirshir** [comment]
@holtkamp @AntonShumin We have changed our API so that a refresh token does not expire anymore. Every time you refresh an access token you will receive the same refresh token, together with the new access token.

**Comment by AntonShumin** [comment]
This is great! Refreshing both tokens on every single transaction was making me nervous 
Does the two weekly reset still apply, or is the refresh token permanent forever?

**Comment by florinciubotariu** [comment]
@willemstuursma 
Can you confirm that the refresh never expires at this moment?
