### ISSUE TITLE
Call to undefined method Mollie\Api\MollieApiClient::customers()

### ISSUE THREAD

**Issue by informatJonas** [mollie/mollie-api-php#751]
## Specifications

  - Package Version: 2.74.1

## Describe the issue

...

**Comment by sandervanhooft** [comment]
Hi @informatJonas ,

Please use `$mollie->customers->...` instead.

**Comment by informatJonas** [comment]
pls update the docu at [here](https://docs.mollie.com/reference/list-customers)

**Comment by informatJonas** [comment]
Why doesn't the SDK actually have a function to display the list? - Except perhaps via page()

**Comment by sandervanhooft** [comment]
> Why doesn't the SDK actually have a function to display the list? - Except perhaps via page()

For consistency, and also using this signature would collide with some derived packages like laravel-mollie. Plus on v3 we're introducing `->customers()->page()` that will eventually replace`->customers->page()` so we can lazily instantiate the endpoints.
