### ISSUE TITLE
Mollie status doesn't update

### ISSUE THREAD

**Issue by daniellegeelen** [mollie/mollie-api-php#76]
Hello,

I'm trying to use mollie 01-new-payment but when I am at the returning page (after chosing a paymethod and bank and klik on payment suceeded, go to site) it sais that the status is open. And it stays open  On my webhook verification I placed on the begining of the file:
```
$testdatabase = dirname(__FILE__) . "/orders/test.txt";
		file_put_contents($testdatabase, "catch");
```
To test if the fle was executed, the file did not apear.
The file with the text open (is created in 01-new-payment ) does apear But the file doesn't get updated.

It is an wordpress site and for testig reasons the page it is not publiced yet could it have to do something with that?
I would expect an error about that the webhook isnt reached or something like that, but it isn't.

I hope You onderstand me, if not feel free to ask anny question :)

**Comment by JorikMollie** [comment]
Is the webhook URL reachable by our servers / the public internet? If we can't reach your server we also can't call the webhook.

**Comment by daniellegeelen** [comment]
mmh I think your right when i try to reach the webhookurl from another pc i don't get on the site. I think I have to put the wrdpress site live, thank you for your fast replay :)

**Comment by daniellegeelen** [comment]
YAY in my mollie account I now see that they are paid but the text file isn't changing i did use chmod($database,0666); but it didn't help, I know Mollie says I have to use a real database but do you know if it is posseble without or with a file? I tried to reseve te GET variable in the returning page but i can't get the payment id isn't it?

**Comment by robertmollie** [comment]
I think this should also work without a file, as long your API can receive the status from our webhook: https://www.mollie.com/nl/docs/webhook.

**Comment by daniellegeelen** [comment]
that sounds nice, it sais: "At this URL you should place a script that – when it's called – fetches the payment status and processes it, if it has changed." I tried to send a mail with contact form 7 (I dit fll it in wit jquery and did a trigger click) but i didn't receve an emaill, is it posible to execute jquery/javascript at the webhoook code?

**Comment by willemstuursma** [comment]
> I tried to send a mail with contact form 7 (I dit fll it in wit jquery and did a trigger click) but i didn't receve an emaill, is it posible to execute jquery/javascript at the webhoook code?

No. The script needs to be executed server side. You cannot use any Javascript / jQuery as it will be ignored by (any) server to server communications.

**Comment by daniellegeelen** [comment]
Then I have to store the data anywere or can id get de order status in my retuning page without reading it from anny storing place? I know that if the website isn't reachable it won't work.

Is it true that if in my mollie dashboard the status is paid that the webhook worked?

I ask Because I tried it with a database (I don't want a database but if there is no other way...) the database is on my localhost can that be the problem? because that din't work eiter.

I am lost, I don't know how to fix this. I just want to have a status variable in my returning page. and I wonder why i cant create a file with fopen ofcorse I am using my test API key mabe it has someting to do ith that? 

in the webhook code I see this:

 `if (!empty($_GET['testByMollie']))
	{
		die('OK');
	}`

what does it mean?

**Comment by willemstuursma** [comment]
> Then I have to store the data anywere or can id get de order status in my retuning page without reading it from anny storing place?

Yes, you have to store the order state somewhere to pass it from the webhook to the return page. 

> Is it true that if in my mollie dashboard the status is paid that the webhook worked?

No, the status in the Mollie Dashboard is paid if the payment was paid. Reporting does not affect the status. 

> `if (!empty($_GET['testByMollie'])) { die('OK'); }`

Sorry, this serves no purpose anymore. We used this for testing if we could reach the webhook but we have removed that function since. 

> I am lost, I don't know how to fix this. I just want to have a status variable in my returning page. 

You need to retrieve the payment status from the webhook, and then store this in your application with the order. On the return page, you should retrieve the order from your database or a file.
