### ISSUE TITLE
Get payment exception, invalid payment id

### ISSUE THREAD

**Issue by AntonShumin** [mollie/mollie-api-php#77]
I am trying to process the webhook and check the payment status, but keep getting the "payment id is invalid".
And i know that it's valid, i've created it a few seconds earlier, plus its a _POST parameter.
(i've also tried hardcoding the payment_id (tr_fKme26vE7m), the same issue)
 
**I am making payments in Testmode, Oauth for authentication.** 

```
$mollie_token = "access_89..";
$mollie_payment_id = $_POST['id'];

$mollie = new Mollie_API_Client;
$mollie->setAccessToken($mollie_token);


try {
    $payment = $mollie->payments->get( $mollie_payment_id, array("testmode" => true) );
    var_dump($payment);
} catch (Exception $e) {
    var_dump($e);
}
```

This gives me an exception:
  **protected 'message'** => string 'Error executing API call (request): The payment id is invalid.' (length=62)
  **protected 'code'** => int 0
  **protected 'file**' => string 'C:\wamp64\www\kivalo\inc\vendor\mollie\mollie-api-php\src\Mollie\API\Resource\Base.php' (length=86)
  **protected 'line'** => int 353

**Comment by AntonShumin** [comment]
Alright, i ran through all of my code a few times. It seems that this specific payment tr_fKme26vE7m was made using a regular API key authentication and not on behalf of the Oauth authenticated profile. Once i created a new payment properly, patments->get worked as advertised

**Comment by willemstuursma** [comment]
Hi @AntonShumin. The payment `tr_fKme26vE7m` was created in test mode. 

You can retrieve it by adding `?testmode=true` to the API call to [get the payment](https://www.mollie.com/nl/docs/reference/payments/get). 

In our client, you can do this by sending:

```$mollie->payments->get('tr_fKme26vE7m', ['testmode'=>'true']);```
