### ISSUE TITLE
Retrieve all payment methods activated on the payment profile

### ISSUE THREAD

**Issue by DePalmo** [mollie/mollie-api-php#78]
On documentation page: https://www.mollie.com/be/docs/reference/methods/list it says that we can get a list of all activated payment methods, but when I execute the sample code it completely ignores payment method status and it lists all. I tried this with test and live API keys and the end result is the same.
Also, API doesn't return payment method status, so we can't know which one is enabled and which isn't.

**Comment by ndijkstra** [comment]
Hi, 

The API lists only the active payment methods of the profile. With the Test API-key all the payment methods are activated.

**Comment by DePalmo** [comment]
I would expect that test environment does reflect live environment as close as possible, so this should not happen.

Will re-confirm about the live one once again and report back.

**Comment by DePalmo** [comment]
I'm sorry to say but live also doesn't follow enabled/disabled payment methods statuses, but it also lists all. Please see attached.

Code I used:
```
require_once('mollie-api-php-master/src/Mollie/API/Autoloader.php');
$mollie=new Mollie_API_Client;
$mollie->setApiKey('live_xxx');

// list available payment methods
$methods = $mollie->methods->all(0,20);
echo'Payment methods found:<br>'."\n";
echo'<ul>';
foreach ($methods as $method){
	echo'<li>'.
		htmlspecialchars($method->description).' (' .  htmlspecialchars($method->id). ')'.
		'</li>';
}
echo'</ul>';

```
![2017-06-27 13-11 image 004](https://user-images.githubusercontent.com/3665779/27585005-b082d91a-5b3a-11e7-8acc-7c415ef6c5a0.jpg)
![2017-06-27 13-13 image 001](https://user-images.githubusercontent.com/3665779/27585006-b0879ebe-5b3a-11e7-9254-da02273540e9.jpg)

**Comment by ndijkstra** [comment]
Are you sure that you are using the Live API-key? And can you tell me your Partner ID?

**Comment by DePalmo** [comment]
100% sure, I double checked. I would prefer not to share any info publicly, can I forward it privately?

**Comment by ndijkstra** [comment]
Sure, can you send your questions to techsupport@mollie.com ?

**Comment by DePalmo** [comment]
Just to post a comment for future readers, I have found an issue. The live API key was being replaced with test one in my code, that's why it returned all payment methods.

But I still consider this as a bug in test environment where it returns all payment methods, not just activated ones. If this could be fixed as well, that would be superb.
