### ISSUE TITLE
Update Subscription

### ISSUE THREAD

**Issue by petericebear** [mollie/mollie-api-php#80]
Hi,

Is it possible to update a subscription?

A general use case is for instance payment per seat. If someone updates his number of users(seats). 
It looks like we now have to cancel the subscription and create a new one.

In Stripe you have proration by updating a subscription to a new one. Is this possible to reproduce with Mollie Subscriptions?

Thanks in advance,
Greetings,
Peter

**Comment by ndijkstra** [comment]
Hi Peter,

Updating a subscription is not possible. You have to cancel the subscription and create a new one.

Best regards,
Nick

**Comment by petericebear** [comment]
Is it on the roadmap to implement the update feature?
Or do you have a best practice for this?

**Comment by willemstuursma** [comment]
Can you tell us a bit about the kind of updates you would like to do?

**Comment by petericebear** [comment]
Updates for payments like this scenario. Payment per user.
We now have a plan of 5 EURO + 1 EURO per seat.

For 1 seat it is: a subscription for 6 EURO.
When I add a seat in our program I would like to update the amount to 7 EURO's. Not cancelling a subscriptions but to update the amount of money. 
Best with proration, so if the current subscription still lasts for 10 days for 1 month. It adds the amount for the days with the next payment. (it could be higher or lower).

So for 30 days in a month it adds 10 / 30 * amount of the difference. Higher or lower depending on the difference of the amount.

**Comment by petericebear** [comment]
It is a common case with subscriptions like in the hosting industry. You can update a CPU or RAM in the middle of the month. Or downgrade the CPU later on. But if an upgrade is doable that would be really great.

**Comment by petericebear** [comment]
https://stripe.com/docs/subscriptions/upgrading-downgrading
