### ISSUE TITLE
How to fetch payment id

### ISSUE THREAD

**Issue by sahilbalani15** [mollie/mollie-api-php#82]
Hello,

I have been trying with the examples, but when I open the new-payment.php then it redirects to the payment gateway and after paying it sends to 03-return-page.php. When I try to open 02-webhook-verification it gives me an error "API call failed: Invalid payment ID: ''. A payment ID should start with 'tr_'."
How do I fetch the payment id when page returns for that particular payment, also how do I fetch the response code after that?

Thanks

**Comment by ndijkstra** [comment]
Hi,
We will do a POST request to your webhookUrl. In this POST request we send the "id" parameter with the Payment ID.

For the redirectUrl you can save the status in your database (via the webhook) and retrieve it on the redirectUrl page.

**Comment by sahilbalani15** [comment]
Hello,

So how do I fetch the same in example 3 ?
Also how do ai fetch the reponse code when payment is sent or updated in
third example.

Thanks in advance


On 20 Jul 2017 20:44, "Nick Dijkstra" <notifications@github.com> wrote:

Hi,
We will do a POST request to your webhookUrl. In this POST request we send
the "id" parameter with the Payment ID.

For the redirectUrl you can save the status in your database (via the
webhook) and retrieve it on the redirectUrl page.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mollie/mollie-api-php/issues/82#issuecomment-316735369>,
or mute the thread

**Comment by ndijkstra** [comment]
You have to save it in your own database after you've created the payment. We don't send it with the redirectUrl only with the webhookUrl.

**Comment by sahilbalani15** [comment]
Alright.  Thanks. Can you help me with one more thing please.
If you can give me a code on core php on how do I save all these codes that
would be great and really helpful to me. I want to save response code.
Thanks

**Comment by ndijkstra** [comment]
Unfortunately we don't have more examples then those in this client. Please read our documentation  for more information: https://www.mollie.com/nl/docs/reference/payments/get
