### ISSUE TITLE
Missing function Payment::isFailed()

### ISSUE THREAD

**Issue by holtkamp** [mollie/mollie-api-php#83]
Just noticed that no helper function exists for [the "failed" status](https://github.com/mollie/mollie-api-php/blob/5327e813fd9f1f15a1932f5d6ea17fb35faa8b1a/src/Mollie/API/Object/Payment.php#L78)

- there are 9 `STATUS_XYZ` constants
- there are 8 `isXYZ()` helper functions

Not a big problem, but would be nice to be "complete" 😄

**Comment by willemstuursma** [comment]
Thanks, this has been added @holtkamp by @PerryZ.

**Comment by willemstuursma** [comment]
We'll release a new version later this week.
