### ISSUE TITLE
namespaced classes

### ISSUE THREAD

**Issue by extcode** [mollie/mollie-api-php#86]
It would be nice to have namespaced classes. This would simplify the classes to instantiate or to extend. 

I would ship this API as legacy phar-library for non composer installations in my shopping provider extension. Having namespaced classes allow easier handling.

**Comment by willemstuursma** [comment]
Sorry, we won't move to namespaced classes as we are still using this package for Wordpress / WooCommerce which still supports PHP 5.3.

**Comment by willemstuursma** [comment]
Namespaced classes will be available in 2.0.
