### ISSUE TITLE
Delay first payment of subscription or give free trial

### ISSUE THREAD

**Issue by DePalmo** [mollie/mollie-api-php#87]
We're using a subscription module and after some errors we made it working properly, but now we're facing with a real life issue. This is what I got from my client today:
_"Sometimes I make agreements with people to extend their premium subscription. e.g. I have a special offer at the moment where I give them 2 month free if they purchase an annual subscription. How do we deal with that?"_

So, how do we deal with that? I didn't find anything useful in the docs except that after first payment, I can set when the second payment starts but that's not really user friendly, so other option is to delay first payment for a selected period of time. Is this possible? If not, how do you recommend that we deal with this situation?

**Comment by kloentje2** [comment]
Maybe you can fix that in your coding? I think mollie is only a psp and they don't offer much more.

**Comment by DePalmo** [comment]
I would "fix" it if I would know how. To get customer's permission, I need to do a first payment and customers are billed right then and there. I could then insert the 2 months free period before subscription kicks in, but this is not how things are normally done and it would also continuously bill each next month.

Also, to make this really working, I would need to have a subscription that would bill 10 of 12 months automatically (depending on the package customer has selected), cancelling and restarting subscription is not an option in this case since that defeats the purpose of subscription.

**Comment by arendvw** [comment]
A common way to do this is to charge monthly, but add a discount of two months divided over 12 months = 16% discount on all months. 

Also, many places will only issue such discount if you actually pay at once for a year, to prevent all the hassle with subscriptions being cancelled halfway through by means of creditcards.

**Comment by DePalmo** [comment]
Your last idea sounds reasonable and truly something that's being done, not sure why I didn't thought of that before. Thank you!
