### ISSUE TITLE
Cancelled subscription returns exception, not subscription object with status

### ISSUE THREAD

**Issue by DePalmo** [mollie/mollie-api-php#88]
Scenario: We create a new subscription through Mollie API (PHP) and later on it can be canceled. After that, our system checks subscription status (for further processing) and it's expected to get an object back with subscription status like: "cancelled" and ideally date when it was cancelled, but we get an Exception thrown.

Why is that? Isn't more logical to get back a proper response with details in the object itself? Now we have to match text returned by exception to do further processing.

**Comment by willemstuursma** [comment]
Because the HTTP verb `DELETE` is used for cancelling a subscription, we have removed cancelled subscriptions from the API and they can no longer be retrieved. 

This is why you are getting an exception. In the API, the cancelled subscription no longer exists.

**Comment by Casmo** [comment]
I have the same problem. I get an exception with the message "Error executing API call (request): The subscription has been cancelled." When I delete the subscription.

The API is still documented: https://www.mollie.com/en/docs/reference/subscriptions/delete. How do I stop or cancel a subscription in an other way without raising an exception?
